#line 1 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
#line 6 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
#pragma warning(disable:4008)
#line 7 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
#line 1 "/Engine/Public/Platform.ush"
#line 9 "/Engine/Public/Platform.ush"
#line 1 "FP16Math.ush"
#line 10 "/Engine/Public/Platform.ush"
#line 43 "/Engine/Public/Platform.ush"
#line 1 "ShaderVersion.ush"
#line 44 "/Engine/Public/Platform.ush"
#line 595 "/Engine/Public/Platform.ush"
float min3( float a, float b, float c )
{
	return min( a, min( b, c ) );
}

float max3( float a, float b, float c )
{
	return max( a, max( b, c ) );
}

float2 min3( float2 a, float2 b, float2 c )
{
	return float2(
		min3( a.x, b.x, c.x ),
		min3( a.y, b.y, c.y )
	);
}

float2 max3( float2 a, float2 b, float2 c )
{
	return float2(
		max3( a.x, b.x, c.x ),
		max3( a.y, b.y, c.y )
	);
}

float3 max3( float3 a, float3 b, float3 c )
{
	return float3(
		max3( a.x, b.x, c.x ),
		max3( a.y, b.y, c.y ),
		max3( a.z, b.z, c.z )
	);
}

float3 min3( float3 a, float3 b, float3 c )
{
	return float3(
		min3( a.x, b.x, c.x ),
		min3( a.y, b.y, c.y ),
		min3( a.z, b.z, c.z )
	);
}

float4 min3( float4 a, float4 b, float4 c )
{
	return float4(
		min3( a.x, b.x, c.x ),
		min3( a.y, b.y, c.y ),
		min3( a.z, b.z, c.z ),
		min3( a.w, b.w, c.w )
	);
}

float4 max3( float4 a, float4 b, float4 c )
{
	return float4(
		max3( a.x, b.x, c.x ),
		max3( a.y, b.y, c.y ),
		max3( a.z, b.z, c.z ),
		max3( a.w, b.w, c.w )
	);
}




float UnpackByte0(uint v) { return float(v & 0xff); }
float UnpackByte1(uint v) { return float((v >> 8) & 0xff); }
float UnpackByte2(uint v) { return float((v >> 16) & 0xff); }
float UnpackByte3(uint v) { return float(v >> 24); }
#line 8 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"






	const static float PI = 3.1415926535897932f;

	const static float TWO_PI = 3.1415926535897932f*2.0f;
#line 18 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
#line 1 "/Engine/Private/Definitions.usf"
#line 19 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"


float4 ModuloPrecise(float4 x, float4 y){ return x - y * trunc(x/y); }
float3 ModuloPrecise(float3 x, float3 y){ return x - y * trunc(x/y); }
float2 ModuloPrecise(float2 x, float2 y){ return x - y * trunc(x/y);}
float ModuloPrecise(float x, float y){ return x - y * trunc(x/y); }
int ModuloPrecise(int x, int y){ return x - y * (x/y); }
int Modulo(int x, int y){ return x - y * (x/y); }



float4 Reciprocal(float4 x){ return 1.0f/x;}
float3 Reciprocal(float3 x){ return 1.0f/x; }
float2 Reciprocal(float2 x){ return 1.0f/x;}
float Reciprocal(float x){ return 1.0f/x; }



bool NiagaraAll(bool b) { return b; }
bool NiagaraAny(bool b) { return b; }









bool NiagaraAll(bool2 b) { return b.x && b.y; }
bool NiagaraAll(bool3 b) { return b.x && b.y && b.z; }
bool NiagaraAll(bool4 b) { return b.x && b.y && b.z && b.w; }
bool NiagaraAny(bool2 b) { return b.x || b.y; }
bool NiagaraAny(bool3 b) { return b.x || b.y || b.z; }
bool NiagaraAny(bool4 b) { return b.x || b.y || b.z || b.w; }
#line 193 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
float4 rand4(int Seed1, int Seed2, int Seed3, int Seed4)
{
	int4 v = int4(Seed4, Seed1, Seed2, Seed3) * 1664525 + 1013904223;

	v.x += v.y*v.w;
	v.y += v.z*v.x;
	v.z += v.x*v.y;
	v.w += v.y*v.z;
	v.x += v.y*v.w;
	v.y += v.z*v.x;
	v.z += v.x*v.y;
	v.w += v.y*v.z;






	return float4((v >> 8) & 0x00ffffff) / 16777216.0;

}







float3 rand3(int Seed1, int Seed2, int Seed3, int Seed4)
{
	int3 v = int3(Seed1, Seed2, Seed4 | (Seed3 << 16)) * 1664525 + 1013904223;

	v.x += v.y*v.z;
	v.y += v.z*v.x;
	v.z += v.x*v.y;
	v.x += v.y*v.z;
	v.y += v.z*v.x;
	v.z += v.x*v.y;

	return float3((v >> 8) & 0x00ffffff) / 16777216.0;
}


static int RandomCounterDeterministic = 0;


float rand(float x, int Seed1, int Seed2, int Seed3)
{
	RandomCounterDeterministic += 1;
	return rand3(Seed1, Seed2, Seed3, RandomCounterDeterministic).x * x;
}


float2 rand(float2 x, int Seed1, int Seed2, int Seed3)
{
	RandomCounterDeterministic += 1;
	return rand3(Seed1, Seed2, Seed3, RandomCounterDeterministic).xy * x;
}


float3 rand(float3 x, int Seed1, int Seed2, int Seed3)
{
	RandomCounterDeterministic += 1;
	return rand3(Seed1, Seed2, Seed3, RandomCounterDeterministic).xyz * x;
}


float4 rand(float4 x, int Seed1, int Seed2, int Seed3)
{
	RandomCounterDeterministic += 1;
	return rand4(Seed1, Seed2, Seed3, RandomCounterDeterministic).xyzw * x;
}


int rand(int x, int Seed1, int Seed2, int Seed3)
{


	RandomCounterDeterministic += 1;
	return int(rand3(Seed1, Seed2, Seed3, RandomCounterDeterministic).x * (x+1));
}
#line 323 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
	float rand(float x);

	float2 rand(float2 x)
	{
		return float2(rand(x.x), rand(x.y));
	}

	float3 rand(float3 x)
	{
		return float3(rand(x.x), rand(x.y), rand(x.z));
	}

	float4 rand(float4 x)
	{
		return float4(rand(x.x), rand(x.y), rand(x.z), rand(x.w));
	}

	int rand(int x);



float rand_float(float x)
{
	return rand(x.x);
}

float2 rand_float(float2 x)
{
	return float2(rand_float(x.x), rand_float(x.y));
}

float3 rand_float(float3 x)
{
	return float3(rand_float(x.x), rand_float(x.y), rand_float(x.z));
}

float4 rand_float(float4 x)
{
	return float4(rand_float(x.x), rand_float(x.y), rand_float(x.z), rand_float(x.w));
}

int rand_int(int x)
{



	return rand_float(x.x);
}


float rand_float(float x, int Seed1, int Seed2, int Seed3)
{
	return rand(x.x, Seed1, Seed2, Seed3);
}

float2 rand_float(float2 x, int Seed1, int Seed2, int Seed3)
{
	return rand(x, Seed1, Seed2, Seed3);
}

float3 rand_float(float3 x, int Seed1, int Seed2, int Seed3)
{
	return rand(x, Seed1, Seed2, Seed3);
}

float4 rand_float(float4 x, int Seed1, int Seed2, int Seed3)
{
	return rand(x, Seed1, Seed2, Seed3);
}

int rand_int(int x, int Seed1, int Seed2, int Seed3)
{


	return rand(x.x-1, Seed1, Seed2, Seed3);
}
#line 405 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
	float noise(float x);
	float noise(float2 x);
	float noise(float3 x);



	float4 Modulo(float4 x, float4 y);
	float3 Modulo(float3 x, float3 y);
	float2 Modulo(float2 x, float2 y);
	float Modulo(float x, float y);


	int ExecIndex();



	int AcquireIndex(int DataSetID, bool DoAcquire);

	void AcquireID(int DataSetID, out int IDIndex, out int IDAcquireTag);
	void UpdateID(int DataSetID, int IDIndex, int InstanceIndex);

	float InputDataFloat(int DataSetIndex, int RegisterIdx);
	int InputDataInt(int DataSetIndex, int RegisterIdx);
	bool InputDataBool(int DataSetIndex, int RegisterIdx);

	float InputDataNoadvanceFloat(int DataSetIndex, int RegisterIdx);
	int InputDataNoadvanceInt(int DataSetIndex, int RegisterIdx);
	bool InputDataNoadvanceBool(int DataSetIndex, int RegisterIdx);

	void OutputDataFloat(int DataSetIndex, int RegisterIndex, int InstanceIndex, float Value);
	void OutputDataInt(int DataSetIndex, int RegisterIndex, int InstanceIndex, int Value);
	void OutputDataBool(int DataSetIndex, int RegisterIndex, int InstanceIndex, bool Value);
#line 683 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
	int OutputIndex(const int DataSetID, const bool bStageKillsParticles, const bool bIsValid)
	{
#line 698 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
			return AcquireIndex(DataSetID, bIsValid);
	}
#line 702 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"
#line 1 "/Engine/Generated/NiagaraEmitterInstance.ush"




struct NiagaraRandInfo
{
	int Seed1;
	int Seed2;
	int Seed3;
};

struct NiagaraSpawnInfo
{
	int Count;
	float InterpStartDt;
	float IntervalDt;
	int SpawnGroup;
};

struct NiagaraID
{
	int Index;
	int AcquireTag;
};

cbuffer FNiagaraGlobalParameters
{
	float Engine_DeltaTime;
	float Engine_InverseDeltaTime;
	float Engine_Time;
	float Engine_RealTime;
}

cbuffer FNiagaraSystemParameters
{
}

cbuffer FNiagaraOwnerParameters
{
}

cbuffer FNiagaraEmitterParameters
{
}

cbuffer FNiagaraExternalParameters
{
	float Constants_SystemState_LoopDelay;
	float Constants_SystemState_LoopDuration;
	float Constants_Empty004_EmitterState_LoopDuration;
	float Constants_Empty004_EmitterState_LoopDelay;
	int Constants_Empty004_UniformRangedInt_Minimum;
	int Constants_Empty004_UniformRangedInt_Maximum;
	int Constants_Empty004_UniformRangedInt_RandomSeed;
	float Constants_Empty004_SpawnBurst_Instantaneous_SpawnTime;
	int Constants_Empty004_SpawnBurst_Instantaneous_SpawnGroup;
	float Constants_Empty004_SpawnBurst_Instantaneous_SpawnProbability;
	float Constants_Empty004_UniformRangedFloat001_Minimum;
	float Constants_Empty004_UniformRangedFloat001_Maximum;
	int Constants_Empty004_UniformRangedFloat001_RandomSeed;
	float Constants_Empty004_UniformRangedFloat002_Minimum;
	float Constants_Empty004_UniformRangedFloat002_Maximum;
	int Constants_Empty004_UniformRangedFloat002_RandomSeed;
	float3 Constants_Empty004_UniformRangedVector001_Minimum;
	float3 Constants_Empty004_UniformRangedVector001_Maximum;
	int Constants_Empty004_UniformRangedVector001_RandomSeed;
	float3 Constants_Empty004_RandomVector_ConstraintVector;
	int Constants_Empty004_RandomVector_RandomSeed;
	float3 Constants_Empty004_RandomVector001_ConstraintVector;
	int Constants_Empty004_RandomVector001_RandomSeed;
	float3 Constants_Empty004_UniformRangedVector_Minimum;
	float3 Constants_Empty004_UniformRangedVector_Maximum;
	int Constants_Empty004_UniformRangedVector_RandomSeed;
	float Constants_Grande_EmitterState_LoopDuration;
	float Constants_Grande_EmitterState_LoopDelay;
	int Constants_Grande_UniformRangedInt_Minimum;
	int Constants_Grande_UniformRangedInt_Maximum;
	int Constants_Grande_UniformRangedInt_RandomSeed;
	float Constants_Grande_SpawnBurst_Instantaneous_SpawnTime;
	int Constants_Grande_SpawnBurst_Instantaneous_SpawnGroup;
	float Constants_Grande_SpawnBurst_Instantaneous_SpawnProbability;
	float Constants_Grande_UniformRangedFloat001_Minimum;
	float Constants_Grande_UniformRangedFloat001_Maximum;
	int Constants_Grande_UniformRangedFloat001_RandomSeed;
	float Constants_Grande_UniformRangedFloat002_Minimum;
	float Constants_Grande_UniformRangedFloat002_Maximum;
	int Constants_Grande_UniformRangedFloat002_RandomSeed;
	float3 Constants_Grande_RandomVector_ConstraintVector;
	int Constants_Grande_RandomVector_RandomSeed;
	float3 Constants_Grande_RandomVector001_ConstraintVector;
	int Constants_Grande_RandomVector001_RandomSeed;
	float3 Constants_Grande_UniformRangedVector_Minimum;
	float3 Constants_Grande_UniformRangedVector_Maximum;
	int Constants_Grande_UniformRangedVector_RandomSeed;
	float Constants_Peque_EmitterState_LoopDuration;
	float Constants_Peque_EmitterState_LoopDelay;
	int Constants_Peque_UniformRangedInt_Minimum;
	int Constants_Peque_UniformRangedInt_Maximum;
	int Constants_Peque_UniformRangedInt_RandomSeed;
	float Constants_Peque_SpawnBurst_Instantaneous_SpawnTime;
	int Constants_Peque_SpawnBurst_Instantaneous_SpawnGroup;
	float Constants_Peque_SpawnBurst_Instantaneous_SpawnProbability;
	float Constants_Peque_UniformRangedFloat001_Minimum;
	float Constants_Peque_UniformRangedFloat001_Maximum;
	int Constants_Peque_UniformRangedFloat001_RandomSeed;
	float Constants_Peque_UniformRangedFloat002_Minimum;
	float Constants_Peque_UniformRangedFloat002_Maximum;
	int Constants_Peque_UniformRangedFloat002_RandomSeed;
	float3 Constants_Peque_RandomVector_ConstraintVector;
	int Constants_Peque_RandomVector_RandomSeed;
	float3 Constants_Peque_RandomVector001_ConstraintVector;
	int Constants_Peque_RandomVector001_RandomSeed;
	float3 Constants_Peque_UniformRangedVector_Minimum;
	float3 Constants_Peque_UniformRangedVector_Maximum;
	int Constants_Peque_UniformRangedVector_RandomSeed;
	int Emitter_RandomSeed;
}

struct FParamMap0_Vector2DFromFloat
{
	float Value;
};

struct FParamMap0_User_Empty004
{
	int RandomSeed;
};

struct FParamMap0_User
{
	FParamMap0_User_Empty004 Empty004;
};

struct FParamMap0_UniformRangedVector001
{
	bool FixedRandomSeed;
	float3 Maximum;
	float3 Minimum;
	bool OverrideRandomness;
	bool OverrideSeed;
	int RandomnessMode;
	int RandomSeed;
};

struct FParamMap0_UniformRangedVector
{
	bool FixedRandomSeed;
	float3 Maximum;
	float3 Minimum;
	bool OverrideRandomness;
	bool OverrideSeed;
	int RandomnessMode;
	int RandomSeed;
};

struct FParamMap0_UniformRangedInt
{
	bool FixedRandomSeed;
	int Maximum;
	int Minimum;
	bool OverrideRandomness;
	bool OverrideSeed;
	int RandomnessMode;
	int RandomSeed;
};

struct FParamMap0_UniformRangedFloat003
{
	bool FixedRandomSeed;
	float Maximum;
	float Minimum;
	bool OverrideRandomness;
	bool OverrideSeed;
	int RandomnessMode;
	int RandomSeed;
};

struct FParamMap0_UniformRangedFloat002
{
	bool FixedRandomSeed;
	float Maximum;
	float Minimum;
	bool OverrideRandomness;
	bool OverrideSeed;
	int RandomnessMode;
	int RandomSeed;
};

struct FParamMap0_UniformRangedFloat001
{
	bool FixedRandomSeed;
	float Maximum;
	float Minimum;
	bool OverrideRandomness;
	bool OverrideSeed;
	int RandomnessMode;
	int RandomSeed;
};

struct FParamMap0_UniformRangedFloat
{
	bool FixedRandomSeed;
	float Maximum;
	float Minimum;
	bool OverrideRandomness;
	bool OverrideSeed;
	int RandomnessMode;
	int RandomSeed;
};

struct FParamMap0_Transient
{
	float PhysicsDeltaTime;
	float PhysicsDrag;
	float3 PhysicsForce;
	int ScalabilityEmitterExecutionState;
	float ScalabilityEmitterSpawnCountScale;
	int ScalabilityExecutionState;
	bool SpawningbCanEverSpawn;
};

struct FParamMap0_SystemState
{
	float LoopDelay;
	float LoopDuration;
	bool RecalculateDurationEachLoop;
};

struct FParamMap0_System
{
	float Age;
	bool bCompleteOnInactive;
	float CurrentLoopDuration;
	int ExecutionState;
	int ExecutionStateSource;
	int LoopCount;
	float LoopedAge;
	float NormalizedLoopAge;
};

struct FParamMap0_SpawnBurst_Instantaneous
{
	float Age;
	int SpawnCount;
	int SpawnGroup;
	float SpawnProbability;
	float SpawnTime;
};

struct FParamMap0_SpawnBeam
{
	float SplinePositionErrorThreshold;
};

struct FParamMap0_SolveForcesAndVelocity
{
	float AccelerationLimit;
	float DeltaTime;
	float3 Force;
	float Mass;
	float3 Position;
	float3 PreviousVelocity;
	float SpeedLimit;
	float3 Velocity;
	bool WritetoIntrinsicProperties;
};

struct FParamMap0_ScaleBeamWidth
{
	float BeamWidthScale;
};

struct FParamMap0_RandomVector001
{
	bool ConstraintoAxis;
	float3 ConstraintVector;
	bool FixedRandomSeed;
	bool OverrideRandomness;
	bool OverrideSeed;
	int RandomnessMode;
	int RandomSeed;
	float VectorScale;
};

struct FParamMap0_RandomVector
{
	bool ConstraintoAxis;
	float3 ConstraintVector;
	bool FixedRandomSeed;
	bool OverrideRandomness;
	bool OverrideSeed;
	int RandomnessMode;
	int RandomSeed;
	float VectorScale;
};

struct FParamMap0_Peque_SpawnBurst_Instantaneous
{
	NiagaraSpawnInfo SpawnBurst;
};

struct FParamMap0_Peque_Scalability
{
	float DistanceFraction;
};

struct FParamMap0_Peque
{
	float Age;
	float3 BeamDirection;
	float3 BeamEnd;
	float3 BeamEndTangent;
	int BeamID;
	float3 BeamStart;
	float BeamStartEndLength;
	float3 BeamStartTangent;
	float3 BeamVector;
	float CurrentLoopDuration;
	int ExecutionState;
	int ExecutionStateSource;
	bool LocalSpace;
	int LoopCount;
	float LoopedAge;
	float NormalizedLoopAge;
	FParamMap0_Peque_Scalability Scalability;
	FParamMap0_Peque_SpawnBurst_Instantaneous SpawnBurst_Instantaneous;
	bool UseBeamTangents;
};

struct FParamMap0_ParticleState
{
	float DeltaTime;
	float Lifetime;
};

struct FParamMap0_Particles_Initial
{
	float RibbonWidth;
};

struct FParamMap0_Particles
{
	float Age;
	float3 BeamSplineBinormal;
	float3 BeamSplineNormal;
	float3 BeamSplineTangent;
	float4 Color;
	FParamMap0_Particles_Initial Initial;
	float JitterDelayTimer;
	float Lifetime;
	float Mass;
	float MaterialRandom;
	float NormalizedAge;
	float3 Position;
	float3 PreviousVelocity;
	NiagaraID RibbonID;
	float RibbonLinkOrder;
	float RibbonTwist;
	float RibbonWidth;
	float3 Scale;
	float SpriteRotation;
	float2 SpriteSize;
	int UniqueID;
	float3 Velocity;
};

struct FParamMap0_OUTPUT_VAR_SolveForcesAndVelocity
{
	float IncomingPhysicsDrag;
	float3 IncomingPhysicsForce;
	float3 Position;
	float3 Velocity;
};

struct FParamMap0_OUTPUT_VAR_ParticleState
{
	bool FirstFrame;
};

struct FParamMap0_OUTPUT_VAR
{
	FParamMap0_OUTPUT_VAR_ParticleState ParticleState;
	FParamMap0_OUTPUT_VAR_SolveForcesAndVelocity SolveForcesAndVelocity;
};

struct FParamMap0_Local_SystemState
{
	bool LoopCountIncreased;
};

struct FParamMap0_Local_SpawnBeam
{
	float3 BeamDirection;
	float3 BeamVector;
	float NormalizedExecIndex;
	float StartEndVecLength;
};

struct FParamMap0_Local_SolveForcesAndVelocity
{
	float DeltaTime;
	float Mass;
	float3 PhysicsForce;
};

struct FParamMap0_Local_JitterPosition
{
	float3 ModuleJitterOffset;
};

struct FParamMap0_Local_EmitterState
{
	bool LoopCountIncreased;
	float LoopDuration;
	bool NoActiveEmitterParticles;
	int PreviousEmitterState;
};

struct FParamMap0_Local_CurlNoiseForce
{
	float AgeAdvancement;
	float DeterministicOffset;
	float Falloff;
	float3 SampledNoise;
	float3 SamplePosition;
};

struct FParamMap0_Local_BeamEmitterSetup
{
	float3 BeamEnd;
	float3 BeamEndTangent;
	float3 BeamStart;
	float BeamStartEndLength;
	float3 BeamStartTangent;
};

struct FParamMap0_Local
{
	FParamMap0_Local_BeamEmitterSetup BeamEmitterSetup;
	FParamMap0_Local_CurlNoiseForce CurlNoiseForce;
	FParamMap0_Local_EmitterState EmitterState;
	FParamMap0_Local_JitterPosition JitterPosition;
	FParamMap0_Local_SolveForcesAndVelocity SolveForcesAndVelocity;
	FParamMap0_Local_SpawnBeam SpawnBeam;
	FParamMap0_Local_SystemState SystemState;
};

struct FParamMap0_JitterPosition
{
	float JitterAmount;
	float JitterDelay;
	float3 JitterOffset;
};

struct FParamMap0_InitializeParticle
{
	float4 Color;
	float Lifetime;
	float Mass;
	float MaterialRandom;
	float3 MeshScale;
	float3 Position;
	float SpriteRotation;
	float2 SpriteSize;
	bool WriteColor;
	bool WriteLifetime;
	bool WriteMass;
	bool WriteMaterialRandom;
	bool WritePosition;
	bool WriteScale;
	bool WriteSpriteRotation;
	bool WriteSpriteSize;
};

struct FParamMap0_Grande_SpawnBurst_Instantaneous
{
	NiagaraSpawnInfo SpawnBurst;
};

struct FParamMap0_Grande_Scalability
{
	float DistanceFraction;
};

struct FParamMap0_Grande
{
	float Age;
	float3 BeamDirection;
	float3 BeamEnd;
	float3 BeamEndTangent;
	int BeamID;
	float3 BeamStart;
	float BeamStartEndLength;
	float3 BeamStartTangent;
	float3 BeamVector;
	float CurrentLoopDuration;
	int ExecutionState;
	int ExecutionStateSource;
	bool LocalSpace;
	int LoopCount;
	float LoopedAge;
	float NormalizedLoopAge;
	FParamMap0_Grande_Scalability Scalability;
	FParamMap0_Grande_SpawnBurst_Instantaneous SpawnBurst_Instantaneous;
	bool UseBeamTangents;
};

struct FParamMap0_FloatFromCurve
{
	float CurveIndex;
	float ScaleCurve;
};

struct FParamMap0_Engine_System
{
	int TickCount;
};

struct FParamMap0_Engine_Peque
{
	int NumParticles;
	float SpawnCountScale;
};

struct FParamMap0_Engine_Owner
{
	int ExecutionState;
	float LODDistanceFraction;
	float3 Position;
	float4x4 SystemLocalToWorld;
	float4x4 SystemLocalToWorldNoScale;
	float4x4 SystemWorldToLocal;
	float4x4 SystemWorldToLocalNoScale;
};

struct FParamMap0_Engine_Grande
{
	int NumParticles;
	float SpawnCountScale;
};

struct FParamMap0_Engine_Empty004
{
	int NumParticles;
	float SpawnCountScale;
};

struct FParamMap0_Engine_Emitter
{
	int TotalSpawnedParticles;
};

struct FParamMap0_Engine
{
	float DeltaTime;
	FParamMap0_Engine_Emitter Emitter;
	FParamMap0_Engine_Empty004 Empty004;
	int ExecutionCount;
	FParamMap0_Engine_Grande Grande;
	float InverseDeltaTime;
	FParamMap0_Engine_Owner Owner;
	FParamMap0_Engine_Peque Peque;
	float RealTime;
	FParamMap0_Engine_System System;
	float Time;
};

struct FParamMap0_Empty004_SpawnBurst_Instantaneous
{
	NiagaraSpawnInfo SpawnBurst;
};

struct FParamMap0_Empty004_Scalability
{
	float DistanceFraction;
};

struct FParamMap0_Empty004
{
	float Age;
	float3 BeamDirection;
	float3 BeamEnd;
	float3 BeamEndTangent;
	int BeamID;
	float3 BeamStart;
	float BeamStartEndLength;
	float3 BeamStartTangent;
	float3 BeamVector;
	float CurrentLoopDuration;
	int ExecutionState;
	int ExecutionStateSource;
	bool LocalSpace;
	int LoopCount;
	float LoopedAge;
	float NormalizedLoopAge;
	FParamMap0_Empty004_Scalability Scalability;
	FParamMap0_Empty004_SpawnBurst_Instantaneous SpawnBurst_Instantaneous;
	bool UseBeamTangents;
};

struct FParamMap0_EmitterState
{
	float LoopDelay;
	float LoopDuration;
	bool RecalculateDurationEachLoop;
};

struct FParamMap0_Emitter
{
	int RandomSeed;
};

struct FParamMap0_DataInstance
{
	bool Alive;
};

struct FParamMap0_CurlNoiseForce
{
	float CurlNoiseConeMaskAngle;
	float3 CurlNoiseConeMaskAxis;
	float CurlNoiseConeMaskFalloffAngle;
	float NoiseFrequency;
	float NoiseStrength;
	float3 PanNoiseField;
	int RandomSeed;
	float3 SamplePosition;
};

struct FParamMap0_Constants_SystemState
{
	float LoopDelay;
	float LoopDuration;
};

struct FParamMap0_Constants_Peque_UniformRangedVector
{
	float3 Maximum;
	float3 Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Peque_UniformRangedInt
{
	int Maximum;
	int Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Peque_UniformRangedFloat002
{
	float Maximum;
	float Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Peque_UniformRangedFloat001
{
	float Maximum;
	float Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Peque_SpawnBurst_Instantaneous
{
	int SpawnGroup;
	float SpawnProbability;
	float SpawnTime;
};

struct FParamMap0_Constants_Peque_RandomVector001
{
	float3 ConstraintVector;
	int RandomSeed;
};

struct FParamMap0_Constants_Peque_RandomVector
{
	float3 ConstraintVector;
	int RandomSeed;
};

struct FParamMap0_Constants_Peque_EmitterState
{
	float LoopDelay;
	float LoopDuration;
};

struct FParamMap0_Constants_Peque
{
	FParamMap0_Constants_Peque_EmitterState EmitterState;
	FParamMap0_Constants_Peque_RandomVector RandomVector;
	FParamMap0_Constants_Peque_RandomVector001 RandomVector001;
	FParamMap0_Constants_Peque_SpawnBurst_Instantaneous SpawnBurst_Instantaneous;
	FParamMap0_Constants_Peque_UniformRangedFloat001 UniformRangedFloat001;
	FParamMap0_Constants_Peque_UniformRangedFloat002 UniformRangedFloat002;
	FParamMap0_Constants_Peque_UniformRangedInt UniformRangedInt;
	FParamMap0_Constants_Peque_UniformRangedVector UniformRangedVector;
};

struct FParamMap0_Constants_Grande_UniformRangedVector
{
	float3 Maximum;
	float3 Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Grande_UniformRangedInt
{
	int Maximum;
	int Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Grande_UniformRangedFloat002
{
	float Maximum;
	float Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Grande_UniformRangedFloat001
{
	float Maximum;
	float Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Grande_SpawnBurst_Instantaneous
{
	int SpawnGroup;
	float SpawnProbability;
	float SpawnTime;
};

struct FParamMap0_Constants_Grande_RandomVector001
{
	float3 ConstraintVector;
	int RandomSeed;
};

struct FParamMap0_Constants_Grande_RandomVector
{
	float3 ConstraintVector;
	int RandomSeed;
};

struct FParamMap0_Constants_Grande_EmitterState
{
	float LoopDelay;
	float LoopDuration;
};

struct FParamMap0_Constants_Grande
{
	FParamMap0_Constants_Grande_EmitterState EmitterState;
	FParamMap0_Constants_Grande_RandomVector RandomVector;
	FParamMap0_Constants_Grande_RandomVector001 RandomVector001;
	FParamMap0_Constants_Grande_SpawnBurst_Instantaneous SpawnBurst_Instantaneous;
	FParamMap0_Constants_Grande_UniformRangedFloat001 UniformRangedFloat001;
	FParamMap0_Constants_Grande_UniformRangedFloat002 UniformRangedFloat002;
	FParamMap0_Constants_Grande_UniformRangedInt UniformRangedInt;
	FParamMap0_Constants_Grande_UniformRangedVector UniformRangedVector;
};

struct FParamMap0_Constants_Empty004_UniformRangedVector001
{
	float3 Maximum;
	float3 Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Empty004_UniformRangedVector
{
	float3 Maximum;
	float3 Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Empty004_UniformRangedInt
{
	int Maximum;
	int Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Empty004_UniformRangedFloat002
{
	float Maximum;
	float Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Empty004_UniformRangedFloat001
{
	float Maximum;
	float Minimum;
	int RandomSeed;
};

struct FParamMap0_Constants_Empty004_SpawnBurst_Instantaneous
{
	int SpawnGroup;
	float SpawnProbability;
	float SpawnTime;
};

struct FParamMap0_Constants_Empty004_RandomVector001
{
	float3 ConstraintVector;
	int RandomSeed;
};

struct FParamMap0_Constants_Empty004_RandomVector
{
	float3 ConstraintVector;
	int RandomSeed;
};

struct FParamMap0_Constants_Empty004_EmitterState
{
	float LoopDelay;
	float LoopDuration;
};

struct FParamMap0_Constants_Empty004
{
	FParamMap0_Constants_Empty004_EmitterState EmitterState;
	FParamMap0_Constants_Empty004_RandomVector RandomVector;
	FParamMap0_Constants_Empty004_RandomVector001 RandomVector001;
	FParamMap0_Constants_Empty004_SpawnBurst_Instantaneous SpawnBurst_Instantaneous;
	FParamMap0_Constants_Empty004_UniformRangedFloat001 UniformRangedFloat001;
	FParamMap0_Constants_Empty004_UniformRangedFloat002 UniformRangedFloat002;
	FParamMap0_Constants_Empty004_UniformRangedInt UniformRangedInt;
	FParamMap0_Constants_Empty004_UniformRangedVector UniformRangedVector;
	FParamMap0_Constants_Empty004_UniformRangedVector001 UniformRangedVector001;
};

struct FParamMap0_Constants
{
	FParamMap0_Constants_Empty004 Empty004;
	FParamMap0_Constants_Grande Grande;
	FParamMap0_Constants_Peque Peque;
	FParamMap0_Constants_SystemState SystemState;
};

struct FParamMap0_BeamWidth
{
	float BeamTwistAmount;
	float BeamWidth;
};

struct FParamMap0_BeamEmitterSetup
{
	bool AbsoluteEndTangent;
	bool AbsoluteStartTangent;
	float3 BeamEnd;
	float3 BeamEndTangent;
	float3 BeamStart;
	float3 BeamStartTangent;
	bool UseBeamTangents;
};

struct FParamMap0
{
	FParamMap0_BeamEmitterSetup BeamEmitterSetup;
	FParamMap0_BeamWidth BeamWidth;
	FParamMap0_Constants Constants;
	FParamMap0_CurlNoiseForce CurlNoiseForce;
	FParamMap0_DataInstance DataInstance;
	FParamMap0_Emitter Emitter;
	FParamMap0_EmitterState EmitterState;
	FParamMap0_Empty004 Empty004;
	FParamMap0_Engine Engine;
	FParamMap0_FloatFromCurve FloatFromCurve;
	FParamMap0_Grande Grande;
	FParamMap0_InitializeParticle InitializeParticle;
	FParamMap0_JitterPosition JitterPosition;
	FParamMap0_Local Local;
	FParamMap0_OUTPUT_VAR OUTPUT_VAR;
	FParamMap0_Particles Particles;
	FParamMap0_ParticleState ParticleState;
	FParamMap0_Peque Peque;
	FParamMap0_RandomVector RandomVector;
	FParamMap0_RandomVector001 RandomVector001;
	FParamMap0_ScaleBeamWidth ScaleBeamWidth;
	FParamMap0_SolveForcesAndVelocity SolveForcesAndVelocity;
	FParamMap0_SpawnBeam SpawnBeam;
	FParamMap0_SpawnBurst_Instantaneous SpawnBurst_Instantaneous;
	FParamMap0_System System;
	FParamMap0_SystemState SystemState;
	FParamMap0_Transient Transient;
	FParamMap0_UniformRangedFloat UniformRangedFloat;
	FParamMap0_UniformRangedFloat001 UniformRangedFloat001;
	FParamMap0_UniformRangedFloat002 UniformRangedFloat002;
	FParamMap0_UniformRangedFloat003 UniformRangedFloat003;
	FParamMap0_UniformRangedInt UniformRangedInt;
	FParamMap0_UniformRangedVector UniformRangedVector;
	FParamMap0_UniformRangedVector001 UniformRangedVector001;
	FParamMap0_User User;
	FParamMap0_Vector2DFromFloat Vector2DFromFloat;
};

struct FSimulationContext
{
	FParamMap0 Map;
};

static float HackSpawnInterp = 1.0;
void SystemState_SystemChangeState002_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void SystemState_SystemChangeState_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void SystemState_SystemChangeState001_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void SystemState_Func_(inout FSimulationContext Context);
void EmitterState_EmitterChangeState002_Empty004_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void EmitterState_EmitterChangeState005_Empty004_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void EmitterState_EmitterChangeState003_Empty004_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void EmitterState_Empty004_Func_(inout FSimulationContext Context);
void GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_(int In_Seed, int In_Engine_System_TickCount, bool In_OverrideSeed, int In_Particles_UniqueID, int In_Emitter_RandomSeed, bool In_FixedOverrideSeed, int In_RandomnessMode, out NiagaraRandInfo Out_RandomInfo, out bool Out_UseDeterministicRandoms, inout FSimulationContext Context);
void RandomRangeInteger_Func_(int In_Min, int In_Max, int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, bool In_FixedOverrideSeed, out int Out_Result, inout FSimulationContext Context);
void UniformRangedInt_Empty004_Func_(out int Out_UniformRangedInt, inout FSimulationContext Context);
void SpawnBurst_Instantaneous_Empty004_Func_(inout FSimulationContext Context);
void RandomRangeFloat_Func_(float In_Min, float In_Max, int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, bool In_FixedOverrideSeed, out float Out_Result, inout FSimulationContext Context);
void UniformRangedFloat001_Empty004_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context);
void UniformRangedFloat002_Empty004_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context);
void RandomRangeFloat_Func_(float3 In_Min, float3 In_Max, int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, bool In_FixedOverrideSeed, out float3 Out_Result, inout FSimulationContext Context);
void UniformRangedVector001_Empty004_Func_(out float3 Out_UniformRangedVector, inout FSimulationContext Context);
void TransformBase_Func_(int In_SourceSpace, int In_DestinationSpace, float4x4 In_LocalToWorldTransform, float4x4 In_WorldToLocalTransform, bool In_bLocalSpace, out bool Out_bUseOriginal, out float4x4 Out_OutTransform, inout FSimulationContext Context);
void RandomVector_NF_TransformVector_Empty004_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context);
void RandomRangeFloat_Func_(float2 In_Min, float2 In_Max, int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, bool In_FixedOverrideSeed, out float2 Out_Result, inout FSimulationContext Context);
void RandomRangeFloat_Func_(float In_Min, float In_Max, int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, out float Out_Result, inout FSimulationContext Context);
void RandomUnitVector_Func_(int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, bool In_FixedOverrideSeed, out float3 Out_UnitVector3D, out float2 Out_UnitVector2D, inout FSimulationContext Context);
void RandomVector_Empty004_Func_(out float3 Out_RandomVector, inout FSimulationContext Context);
void RandomVector001_NF_TransformVector_Empty004_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context);
void RandomVector001_Empty004_Func_(out float3 Out_RandomVector, inout FSimulationContext Context);
void UniformRangedVector_Empty004_Func_(out float3 Out_UniformRangedVector, inout FSimulationContext Context);
void DirectionAndLengthSafe_Func_(float3 In_V, float3 In_Fallback, float In_Threshold, float In_FallbackLength, out float3 Out_Direction, out float Out_Length, out bool Out_BelowThreshold, inout FSimulationContext Context);
void BeamEmitterSetup_NF_TransformVector_Empty004_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context);
void BeamEmitterSetup_Empty004_Func_(inout FSimulationContext Context);
void Empty004_Func_(inout FSimulationContext Context);
void EmitterState_EmitterChangeState002_Grande_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void EmitterState_EmitterChangeState005_Grande_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void EmitterState_EmitterChangeState003_Grande_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void EmitterState_Grande_Func_(inout FSimulationContext Context);
void UniformRangedInt_Grande_Func_(out int Out_UniformRangedInt, inout FSimulationContext Context);
void SpawnBurst_Instantaneous_Grande_Func_(inout FSimulationContext Context);
void UniformRangedFloat001_Grande_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context);
void UniformRangedFloat002_Grande_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context);
void RandomVector_NF_TransformVector_Grande_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context);
void RandomVector_Grande_Func_(out float3 Out_RandomVector, inout FSimulationContext Context);
void RandomVector001_NF_TransformVector_Grande_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context);
void RandomVector001_Grande_Func_(out float3 Out_RandomVector, inout FSimulationContext Context);
void UniformRangedVector_Grande_Func_(out float3 Out_UniformRangedVector, inout FSimulationContext Context);
void BeamEmitterSetup_NF_TransformVector_Grande_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context);
void BeamEmitterSetup_Grande_Func_(inout FSimulationContext Context);
void Grande_Func_(inout FSimulationContext Context);
void EmitterState_EmitterChangeState002_Peque_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void EmitterState_EmitterChangeState005_Peque_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void EmitterState_EmitterChangeState003_Peque_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context);
void EmitterState_Peque_Func_(inout FSimulationContext Context);
void UniformRangedInt_Peque_Func_(out int Out_UniformRangedInt, inout FSimulationContext Context);
void SpawnBurst_Instantaneous_Peque_Func_(inout FSimulationContext Context);
void UniformRangedFloat001_Peque_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context);
void UniformRangedFloat002_Peque_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context);
void RandomVector_NF_TransformVector_Peque_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context);
void RandomVector_Peque_Func_(out float3 Out_RandomVector, inout FSimulationContext Context);
void RandomVector001_NF_TransformVector_Peque_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context);
void RandomVector001_Peque_Func_(out float3 Out_RandomVector, inout FSimulationContext Context);
void UniformRangedVector_Peque_Func_(out float3 Out_UniformRangedVector, inout FSimulationContext Context);
void BeamEmitterSetup_NF_TransformVector_Peque_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context);
void BeamEmitterSetup_Peque_Func_(inout FSimulationContext Context);
void Peque_Func_(inout FSimulationContext Context);
float GetSpawnInterpolation();
void SystemState_SystemChangeState002_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	bool Result11 = NiagaraAll(Context.Map.System.ExecutionStateSource <= In_NewStateSource);
	bool Result12 = In_Condition && Result11;
	int ENiagaraExecutionState_IfResult;
	int ENiagaraExecutionStateSource_IfResult;
	if(Result12)
	{
	ENiagaraExecutionState_IfResult = In_NewState;
	ENiagaraExecutionStateSource_IfResult = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult = Context.Map.System.ExecutionState;
	ENiagaraExecutionStateSource_IfResult = Context.Map.System.ExecutionStateSource;
	}
	Context.Map.System.ExecutionState = ENiagaraExecutionState_IfResult;
	Context.Map.System.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult;
}

void SystemState_SystemChangeState_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	bool Result13 = NiagaraAll(Context.Map.System.ExecutionStateSource <= In_NewStateSource);
	bool Result14 = In_Condition && Result13;
	int ENiagaraExecutionState_IfResult1;
	int ENiagaraExecutionStateSource_IfResult1;
	if(Result14)
	{
	ENiagaraExecutionState_IfResult1 = In_NewState;
	ENiagaraExecutionStateSource_IfResult1 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult1 = Context.Map.System.ExecutionState;
	ENiagaraExecutionStateSource_IfResult1 = Context.Map.System.ExecutionStateSource;
	}
	Context.Map.System.ExecutionState = ENiagaraExecutionState_IfResult1;
	Context.Map.System.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult1;
}

void SystemState_SystemChangeState001_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	bool Result16 = NiagaraAll(Context.Map.System.ExecutionStateSource <= In_NewStateSource);
	bool Result17 = In_Condition && Result16;
	int ENiagaraExecutionState_IfResult2;
	int ENiagaraExecutionStateSource_IfResult2;
	if(Result17)
	{
	ENiagaraExecutionState_IfResult2 = In_NewState;
	ENiagaraExecutionStateSource_IfResult2 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult2 = Context.Map.System.ExecutionState;
	ENiagaraExecutionStateSource_IfResult2 = Context.Map.System.ExecutionStateSource;
	}
	Context.Map.System.ExecutionState = ENiagaraExecutionState_IfResult2;
	Context.Map.System.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult2;
}

void SystemState_Func_(inout FSimulationContext Context)
{
	float Constant3 = 0;
	bool Result = NiagaraAll(Context.Map.System.Age == Constant3);
	float Constant4 = 0.016667;
	float Result1 = max(Context.Map.Constants.SystemState.LoopDuration, Constant4);
	float Duration_IfResult;
	if(Result)
	{
	Duration_IfResult = Result1;
	}
	else
	{
	Duration_IfResult = Context.Map.System.CurrentLoopDuration;
	}
	float Constant5 = 0;
	Context.Map.System.CurrentLoopDuration = Duration_IfResult;
	Context.Map.SystemState.LoopDelay = Constant5;
	float Result2 = Context.Map.System.Age + Context.Map.Engine.DeltaTime;
	float Result3 = Context.Map.Engine.DeltaTime + Context.Map.System.LoopedAge;
	float Result4 = Result3 / Context.Map.System.CurrentLoopDuration;
	int Count;
	Count = Result4;
	int Constant6 = 0;
	int Result5 = max(Count, Constant6);
	float Result6 = Result5 * Context.Map.System.CurrentLoopDuration;
	float Result7 = Result3 - Result6;
	int Constant7 = 0;
	bool Result8 = NiagaraAll(Result5 > Constant7);
	int Result9 = Result5 + Context.Map.System.LoopCount;
	Context.Map.System.Age = Result2;
	Context.Map.System.LoopedAge = Result7;
	Context.Map.Local.SystemState.LoopCountIncreased = Result8;
	Context.Map.System.LoopCount = Result9;
	float float_IfResult;
	if(Context.Map.SystemState.RecalculateDurationEachLoop)
	{
	float_IfResult = Context.Map.Constants.SystemState.LoopDuration;
	}
	else
	{
	float_IfResult = Context.Map.System.CurrentLoopDuration;
	}
	float CurrentLoopDuration_IfResult;
	float LoopedAge_IfResult;
	if(Context.Map.Local.SystemState.LoopCountIncreased)
	{
	CurrentLoopDuration_IfResult = float_IfResult;
	LoopedAge_IfResult = Context.Map.System.LoopedAge;
	}
	else
	{
	CurrentLoopDuration_IfResult = Context.Map.System.CurrentLoopDuration;
	LoopedAge_IfResult = Context.Map.System.LoopedAge;
	}
	Context.Map.System.CurrentLoopDuration = CurrentLoopDuration_IfResult;
	Context.Map.System.LoopedAge = LoopedAge_IfResult;
	float Result10 = Context.Map.System.LoopedAge / Context.Map.System.CurrentLoopDuration;
	Context.Map.System.NormalizedLoopAge = Result10;
	bool Constant8 = true;
	int Constant9 = 0;
	SystemState_SystemChangeState002_Func_(Context.Map.Transient.ScalabilityExecutionState, Constant8, Constant9, Context);
	int Constant10 = 3;
	bool Constant11 = false;
	int Constant12 = 3;
	SystemState_SystemChangeState_Func_(Constant10, Constant11, Constant12, Context);
	bool Constant13 = true;
	Context.Map.System.bCompleteOnInactive = Constant13;
	int Constant14 = 0;
	bool Result15 = NiagaraAll(Context.Map.Engine.Owner.ExecutionState != Constant14);
	int Constant15 = 2;
	SystemState_SystemChangeState001_Func_(Context.Map.Engine.Owner.ExecutionState, Result15, Constant15, Context);
}

void EmitterState_EmitterChangeState002_Empty004_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	int Constant27 = 3;
	bool Result32 = NiagaraAll(Context.Map.Empty004.ExecutionState != Constant27);
	int Constant28 = 4;
	bool Result33 = NiagaraAll(Context.Map.Empty004.ExecutionState != Constant28);
	bool Result34 = Result32 && Result33;
	bool Result35 = In_Condition && Result34;
	bool Result36 = NiagaraAll(Context.Map.Empty004.ExecutionStateSource <= In_NewStateSource);
	bool Result37 = Result35 && Result36;
	int ENiagaraExecutionState_IfResult3;
	int ENiagaraExecutionStateSource_IfResult3;
	if(Result37)
	{
	ENiagaraExecutionState_IfResult3 = In_NewState;
	ENiagaraExecutionStateSource_IfResult3 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult3 = Context.Map.Empty004.ExecutionState;
	ENiagaraExecutionStateSource_IfResult3 = Context.Map.Empty004.ExecutionStateSource;
	}
	Context.Map.Empty004.ExecutionState = ENiagaraExecutionState_IfResult3;
	Context.Map.Empty004.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult3;
}

void EmitterState_EmitterChangeState005_Empty004_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	int Constant33 = 3;
	bool Result41 = NiagaraAll(Context.Map.Empty004.ExecutionState != Constant33);
	int Constant34 = 4;
	bool Result42 = NiagaraAll(Context.Map.Empty004.ExecutionState != Constant34);
	bool Result43 = Result41 && Result42;
	bool Result44 = In_Condition && Result43;
	bool Result45 = NiagaraAll(Context.Map.Empty004.ExecutionStateSource <= In_NewStateSource);
	bool Result46 = Result44 && Result45;
	int ENiagaraExecutionState_IfResult4;
	int ENiagaraExecutionStateSource_IfResult4;
	if(Result46)
	{
	ENiagaraExecutionState_IfResult4 = In_NewState;
	ENiagaraExecutionStateSource_IfResult4 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult4 = Context.Map.Empty004.ExecutionState;
	ENiagaraExecutionStateSource_IfResult4 = Context.Map.Empty004.ExecutionStateSource;
	}
	Context.Map.Empty004.ExecutionState = ENiagaraExecutionState_IfResult4;
	Context.Map.Empty004.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult4;
}

void EmitterState_EmitterChangeState003_Empty004_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	int Constant39 = 3;
	bool Result51 = NiagaraAll(Context.Map.Empty004.ExecutionState != Constant39);
	int Constant40 = 4;
	bool Result52 = NiagaraAll(Context.Map.Empty004.ExecutionState != Constant40);
	bool Result53 = Result51 && Result52;
	bool Result54 = In_Condition && Result53;
	bool Result55 = NiagaraAll(Context.Map.Empty004.ExecutionStateSource <= In_NewStateSource);
	bool Result56 = Result54 && Result55;
	int ENiagaraExecutionState_IfResult5;
	int ENiagaraExecutionStateSource_IfResult5;
	if(Result56)
	{
	ENiagaraExecutionState_IfResult5 = In_NewState;
	ENiagaraExecutionStateSource_IfResult5 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult5 = Context.Map.Empty004.ExecutionState;
	ENiagaraExecutionStateSource_IfResult5 = Context.Map.Empty004.ExecutionStateSource;
	}
	Context.Map.Empty004.ExecutionState = ENiagaraExecutionState_IfResult5;
	Context.Map.Empty004.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult5;
}

void EmitterState_Empty004_Func_(inout FSimulationContext Context)
{
	Context.Map.Local.EmitterState.PreviousEmitterState = Context.Map.Empty004.ExecutionState;
	float Constant16 = 0.016667;
	float Result18 = max(Context.Map.Constants.Empty004.EmitterState.LoopDuration, Constant16);
	Context.Map.Local.EmitterState.LoopDuration = Result18;
	float Constant17 = 0;
	bool Result19 = NiagaraAll(Context.Map.Empty004.Age == Constant17);
	float Duration_IfResult1;
	if(Result19)
	{
	Duration_IfResult1 = Context.Map.Local.EmitterState.LoopDuration;
	}
	else
	{
	Duration_IfResult1 = Context.Map.Empty004.CurrentLoopDuration;
	}
	float Constant18 = 0;
	Context.Map.Empty004.CurrentLoopDuration = Duration_IfResult1;
	Context.Map.EmitterState.LoopDelay = Constant18;
	float Result20 = Context.Map.Empty004.Age + Context.Map.Engine.DeltaTime;
	float Result21 = Context.Map.Engine.DeltaTime + Context.Map.Empty004.LoopedAge;
	float Result22 = Result21 / Context.Map.Empty004.CurrentLoopDuration;
	int Count1;
	Count1 = Result22;
	int Constant19 = 0;
	int Result23 = max(Count1, Constant19);
	float Result24 = Result23 * Context.Map.Empty004.CurrentLoopDuration;
	float Result25 = Result21 - Result24;
	int Constant20 = 0;
	bool Result26 = NiagaraAll(Result23 > Constant20);
	int Result27 = Result23 + Context.Map.Empty004.LoopCount;
	Context.Map.Empty004.Age = Result20;
	Context.Map.Empty004.LoopedAge = Result25;
	Context.Map.Local.EmitterState.LoopCountIncreased = Result26;
	Context.Map.Empty004.LoopCount = Result27;
	bool Constant21 = false;
	Context.Map.EmitterState.RecalculateDurationEachLoop = Constant21;
	float float_IfResult1;
	if(Context.Map.EmitterState.RecalculateDurationEachLoop)
	{
	float_IfResult1 = Context.Map.Local.EmitterState.LoopDuration;
	}
	else
	{
	float_IfResult1 = Context.Map.Empty004.CurrentLoopDuration;
	}
	float CurrentLoopDuration_IfResult1;
	float LoopedAge_IfResult1;
	if(Context.Map.Local.EmitterState.LoopCountIncreased)
	{
	CurrentLoopDuration_IfResult1 = float_IfResult1;
	LoopedAge_IfResult1 = Context.Map.Empty004.LoopedAge;
	}
	else
	{
	CurrentLoopDuration_IfResult1 = Context.Map.Empty004.CurrentLoopDuration;
	LoopedAge_IfResult1 = Context.Map.Empty004.LoopedAge;
	}
	Context.Map.Empty004.CurrentLoopDuration = CurrentLoopDuration_IfResult1;
	Context.Map.Empty004.LoopedAge = LoopedAge_IfResult1;
	float Result28 = Context.Map.Empty004.LoopedAge / Context.Map.Empty004.CurrentLoopDuration;
	Context.Map.Empty004.NormalizedLoopAge = Result28;
	float Constant22 = 0;
	float Constant23 = 1.0001;
	float Result29 = clamp(Context.Map.Engine.Owner.LODDistanceFraction,Constant22,Constant23);
	Context.Map.Empty004.Scalability.DistanceFraction = Result29;
	int Constant24 = 0;
	Context.Map.Transient.ScalabilityEmitterExecutionState = Constant24;
	int Constant25 = 0;
	bool Result30 = NiagaraAll(Context.Map.Engine.Empty004.NumParticles == Constant25);
	Context.Map.Local.EmitterState.NoActiveEmitterParticles = Result30;
	int Constant26 = 0;
	bool Result31 = NiagaraAll(Context.Map.System.ExecutionStateSource == Constant26);
	EmitterState_EmitterChangeState002_Empty004_Func_(Context.Map.System.ExecutionState, Result31, Context.Map.System.ExecutionStateSource, Context);
	int Constant29 = 1;
	int Constant30 = 0;
	bool Result38 = NiagaraAll(Context.Map.System.ExecutionState != Constant30);
	int Constant31 = 2;
	bool Result39 = NiagaraAll(Context.Map.System.ExecutionStateSource == Constant31);
	bool Result40 = Result38 && Result39;
	int Constant32 = 1;
	EmitterState_EmitterChangeState005_Empty004_Func_(Constant29, Result40, Constant32, Context);
	int Constant35 = 3;
	int Constant36 = 0;
	bool Result47 = NiagaraAll(Context.Map.Empty004.ExecutionState != Constant36);
	int Constant37 = 0;
	bool Result48 = NiagaraAll(Context.Map.Empty004.ExecutionStateSource != Constant37);
	bool Result49 = Result47 && Result48;
	bool Result50 = Context.Map.Local.EmitterState.NoActiveEmitterParticles && Result49;
	int Constant38 = 3;
	EmitterState_EmitterChangeState003_Empty004_Func_(Constant35, Result50, Constant38, Context);
}

void GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_(int In_Seed, int In_Engine_System_TickCount, bool In_OverrideSeed, int In_Particles_UniqueID, int In_Emitter_RandomSeed, bool In_FixedOverrideSeed, int In_RandomnessMode, out NiagaraRandInfo Out_RandomInfo, out bool Out_UseDeterministicRandoms, inout FSimulationContext Context)
{
	bool Constant51 = false;
	int Constant52 = 0;
	bool Result57 = NiagaraAll(In_RandomnessMode == Constant52);
	bool Result58 = Constant51 && Result57;
	int Constant53 = 1;
	bool Result59 = NiagaraAll(In_RandomnessMode == Constant53);
	bool Result60 = Result58 || Result59;
	int Seed_IfResult;
	if(In_OverrideSeed)
	{
	Seed_IfResult = In_Seed;
	}
	else
	{
	Seed_IfResult = Context.Map.User.Empty004.RandomSeed;
	}
	int Constant54 = 0;
	int Constant55 = 0;
	int Constant56 = 0;
	int Seed1_IfResult;
	int Seed2_IfResult;
	int Seed3_IfResult;
	if(In_FixedOverrideSeed)
	{
	Seed1_IfResult = Seed_IfResult;
	Seed2_IfResult = Constant54;
	Seed3_IfResult = Constant55;
	}
	else
	{
	Seed1_IfResult = Constant56;
	Seed2_IfResult = Context.Map.Engine.System.TickCount;
	Seed3_IfResult = Seed_IfResult;
	}
	int Constant57 = -1;
	int Constant58 = -1;
	int Constant59 = -1;
	int Seed1_IfResult1;
	int Seed2_IfResult1;
	int Seed3_IfResult1;
	if(Result60)
	{
	Seed1_IfResult1 = Seed1_IfResult;
	Seed2_IfResult1 = Seed2_IfResult;
	Seed3_IfResult1 = Seed3_IfResult;
	}
	else
	{
	Seed1_IfResult1 = Constant57;
	Seed2_IfResult1 = Constant58;
	Seed3_IfResult1 = Constant59;
	}
	NiagaraRandInfo Output1;
	Output1.Seed1 = Seed1_IfResult1;
	Output1.Seed2 = Seed2_IfResult1;
	Output1.Seed3 = Seed3_IfResult1;
	Out_RandomInfo = Output1;
	Out_UseDeterministicRandoms = Result60;
}

void RandomRangeInteger_Func_(int In_Min, int In_Max, int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, bool In_FixedOverrideSeed, out int Out_Result, inout FSimulationContext Context)
{
	int Constant47 = (0);
	bool Constant48 = false;
	int Constant49 = 0;
	int Constant50 = (0);
	NiagaraRandInfo GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo;
	bool GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms;
	GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_(In_Seed, Constant47, In_OverrideSeed, Constant49, Constant50, In_FixedOverrideSeed, In_RandomnessMode, GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo, GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms, Context);
	int Result61 = In_Max - In_Min;
	int Constant60 = 1;
	int Result62 = Result61 + Constant60;
	int Seed1;
	int Seed2;
	int Seed3;
	Seed1 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo.Seed1;
	Seed2 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo.Seed2;
	Seed3 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo.Seed3;
	int Result63 = rand_int(Result62, Seed1, Seed2, Seed3);
	int Result64 = rand_int(Result62);
	int Random_IfResult;
	if(GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms)
	{
	Random_IfResult = Result63;
	}
	else
	{
	Random_IfResult = Result64;
	}
	int Result65 = In_Min + Random_IfResult;
	Out_Result = Result65;
}

void UniformRangedInt_Empty004_Func_(out int Out_UniformRangedInt, inout FSimulationContext Context)
{
	bool Constant41 = false;
	Context.Map.UniformRangedInt.OverrideRandomness = Constant41;
	int Constant42 = 0;
	Context.Map.UniformRangedInt.RandomnessMode = Constant42;
	bool Constant43 = false;
	Context.Map.UniformRangedInt.OverrideSeed = Constant43;
	bool Constant44 = false;
	Context.Map.UniformRangedInt.FixedRandomSeed = Constant44;
	int Constant45 = 0;
	bool Constant46 = false;
	int Mode_IfResult;
	bool Override_IfResult;
	if(Context.Map.UniformRangedInt.OverrideRandomness)
	{
	Mode_IfResult = Context.Map.UniformRangedInt.RandomnessMode;
	Override_IfResult = Context.Map.UniformRangedInt.OverrideSeed;
	}
	else
	{
	Mode_IfResult = Constant45;
	Override_IfResult = Constant46;
	}
	int RandomRangeInteger_Func_Output_Result;
	RandomRangeInteger_Func_(Context.Map.Constants.Empty004.UniformRangedInt.Minimum, Context.Map.Constants.Empty004.UniformRangedInt.Maximum, Context.Map.Constants.Empty004.UniformRangedInt.RandomSeed, Mode_IfResult, Override_IfResult, Context.Map.UniformRangedInt.FixedRandomSeed, RandomRangeInteger_Func_Output_Result, Context);
	Out_UniformRangedInt = RandomRangeInteger_Func_Output_Result;
}

void SpawnBurst_Instantaneous_Empty004_Func_(inout FSimulationContext Context)
{
	Context.Map.SpawnBurst_Instantaneous.Age = Context.Map.Empty004.LoopedAge;
	float Result66 = Context.Map.SpawnBurst_Instantaneous.Age - Context.Map.Engine.DeltaTime;
	float Result67 = Context.Map.Constants.Empty004.SpawnBurst_Instantaneous.SpawnTime - Result66;
	float Constant61 = 0;
	float Output11;
	Output11 = Constant61;
	bool Result68 = NiagaraAll(Result67 >= Output11);
	float Result69 = Context.Map.Constants.Empty004.SpawnBurst_Instantaneous.SpawnTime - Context.Map.SpawnBurst_Instantaneous.Age;
	bool Result70 = NiagaraAll(Result69 < Output11);
	bool Result71 = Result68 && Result70;
	float Constant62 = 1;
	Context.Map.Transient.ScalabilityEmitterSpawnCountScale = Constant62;
	int Constant63 = 0;
	bool Result72 = NiagaraAll(Context.Map.SpawnBurst_Instantaneous.SpawnCount == Constant63);
	float Constant64 = 0;
	float Result73 = Context.Map.SpawnBurst_Instantaneous.SpawnCount * Context.Map.Transient.ScalabilityEmitterSpawnCountScale * Context.Map.Engine.Empty004.SpawnCountScale;
	float Constant65 = 1;
	float Result74 = max(Result73, Constant65);
	float float_IfResult2;
	if(Result72)
	{
	float_IfResult2 = Constant64;
	}
	else
	{
	float_IfResult2 = Result74;
	}
	float Constant66 = 0;
	NiagaraSpawnInfo Output12;
	Output12.Count = float_IfResult2;
	Output12.InterpStartDt = Result67;
	Output12.IntervalDt = Constant66;
	Output12.SpawnGroup = Context.Map.Constants.Empty004.SpawnBurst_Instantaneous.SpawnGroup;
	int Constant67 = 0;
	float Constant68 = 0;
	float Constant69 = 0;
	NiagaraSpawnInfo Output13;
	Output13.Count = Constant67;
	Output13.InterpStartDt = Constant68;
	Output13.SpawnGroup = Context.Map.Constants.Empty004.SpawnBurst_Instantaneous.SpawnGroup;
	Output13.IntervalDt = Constant69;
	NiagaraSpawnInfo SpawnInfo_IfResult;
	if(Result71)
	{
	SpawnInfo_IfResult = Output12;
	}
	else
	{
	SpawnInfo_IfResult = Output13;
	}
	Context.Map.Empty004.SpawnBurst_Instantaneous.SpawnBurst = SpawnInfo_IfResult;
	bool Constant70 = false;
	Context.Map.Transient.SpawningbCanEverSpawn = Constant70;
	bool Result75 = NiagaraAll(Context.Map.Empty004.LoopedAge <= Context.Map.Constants.Empty004.SpawnBurst_Instantaneous.SpawnTime);
	bool Result76 = Context.Map.Transient.SpawningbCanEverSpawn || Result75;
	Context.Map.Transient.SpawningbCanEverSpawn = Result76;
}

void RandomRangeFloat_Func_(float In_Min, float In_Max, int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, bool In_FixedOverrideSeed, out float Out_Result, inout FSimulationContext Context)
{
	int Constant77 = (0);
	bool Constant78 = false;
	int Constant79 = 0;
	int Constant80 = (0);
	NiagaraRandInfo GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo1;
	bool GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms1;
	GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_(In_Seed, Constant77, In_OverrideSeed, Constant79, Constant80, In_FixedOverrideSeed, In_RandomnessMode, GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo1, GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms1, Context);
	float Result77 = In_Max - In_Min;
	int Seed11;
	int Seed21;
	int Seed31;
	Seed11 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo1.Seed1;
	Seed21 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo1.Seed2;
	Seed31 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo1.Seed3;
	float Result78 = rand_float(Result77, Seed11, Seed21, Seed31);
	float Result79 = rand_float(Result77);
	float Random_IfResult1;
	if(GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms1)
	{
	Random_IfResult1 = Result78;
	}
	else
	{
	Random_IfResult1 = Result79;
	}
	float Result80 = In_Min + Random_IfResult1;
	Out_Result = Result80;
}

void UniformRangedFloat001_Empty004_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context)
{
	bool Constant71 = false;
	Context.Map.UniformRangedFloat001.OverrideRandomness = Constant71;
	int Constant72 = 0;
	Context.Map.UniformRangedFloat001.RandomnessMode = Constant72;
	bool Constant73 = false;
	Context.Map.UniformRangedFloat001.OverrideSeed = Constant73;
	bool Constant74 = false;
	Context.Map.UniformRangedFloat001.FixedRandomSeed = Constant74;
	int Constant75 = 0;
	bool Constant76 = false;
	int Mode_IfResult1;
	bool Override_IfResult1;
	if(Context.Map.UniformRangedFloat001.OverrideRandomness)
	{
	Mode_IfResult1 = Context.Map.UniformRangedFloat001.RandomnessMode;
	Override_IfResult1 = Context.Map.UniformRangedFloat001.OverrideSeed;
	}
	else
	{
	Mode_IfResult1 = Constant75;
	Override_IfResult1 = Constant76;
	}
	float RandomRangeFloat_Func_Output_Result;
	RandomRangeFloat_Func_(Context.Map.Constants.Empty004.UniformRangedFloat001.Minimum, Context.Map.Constants.Empty004.UniformRangedFloat001.Maximum, Context.Map.Constants.Empty004.UniformRangedFloat001.RandomSeed, Mode_IfResult1, Override_IfResult1, Context.Map.UniformRangedFloat001.FixedRandomSeed, RandomRangeFloat_Func_Output_Result, Context);
	Out_UniformRangedFloat = RandomRangeFloat_Func_Output_Result;
}

void UniformRangedFloat002_Empty004_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context)
{
	bool Constant81 = false;
	Context.Map.UniformRangedFloat002.OverrideRandomness = Constant81;
	int Constant82 = 0;
	Context.Map.UniformRangedFloat002.RandomnessMode = Constant82;
	bool Constant83 = false;
	Context.Map.UniformRangedFloat002.OverrideSeed = Constant83;
	bool Constant84 = false;
	Context.Map.UniformRangedFloat002.FixedRandomSeed = Constant84;
	int Constant85 = 0;
	bool Constant86 = false;
	int Mode_IfResult2;
	bool Override_IfResult2;
	if(Context.Map.UniformRangedFloat002.OverrideRandomness)
	{
	Mode_IfResult2 = Context.Map.UniformRangedFloat002.RandomnessMode;
	Override_IfResult2 = Context.Map.UniformRangedFloat002.OverrideSeed;
	}
	else
	{
	Mode_IfResult2 = Constant85;
	Override_IfResult2 = Constant86;
	}
	float RandomRangeFloat_Func_Output_Result1;
	RandomRangeFloat_Func_(Context.Map.Constants.Empty004.UniformRangedFloat002.Minimum, Context.Map.Constants.Empty004.UniformRangedFloat002.Maximum, Context.Map.Constants.Empty004.UniformRangedFloat002.RandomSeed, Mode_IfResult2, Override_IfResult2, Context.Map.UniformRangedFloat002.FixedRandomSeed, RandomRangeFloat_Func_Output_Result1, Context);
	Out_UniformRangedFloat = RandomRangeFloat_Func_Output_Result1;
}

void RandomRangeFloat_Func_(float3 In_Min, float3 In_Max, int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, bool In_FixedOverrideSeed, out float3 Out_Result, inout FSimulationContext Context)
{
	int Constant93 = (0);
	bool Constant94 = false;
	int Constant95 = 0;
	int Constant96 = (0);
	NiagaraRandInfo GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo2;
	bool GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms2;
	GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_(In_Seed, Constant93, In_OverrideSeed, Constant95, Constant96, In_FixedOverrideSeed, In_RandomnessMode, GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo2, GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms2, Context);
	float3 Result81 = In_Max - In_Min;
	int Seed12;
	int Seed22;
	int Seed32;
	Seed12 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo2.Seed1;
	Seed22 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo2.Seed2;
	Seed32 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo2.Seed3;
	float3 Result82 = rand_float(Result81, Seed12, Seed22, Seed32);
	float3 Result83 = rand_float(Result81);
	float3 Random_IfResult2;
	if(GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms2)
	{
	Random_IfResult2 = Result82;
	}
	else
	{
	Random_IfResult2 = Result83;
	}
	float3 Result84 = In_Min + Random_IfResult2;
	Out_Result = Result84;
}

void UniformRangedVector001_Empty004_Func_(out float3 Out_UniformRangedVector, inout FSimulationContext Context)
{
	bool Constant87 = false;
	Context.Map.UniformRangedVector001.OverrideRandomness = Constant87;
	int Constant88 = 0;
	Context.Map.UniformRangedVector001.RandomnessMode = Constant88;
	bool Constant89 = false;
	Context.Map.UniformRangedVector001.OverrideSeed = Constant89;
	bool Constant90 = false;
	Context.Map.UniformRangedVector001.FixedRandomSeed = Constant90;
	int Constant91 = 0;
	bool Constant92 = false;
	int Mode_IfResult3;
	bool Override_IfResult3;
	if(Context.Map.UniformRangedVector001.OverrideRandomness)
	{
	Mode_IfResult3 = Context.Map.UniformRangedVector001.RandomnessMode;
	Override_IfResult3 = Context.Map.UniformRangedVector001.OverrideSeed;
	}
	else
	{
	Mode_IfResult3 = Constant91;
	Override_IfResult3 = Constant92;
	}
	float3 RandomRangeFloat_Func_Output_Result2;
	RandomRangeFloat_Func_(Context.Map.Constants.Empty004.UniformRangedVector001.Minimum, Context.Map.Constants.Empty004.UniformRangedVector001.Maximum, Context.Map.Constants.Empty004.UniformRangedVector001.RandomSeed, Mode_IfResult3, Override_IfResult3, Context.Map.UniformRangedVector001.FixedRandomSeed, RandomRangeFloat_Func_Output_Result2, Context);
	Out_UniformRangedVector = RandomRangeFloat_Func_Output_Result2;
}

void TransformBase_Func_(int In_SourceSpace, int In_DestinationSpace, float4x4 In_LocalToWorldTransform, float4x4 In_WorldToLocalTransform, bool In_bLocalSpace, out bool Out_bUseOriginal, out float4x4 Out_OutTransform, inout FSimulationContext Context)
{
	int Constant103 = 0;
	bool Result85 = NiagaraAll(In_SourceSpace == Constant103);
	int Constant104 = 0;
	bool Result86 = NiagaraAll(In_DestinationSpace == Constant104);
	bool Result87 = Result85 && Result86;
	int Constant105 = 1;
	bool Result88 = NiagaraAll(In_SourceSpace == Constant105);
	int Constant106 = 1;
	bool Result89 = NiagaraAll(In_DestinationSpace == Constant106);
	bool Result90 = Result88 && Result89;
	bool Result91 = Result87 || Result90;
	int Constant107 = 2;
	bool Result92 = NiagaraAll(In_SourceSpace == Constant107);
	int Constant108 = 2;
	bool Result93 = NiagaraAll(In_DestinationSpace == Constant108);
	bool Result94 = Result92 && Result93;
	bool Result95 = Result91 || Result94;
	bool Result96 = Result85 && Result93;
	bool Result97 = Result92 && Result86;
	bool Result98 = Result96 || Result97;
	bool Result99 = In_bLocalSpace && Result98;
	bool Result100 = Result95 || Result99;
	bool Result101 = !In_bLocalSpace;
	bool Result102 = Result85 && Result89;
	bool Result103 = Result88 && Result86;
	bool Result104 = Result102 || Result103;
	bool Result105 = Result101 && Result104;
	bool Result106 = Result100 || Result105;
	bool Result107 = In_bLocalSpace && Result102;
	bool Result108 = Result92 && Result89;
	bool Result109 = Result107 || Result108;
	bool Result110 = Result101 && Result97;
	bool Result111 = Result109 || Result110;
	float4x4 Matrix_IfResult1;
	if(Result111)
	{
	Matrix_IfResult1 = In_LocalToWorldTransform;
	}
	else
	{
	Matrix_IfResult1 = In_WorldToLocalTransform;
	}
	Out_bUseOriginal = Result106;
	Out_OutTransform = Matrix_IfResult1;
}

void RandomVector_NF_TransformVector_Empty004_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context)
{
	bool Constant102 = true;
	float4x4 Matrix_IfResult;
	float4x4 Matrix001_IfResult;
	if(In_ApplyScale)
	{
	Matrix_IfResult = Context.Map.Engine.Owner.SystemLocalToWorld;
	Matrix001_IfResult = Context.Map.Engine.Owner.SystemWorldToLocal;
	}
	else
	{
	Matrix_IfResult = Context.Map.Engine.Owner.SystemLocalToWorldNoScale;
	Matrix001_IfResult = Context.Map.Engine.Owner.SystemWorldToLocalNoScale;
	}
	bool TransformBase_Func_Output_bUseOriginal;
	float4x4 TransformBase_Func_Output_OutTransform;
	TransformBase_Func_(In_SourceSpace, In_DestinationSpace, Matrix_IfResult, Matrix001_IfResult, Constant102, TransformBase_Func_Output_bUseOriginal, TransformBase_Func_Output_OutTransform, Context);
	float3 Result112 = mul(float4(In_InVector,0.0),TransformBase_Func_Output_OutTransform).xyz;
	float3 Vector_IfResult;
	if(TransformBase_Func_Output_bUseOriginal)
	{
	Vector_IfResult = In_InVector;
	}
	else
	{
	Vector_IfResult = Result112;
	}
	Out_OutVector = Vector_IfResult;
}

void RandomRangeFloat_Func_(float2 In_Min, float2 In_Max, int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, bool In_FixedOverrideSeed, out float2 Out_Result, inout FSimulationContext Context)
{
	int Constant117 = (0);
	bool Constant118 = false;
	int Constant119 = 0;
	int Constant120 = (0);
	NiagaraRandInfo GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo3;
	bool GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms3;
	GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_(In_Seed, Constant117, In_OverrideSeed, Constant119, Constant120, In_FixedOverrideSeed, In_RandomnessMode, GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo3, GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms3, Context);
	float2 Result113 = In_Max - In_Min;
	int Seed13;
	int Seed23;
	int Seed33;
	Seed13 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo3.Seed1;
	Seed23 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo3.Seed2;
	Seed33 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo3.Seed3;
	float2 Result114 = rand_float(Result113, Seed13, Seed23, Seed33);
	float2 Result115 = rand_float(Result113);
	float2 Random_IfResult3;
	if(GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms3)
	{
	Random_IfResult3 = Result114;
	}
	else
	{
	Random_IfResult3 = Result115;
	}
	float2 Result116 = In_Min + Random_IfResult3;
	Out_Result = Result116;
}

void RandomRangeFloat_Func_(float In_Min, float In_Max, int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, out float Out_Result, inout FSimulationContext Context)
{
	int Constant126 = (0);
	bool Constant127 = false;
	int Constant128 = 0;
	int Constant129 = (0);
	bool Constant130 = false;
	NiagaraRandInfo GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo4;
	bool GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms4;
	GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_(In_Seed, Constant126, In_OverrideSeed, Constant128, Constant129, Constant130, In_RandomnessMode, GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo4, GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms4, Context);
	float Result124 = In_Max - In_Min;
	int Seed14;
	int Seed24;
	int Seed34;
	Seed14 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo4.Seed1;
	Seed24 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo4.Seed2;
	Seed34 = GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_RandomInfo4.Seed3;
	float Result125 = rand_float(Result124, Seed14, Seed24, Seed34);
	float Result126 = rand_float(Result124);
	float Random_IfResult4;
	if(GetRandomInfo_Emitter_Determinism_false_Emitter_Emitter_Emitter_Func_Output_UseDeterministicRandoms4)
	{
	Random_IfResult4 = Result125;
	}
	else
	{
	Random_IfResult4 = Result126;
	}
	float Result127 = In_Min + Random_IfResult4;
	Out_Result = Result127;
}

void RandomUnitVector_Func_(int In_Seed, int In_RandomnessMode, bool In_OverrideSeed, bool In_FixedOverrideSeed, out float3 Out_UnitVector3D, out float2 Out_UnitVector2D, inout FSimulationContext Context)
{
	float2 Constant115 = float2(0,-1);
	float2 Constant116 = float2(6.28319,1);
	float2 RandomRangeFloat_Func_Output_Result3;
	RandomRangeFloat_Func_(Constant115, Constant116, In_Seed, In_RandomnessMode, In_OverrideSeed, In_FixedOverrideSeed, RandomRangeFloat_Func_Output_Result3, Context);
	float Phi;
	float CosASC40ThetaASC41;
	Phi = RandomRangeFloat_Func_Output_Result3.x;
	CosASC40ThetaASC41 = RandomRangeFloat_Func_Output_Result3.y;
	float Result117 = cos(Phi);
	float Result118 = CosASC40ThetaASC41 * CosASC40ThetaASC41;
	float Result119 = 1 - Result118;
	float Result120 = sqrt(Result119);
	float Result121 = Result117 * Result120;
	float Result122 = sin(Phi);
	float Result123 = Result122 * Result120;
	float3 PositionOnSphere;
	PositionOnSphere.x = Result121;
	PositionOnSphere.y = Result123;
	PositionOnSphere.z = CosASC40ThetaASC41;
	float Constant121 = 0;
	float Constant122 = 6.28319;
	int Constant123 = -1;
	int Constant124 = 0;
	bool Constant125 = false;
	float RandomRangeFloat_Func_Output_Result4;
	RandomRangeFloat_Func_(Constant121, Constant122, Constant123, Constant124, Constant125, RandomRangeFloat_Func_Output_Result4, Context);
	float Result128 = cos(RandomRangeFloat_Func_Output_Result4);
	float Result129 = sin(RandomRangeFloat_Func_Output_Result4);
	float2 PositionOnCircle;
	PositionOnCircle.x = Result128;
	PositionOnCircle.y = Result129;
	Out_UnitVector3D = PositionOnSphere;
	Out_UnitVector2D = PositionOnCircle;
}

void RandomVector_Empty004_Func_(out float3 Out_RandomVector, inout FSimulationContext Context)
{
	bool Constant98 = false;
	Context.Map.RandomVector.ConstraintoAxis = Constant98;
	int Constant99 = 2;
	int Constant100 = 0;
	bool Constant101 = false;
	float3 RandomVector_NF_TransformVector_Empty004_Func_Output_OutVector;
	RandomVector_NF_TransformVector_Empty004_Func_(Context.Map.Constants.Empty004.RandomVector.ConstraintVector, Constant99, Constant100, Constant101, RandomVector_NF_TransformVector_Empty004_Func_Output_OutVector, Context);
	bool Constant109 = false;
	Context.Map.RandomVector.OverrideRandomness = Constant109;
	int Constant110 = 0;
	Context.Map.RandomVector.RandomnessMode = Constant110;
	bool Constant111 = false;
	Context.Map.RandomVector.OverrideSeed = Constant111;
	bool Constant112 = false;
	Context.Map.RandomVector.FixedRandomSeed = Constant112;
	int Constant113 = 0;
	bool Constant114 = false;
	int Mode_IfResult4;
	bool Override_IfResult4;
	if(Context.Map.RandomVector.OverrideRandomness)
	{
	Mode_IfResult4 = Context.Map.RandomVector.RandomnessMode;
	Override_IfResult4 = Context.Map.RandomVector.OverrideSeed;
	}
	else
	{
	Mode_IfResult4 = Constant113;
	Override_IfResult4 = Constant114;
	}
	float3 RandomUnitVector_Func_Output_UnitVector3D;
	float2 RandomUnitVector_Func_Output_UnitVector2D;
	RandomUnitVector_Func_(Context.Map.Constants.Empty004.RandomVector.RandomSeed, Mode_IfResult4, Override_IfResult4, Context.Map.RandomVector.FixedRandomSeed, RandomUnitVector_Func_Output_UnitVector3D, RandomUnitVector_Func_Output_UnitVector2D, Context);
	float Result130 = dot(RandomVector_NF_TransformVector_Empty004_Func_Output_OutVector,RandomUnitVector_Func_Output_UnitVector3D);
	float Result131 = sign(Result130);
	float3 Result132 = Result131 * RandomUnitVector_Func_Output_UnitVector3D;
	float3 Vector_IfResult1;
	if(Context.Map.RandomVector.ConstraintoAxis)
	{
	Vector_IfResult1 = Result132;
	}
	else
	{
	Vector_IfResult1 = RandomUnitVector_Func_Output_UnitVector3D;
	}
	float3 Result133 = Context.Map.RandomVector.VectorScale * Vector_IfResult1;
	Out_RandomVector = Result133;
}

void RandomVector001_NF_TransformVector_Empty004_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context)
{
	bool Constant135 = true;
	float4x4 Matrix_IfResult2;
	float4x4 Matrix001_IfResult1;
	if(In_ApplyScale)
	{
	Matrix_IfResult2 = Context.Map.Engine.Owner.SystemLocalToWorld;
	Matrix001_IfResult1 = Context.Map.Engine.Owner.SystemWorldToLocal;
	}
	else
	{
	Matrix_IfResult2 = Context.Map.Engine.Owner.SystemLocalToWorldNoScale;
	Matrix001_IfResult1 = Context.Map.Engine.Owner.SystemWorldToLocalNoScale;
	}
	bool TransformBase_Func_Output_bUseOriginal1;
	float4x4 TransformBase_Func_Output_OutTransform1;
	TransformBase_Func_(In_SourceSpace, In_DestinationSpace, Matrix_IfResult2, Matrix001_IfResult1, Constant135, TransformBase_Func_Output_bUseOriginal1, TransformBase_Func_Output_OutTransform1, Context);
	float3 Result134 = mul(float4(In_InVector,0.0),TransformBase_Func_Output_OutTransform1).xyz;
	float3 Vector_IfResult2;
	if(TransformBase_Func_Output_bUseOriginal1)
	{
	Vector_IfResult2 = In_InVector;
	}
	else
	{
	Vector_IfResult2 = Result134;
	}
	Out_OutVector = Vector_IfResult2;
}

void RandomVector001_Empty004_Func_(out float3 Out_RandomVector, inout FSimulationContext Context)
{
	bool Constant131 = false;
	Context.Map.RandomVector001.ConstraintoAxis = Constant131;
	int Constant132 = 2;
	int Constant133 = 0;
	bool Constant134 = false;
	float3 RandomVector001_NF_TransformVector_Empty004_Func_Output_OutVector;
	RandomVector001_NF_TransformVector_Empty004_Func_(Context.Map.Constants.Empty004.RandomVector001.ConstraintVector, Constant132, Constant133, Constant134, RandomVector001_NF_TransformVector_Empty004_Func_Output_OutVector, Context);
	bool Constant136 = false;
	Context.Map.RandomVector001.OverrideRandomness = Constant136;
	int Constant137 = 0;
	Context.Map.RandomVector001.RandomnessMode = Constant137;
	bool Constant138 = false;
	Context.Map.RandomVector001.OverrideSeed = Constant138;
	bool Constant139 = false;
	Context.Map.RandomVector001.FixedRandomSeed = Constant139;
	int Constant140 = 0;
	bool Constant141 = false;
	int Mode_IfResult5;
	bool Override_IfResult5;
	if(Context.Map.RandomVector001.OverrideRandomness)
	{
	Mode_IfResult5 = Context.Map.RandomVector001.RandomnessMode;
	Override_IfResult5 = Context.Map.RandomVector001.OverrideSeed;
	}
	else
	{
	Mode_IfResult5 = Constant140;
	Override_IfResult5 = Constant141;
	}
	float3 RandomUnitVector_Func_Output_UnitVector3D1;
	float2 RandomUnitVector_Func_Output_UnitVector2D1;
	RandomUnitVector_Func_(Context.Map.Constants.Empty004.RandomVector001.RandomSeed, Mode_IfResult5, Override_IfResult5, Context.Map.RandomVector001.FixedRandomSeed, RandomUnitVector_Func_Output_UnitVector3D1, RandomUnitVector_Func_Output_UnitVector2D1, Context);
	float Result135 = dot(RandomVector001_NF_TransformVector_Empty004_Func_Output_OutVector,RandomUnitVector_Func_Output_UnitVector3D1);
	float Result136 = sign(Result135);
	float3 Result137 = Result136 * RandomUnitVector_Func_Output_UnitVector3D1;
	float3 Vector_IfResult3;
	if(Context.Map.RandomVector001.ConstraintoAxis)
	{
	Vector_IfResult3 = Result137;
	}
	else
	{
	Vector_IfResult3 = RandomUnitVector_Func_Output_UnitVector3D1;
	}
	float3 Result138 = Context.Map.RandomVector001.VectorScale * Vector_IfResult3;
	Out_RandomVector = Result138;
}

void UniformRangedVector_Empty004_Func_(out float3 Out_UniformRangedVector, inout FSimulationContext Context)
{
	bool Constant142 = false;
	Context.Map.UniformRangedVector.OverrideRandomness = Constant142;
	int Constant143 = 0;
	Context.Map.UniformRangedVector.RandomnessMode = Constant143;
	bool Constant144 = false;
	Context.Map.UniformRangedVector.OverrideSeed = Constant144;
	bool Constant145 = false;
	Context.Map.UniformRangedVector.FixedRandomSeed = Constant145;
	int Constant146 = 0;
	bool Constant147 = false;
	int Mode_IfResult6;
	bool Override_IfResult6;
	if(Context.Map.UniformRangedVector.OverrideRandomness)
	{
	Mode_IfResult6 = Context.Map.UniformRangedVector.RandomnessMode;
	Override_IfResult6 = Context.Map.UniformRangedVector.OverrideSeed;
	}
	else
	{
	Mode_IfResult6 = Constant146;
	Override_IfResult6 = Constant147;
	}
	float3 RandomRangeFloat_Func_Output_Result5;
	RandomRangeFloat_Func_(Context.Map.Constants.Empty004.UniformRangedVector.Minimum, Context.Map.Constants.Empty004.UniformRangedVector.Maximum, Context.Map.Constants.Empty004.UniformRangedVector.RandomSeed, Mode_IfResult6, Override_IfResult6, Context.Map.UniformRangedVector.FixedRandomSeed, RandomRangeFloat_Func_Output_Result5, Context);
	Out_UniformRangedVector = RandomRangeFloat_Func_Output_Result5;
}

void DirectionAndLengthSafe_Func_(float3 In_V, float3 In_Fallback, float In_Threshold, float In_FallbackLength, out float3 Out_Direction, out float Out_Length, out bool Out_BelowThreshold, inout FSimulationContext Context)
{
	float Result140 = length(In_V);
	bool Result141 = NiagaraAll(Result140 < In_Threshold);
	float Result142 = length(In_Fallback);
	float3 Vector_IfResult4;
	float float_IfResult3;
	if(Result141)
	{
	Vector_IfResult4 = In_Fallback;
	float_IfResult3 = In_FallbackLength;
	}
	else
	{
	Vector_IfResult4 = In_V;
	float_IfResult3 = Result140;
	}
	float3 Result143 = Vector_IfResult4 / float_IfResult3;
	float3 Vector_IfResult5;
	float float_IfResult4;
	if(Result141)
	{
	Vector_IfResult5 = In_Fallback;
	float_IfResult4 = Result142;
	}
	else
	{
	Vector_IfResult5 = Result143;
	float_IfResult4 = float_IfResult3;
	}
	Out_Direction = Vector_IfResult5;
	Out_Length = float_IfResult4;
	Out_BelowThreshold = Result141;
}

void BeamEmitterSetup_NF_TransformVector_Empty004_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context)
{
	bool Constant154 = true;
	float4x4 Matrix_IfResult3;
	float4x4 Matrix001_IfResult2;
	if(In_ApplyScale)
	{
	Matrix_IfResult3 = Context.Map.Engine.Owner.SystemLocalToWorld;
	Matrix001_IfResult2 = Context.Map.Engine.Owner.SystemWorldToLocal;
	}
	else
	{
	Matrix_IfResult3 = Context.Map.Engine.Owner.SystemLocalToWorldNoScale;
	Matrix001_IfResult2 = Context.Map.Engine.Owner.SystemWorldToLocalNoScale;
	}
	bool TransformBase_Func_Output_bUseOriginal2;
	float4x4 TransformBase_Func_Output_OutTransform2;
	TransformBase_Func_(In_SourceSpace, In_DestinationSpace, Matrix_IfResult3, Matrix001_IfResult2, Constant154, TransformBase_Func_Output_bUseOriginal2, TransformBase_Func_Output_OutTransform2, Context);
	float3 Result144 = mul(float4(In_InVector,0.0),TransformBase_Func_Output_OutTransform2).xyz;
	float3 Vector_IfResult6;
	if(TransformBase_Func_Output_bUseOriginal2)
	{
	Vector_IfResult6 = In_InVector;
	}
	else
	{
	Vector_IfResult6 = Result144;
	}
	Out_OutVector = Vector_IfResult6;
}

void BeamEmitterSetup_Empty004_Func_(inout FSimulationContext Context)
{
	float3 Result139 = Context.Map.BeamEmitterSetup.BeamStart - Context.Map.BeamEmitterSetup.BeamEnd;
	float3 Constant148 = float3(0,0,1);
	float Constant149 = 1e-05;
	float Constant150 = 1;
	float3 DirectionAndLengthSafe_Func_Output_Direction;
	float DirectionAndLengthSafe_Func_Output_Length;
	bool DirectionAndLengthSafe_Func_Output_BelowThreshold;
	DirectionAndLengthSafe_Func_(Result139, Constant148, Constant149, Constant150, DirectionAndLengthSafe_Func_Output_Direction, DirectionAndLengthSafe_Func_Output_Length, DirectionAndLengthSafe_Func_Output_BelowThreshold, Context);
	int Constant151 = 2;
	int Constant152 = 0;
	bool Constant153 = false;
	float3 BeamEmitterSetup_NF_TransformVector_Empty004_Func_Output_OutVector;
	BeamEmitterSetup_NF_TransformVector_Empty004_Func_(Context.Map.BeamEmitterSetup.BeamEnd, Constant151, Constant152, Constant153, BeamEmitterSetup_NF_TransformVector_Empty004_Func_Output_OutVector, Context);
	float3 Result145 = Context.Map.BeamEmitterSetup.BeamStart + BeamEmitterSetup_NF_TransformVector_Empty004_Func_Output_OutVector;
	Context.Map.Local.BeamEmitterSetup.BeamStart = Context.Map.BeamEmitterSetup.BeamStart;
	Context.Map.Local.BeamEmitterSetup.BeamStartEndLength = DirectionAndLengthSafe_Func_Output_Length;
	Context.Map.Local.BeamEmitterSetup.BeamEnd = Result145;
	bool Constant155 = false;
	Context.Map.BeamEmitterSetup.AbsoluteStartTangent = Constant155;
	float3 Result146 = Context.Map.BeamEmitterSetup.BeamStartTangent * Context.Map.Local.BeamEmitterSetup.BeamStartEndLength;
	float3 Result147 = Context.Map.Local.BeamEmitterSetup.BeamStart + Result146;
	float3 Vector_IfResult7;
	if(Context.Map.BeamEmitterSetup.AbsoluteStartTangent)
	{
	Vector_IfResult7 = Context.Map.BeamEmitterSetup.BeamStartTangent;
	}
	else
	{
	Vector_IfResult7 = Result147;
	}
	bool Constant156 = false;
	Context.Map.BeamEmitterSetup.AbsoluteEndTangent = Constant156;
	float3 Result148 = Context.Map.Local.BeamEmitterSetup.BeamStartEndLength * Context.Map.BeamEmitterSetup.BeamEndTangent;
	float3 Result149 = Result148 + Context.Map.Local.BeamEmitterSetup.BeamEnd;
	float3 Vector_IfResult8;
	if(Context.Map.BeamEmitterSetup.AbsoluteEndTangent)
	{
	Vector_IfResult8 = Context.Map.BeamEmitterSetup.BeamEndTangent;
	}
	else
	{
	Vector_IfResult8 = Result149;
	}
	Context.Map.Local.BeamEmitterSetup.BeamStartTangent = Vector_IfResult7;
	Context.Map.Local.BeamEmitterSetup.BeamEndTangent = Vector_IfResult8;
	float3 Result150 = Context.Map.Local.BeamEmitterSetup.BeamEnd - Context.Map.Local.BeamEmitterSetup.BeamStart;
	float3 Constant157 = float3(0,0,1);
	float Constant158 = 1e-05;
	float Constant159 = 1;
	float3 DirectionAndLengthSafe_Func_Output_Direction1;
	float DirectionAndLengthSafe_Func_Output_Length1;
	bool DirectionAndLengthSafe_Func_Output_BelowThreshold1;
	DirectionAndLengthSafe_Func_(Result150, Constant157, Constant158, Constant159, DirectionAndLengthSafe_Func_Output_Direction1, DirectionAndLengthSafe_Func_Output_Length1, DirectionAndLengthSafe_Func_Output_BelowThreshold1, Context);
	Context.Map.Empty004.BeamStart = Context.Map.Local.BeamEmitterSetup.BeamStart;
	Context.Map.Empty004.BeamStartTangent = Context.Map.Local.BeamEmitterSetup.BeamStartTangent;
	Context.Map.Empty004.BeamEnd = Context.Map.Local.BeamEmitterSetup.BeamEnd;
	Context.Map.Empty004.BeamEndTangent = Context.Map.Local.BeamEmitterSetup.BeamEndTangent;
	Context.Map.Empty004.UseBeamTangents = Context.Map.BeamEmitterSetup.UseBeamTangents;
	Context.Map.Empty004.BeamStartEndLength = Context.Map.Local.BeamEmitterSetup.BeamStartEndLength;
	Context.Map.Empty004.BeamVector = Result150;
	Context.Map.Empty004.BeamDirection = DirectionAndLengthSafe_Func_Output_Direction1;
	bool Result151 = NiagaraAll(Context.Map.Empty004.LoopCount > Context.Map.Empty004.BeamID);
	int Constant160 = -1;
	int int32_IfResult;
	if(Result151)
	{
	int32_IfResult = Context.Map.Empty004.LoopCount;
	}
	else
	{
	int32_IfResult = Constant160;
	}
	Context.Map.Empty004.BeamID = int32_IfResult;
}

void Empty004_Func_(inout FSimulationContext Context)
{
	EnterStatScope(3 );
	EmitterState_Empty004_Func_(Context);
	ExitStatScope( );
	int UniformRangedInt_Empty004_Func_Output_UniformRangedInt;
	UniformRangedInt_Empty004_Func_(UniformRangedInt_Empty004_Func_Output_UniformRangedInt, Context);
	Context.Map.SpawnBurst_Instantaneous.SpawnCount = UniformRangedInt_Empty004_Func_Output_UniformRangedInt;
	EnterStatScope(4 );
	SpawnBurst_Instantaneous_Empty004_Func_(Context);
	ExitStatScope( );
	float UniformRangedFloat001_Empty004_Func_Output_UniformRangedFloat;
	UniformRangedFloat001_Empty004_Func_(UniformRangedFloat001_Empty004_Func_Output_UniformRangedFloat, Context);
	float UniformRangedFloat002_Empty004_Func_Output_UniformRangedFloat;
	UniformRangedFloat002_Empty004_Func_(UniformRangedFloat002_Empty004_Func_Output_UniformRangedFloat, Context);
	Context.Map.RandomVector.VectorScale = UniformRangedFloat001_Empty004_Func_Output_UniformRangedFloat;
	Context.Map.RandomVector001.VectorScale = UniformRangedFloat002_Empty004_Func_Output_UniformRangedFloat;
	float3 UniformRangedVector001_Empty004_Func_Output_UniformRangedVector;
	UniformRangedVector001_Empty004_Func_(UniformRangedVector001_Empty004_Func_Output_UniformRangedVector, Context);
	bool Constant97 = true;
	float3 RandomVector_Empty004_Func_Output_RandomVector;
	RandomVector_Empty004_Func_(RandomVector_Empty004_Func_Output_RandomVector, Context);
	float3 RandomVector001_Empty004_Func_Output_RandomVector;
	RandomVector001_Empty004_Func_(RandomVector001_Empty004_Func_Output_RandomVector, Context);
	float3 UniformRangedVector_Empty004_Func_Output_UniformRangedVector;
	UniformRangedVector_Empty004_Func_(UniformRangedVector_Empty004_Func_Output_UniformRangedVector, Context);
	Context.Map.BeamEmitterSetup.BeamStart = UniformRangedVector001_Empty004_Func_Output_UniformRangedVector;
	Context.Map.BeamEmitterSetup.UseBeamTangents = Constant97;
	Context.Map.BeamEmitterSetup.BeamStartTangent = RandomVector_Empty004_Func_Output_RandomVector;
	Context.Map.BeamEmitterSetup.BeamEndTangent = RandomVector001_Empty004_Func_Output_RandomVector;
	Context.Map.BeamEmitterSetup.BeamEnd = UniformRangedVector_Empty004_Func_Output_UniformRangedVector;
	EnterStatScope(5 );
	BeamEmitterSetup_Empty004_Func_(Context);
	ExitStatScope( );
}

void EmitterState_EmitterChangeState002_Grande_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	int Constant172 = 3;
	bool Result166 = NiagaraAll(Context.Map.Grande.ExecutionState != Constant172);
	int Constant173 = 4;
	bool Result167 = NiagaraAll(Context.Map.Grande.ExecutionState != Constant173);
	bool Result168 = Result166 && Result167;
	bool Result169 = In_Condition && Result168;
	bool Result170 = NiagaraAll(Context.Map.Grande.ExecutionStateSource <= In_NewStateSource);
	bool Result171 = Result169 && Result170;
	int ENiagaraExecutionState_IfResult6;
	int ENiagaraExecutionStateSource_IfResult6;
	if(Result171)
	{
	ENiagaraExecutionState_IfResult6 = In_NewState;
	ENiagaraExecutionStateSource_IfResult6 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult6 = Context.Map.Grande.ExecutionState;
	ENiagaraExecutionStateSource_IfResult6 = Context.Map.Grande.ExecutionStateSource;
	}
	Context.Map.Grande.ExecutionState = ENiagaraExecutionState_IfResult6;
	Context.Map.Grande.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult6;
}

void EmitterState_EmitterChangeState005_Grande_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	int Constant178 = 3;
	bool Result175 = NiagaraAll(Context.Map.Grande.ExecutionState != Constant178);
	int Constant179 = 4;
	bool Result176 = NiagaraAll(Context.Map.Grande.ExecutionState != Constant179);
	bool Result177 = Result175 && Result176;
	bool Result178 = In_Condition && Result177;
	bool Result179 = NiagaraAll(Context.Map.Grande.ExecutionStateSource <= In_NewStateSource);
	bool Result180 = Result178 && Result179;
	int ENiagaraExecutionState_IfResult7;
	int ENiagaraExecutionStateSource_IfResult7;
	if(Result180)
	{
	ENiagaraExecutionState_IfResult7 = In_NewState;
	ENiagaraExecutionStateSource_IfResult7 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult7 = Context.Map.Grande.ExecutionState;
	ENiagaraExecutionStateSource_IfResult7 = Context.Map.Grande.ExecutionStateSource;
	}
	Context.Map.Grande.ExecutionState = ENiagaraExecutionState_IfResult7;
	Context.Map.Grande.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult7;
}

void EmitterState_EmitterChangeState003_Grande_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	int Constant184 = 3;
	bool Result185 = NiagaraAll(Context.Map.Grande.ExecutionState != Constant184);
	int Constant185 = 4;
	bool Result186 = NiagaraAll(Context.Map.Grande.ExecutionState != Constant185);
	bool Result187 = Result185 && Result186;
	bool Result188 = In_Condition && Result187;
	bool Result189 = NiagaraAll(Context.Map.Grande.ExecutionStateSource <= In_NewStateSource);
	bool Result190 = Result188 && Result189;
	int ENiagaraExecutionState_IfResult8;
	int ENiagaraExecutionStateSource_IfResult8;
	if(Result190)
	{
	ENiagaraExecutionState_IfResult8 = In_NewState;
	ENiagaraExecutionStateSource_IfResult8 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult8 = Context.Map.Grande.ExecutionState;
	ENiagaraExecutionStateSource_IfResult8 = Context.Map.Grande.ExecutionStateSource;
	}
	Context.Map.Grande.ExecutionState = ENiagaraExecutionState_IfResult8;
	Context.Map.Grande.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult8;
}

void EmitterState_Grande_Func_(inout FSimulationContext Context)
{
	Context.Map.Local.EmitterState.PreviousEmitterState = Context.Map.Grande.ExecutionState;
	float Constant161 = 0.016667;
	float Result152 = max(Context.Map.Constants.Grande.EmitterState.LoopDuration, Constant161);
	Context.Map.Local.EmitterState.LoopDuration = Result152;
	float Constant162 = 0;
	bool Result153 = NiagaraAll(Context.Map.Grande.Age == Constant162);
	float Duration_IfResult2;
	if(Result153)
	{
	Duration_IfResult2 = Context.Map.Local.EmitterState.LoopDuration;
	}
	else
	{
	Duration_IfResult2 = Context.Map.Grande.CurrentLoopDuration;
	}
	float Constant163 = 0;
	Context.Map.Grande.CurrentLoopDuration = Duration_IfResult2;
	Context.Map.EmitterState.LoopDelay = Constant163;
	float Result154 = Context.Map.Grande.Age + Context.Map.Engine.DeltaTime;
	float Result155 = Context.Map.Engine.DeltaTime + Context.Map.Grande.LoopedAge;
	float Result156 = Result155 / Context.Map.Grande.CurrentLoopDuration;
	int Count2;
	Count2 = Result156;
	int Constant164 = 0;
	int Result157 = max(Count2, Constant164);
	float Result158 = Result157 * Context.Map.Grande.CurrentLoopDuration;
	float Result159 = Result155 - Result158;
	int Constant165 = 0;
	bool Result160 = NiagaraAll(Result157 > Constant165);
	int Result161 = Result157 + Context.Map.Grande.LoopCount;
	Context.Map.Grande.Age = Result154;
	Context.Map.Grande.LoopedAge = Result159;
	Context.Map.Local.EmitterState.LoopCountIncreased = Result160;
	Context.Map.Grande.LoopCount = Result161;
	bool Constant166 = false;
	Context.Map.EmitterState.RecalculateDurationEachLoop = Constant166;
	float float_IfResult5;
	if(Context.Map.EmitterState.RecalculateDurationEachLoop)
	{
	float_IfResult5 = Context.Map.Local.EmitterState.LoopDuration;
	}
	else
	{
	float_IfResult5 = Context.Map.Grande.CurrentLoopDuration;
	}
	float CurrentLoopDuration_IfResult2;
	float LoopedAge_IfResult2;
	if(Context.Map.Local.EmitterState.LoopCountIncreased)
	{
	CurrentLoopDuration_IfResult2 = float_IfResult5;
	LoopedAge_IfResult2 = Context.Map.Grande.LoopedAge;
	}
	else
	{
	CurrentLoopDuration_IfResult2 = Context.Map.Grande.CurrentLoopDuration;
	LoopedAge_IfResult2 = Context.Map.Grande.LoopedAge;
	}
	Context.Map.Grande.CurrentLoopDuration = CurrentLoopDuration_IfResult2;
	Context.Map.Grande.LoopedAge = LoopedAge_IfResult2;
	float Result162 = Context.Map.Grande.LoopedAge / Context.Map.Grande.CurrentLoopDuration;
	Context.Map.Grande.NormalizedLoopAge = Result162;
	float Constant167 = 0;
	float Constant168 = 1.0001;
	float Result163 = clamp(Context.Map.Engine.Owner.LODDistanceFraction,Constant167,Constant168);
	Context.Map.Grande.Scalability.DistanceFraction = Result163;
	int Constant169 = 0;
	Context.Map.Transient.ScalabilityEmitterExecutionState = Constant169;
	int Constant170 = 0;
	bool Result164 = NiagaraAll(Context.Map.Engine.Grande.NumParticles == Constant170);
	Context.Map.Local.EmitterState.NoActiveEmitterParticles = Result164;
	int Constant171 = 0;
	bool Result165 = NiagaraAll(Context.Map.System.ExecutionStateSource == Constant171);
	EmitterState_EmitterChangeState002_Grande_Func_(Context.Map.System.ExecutionState, Result165, Context.Map.System.ExecutionStateSource, Context);
	int Constant174 = 1;
	int Constant175 = 0;
	bool Result172 = NiagaraAll(Context.Map.System.ExecutionState != Constant175);
	int Constant176 = 2;
	bool Result173 = NiagaraAll(Context.Map.System.ExecutionStateSource == Constant176);
	bool Result174 = Result172 && Result173;
	int Constant177 = 1;
	EmitterState_EmitterChangeState005_Grande_Func_(Constant174, Result174, Constant177, Context);
	int Constant180 = 3;
	int Constant181 = 0;
	bool Result181 = NiagaraAll(Context.Map.Grande.ExecutionState != Constant181);
	int Constant182 = 0;
	bool Result182 = NiagaraAll(Context.Map.Grande.ExecutionStateSource != Constant182);
	bool Result183 = Result181 && Result182;
	bool Result184 = Context.Map.Local.EmitterState.NoActiveEmitterParticles && Result183;
	int Constant183 = 3;
	EmitterState_EmitterChangeState003_Grande_Func_(Constant180, Result184, Constant183, Context);
}

void UniformRangedInt_Grande_Func_(out int Out_UniformRangedInt, inout FSimulationContext Context)
{
	bool Constant186 = false;
	Context.Map.UniformRangedInt.OverrideRandomness = Constant186;
	int Constant187 = 0;
	Context.Map.UniformRangedInt.RandomnessMode = Constant187;
	bool Constant188 = false;
	Context.Map.UniformRangedInt.OverrideSeed = Constant188;
	bool Constant189 = false;
	Context.Map.UniformRangedInt.FixedRandomSeed = Constant189;
	int Constant190 = 0;
	bool Constant191 = false;
	int Mode_IfResult7;
	bool Override_IfResult7;
	if(Context.Map.UniformRangedInt.OverrideRandomness)
	{
	Mode_IfResult7 = Context.Map.UniformRangedInt.RandomnessMode;
	Override_IfResult7 = Context.Map.UniformRangedInt.OverrideSeed;
	}
	else
	{
	Mode_IfResult7 = Constant190;
	Override_IfResult7 = Constant191;
	}
	int RandomRangeInteger_Func_Output_Result1;
	RandomRangeInteger_Func_(Context.Map.Constants.Grande.UniformRangedInt.Minimum, Context.Map.Constants.Grande.UniformRangedInt.Maximum, Context.Map.Constants.Grande.UniformRangedInt.RandomSeed, Mode_IfResult7, Override_IfResult7, Context.Map.UniformRangedInt.FixedRandomSeed, RandomRangeInteger_Func_Output_Result1, Context);
	Out_UniformRangedInt = RandomRangeInteger_Func_Output_Result1;
}

void SpawnBurst_Instantaneous_Grande_Func_(inout FSimulationContext Context)
{
	Context.Map.SpawnBurst_Instantaneous.Age = Context.Map.Grande.LoopedAge;
	float Result191 = Context.Map.SpawnBurst_Instantaneous.Age - Context.Map.Engine.DeltaTime;
	float Result192 = Context.Map.Constants.Grande.SpawnBurst_Instantaneous.SpawnTime - Result191;
	float Constant192 = 0;
	float Output14;
	Output14 = Constant192;
	bool Result193 = NiagaraAll(Result192 >= Output14);
	float Result194 = Context.Map.Constants.Grande.SpawnBurst_Instantaneous.SpawnTime - Context.Map.SpawnBurst_Instantaneous.Age;
	bool Result195 = NiagaraAll(Result194 < Output14);
	bool Result196 = Result193 && Result195;
	int Constant193 = 0;
	bool Result197 = NiagaraAll(Context.Map.SpawnBurst_Instantaneous.SpawnCount == Constant193);
	float Constant194 = 0;
	float Result198 = Context.Map.SpawnBurst_Instantaneous.SpawnCount * Context.Map.Transient.ScalabilityEmitterSpawnCountScale * Context.Map.Engine.Grande.SpawnCountScale;
	float Constant195 = 1;
	float Result199 = max(Result198, Constant195);
	float float_IfResult6;
	if(Result197)
	{
	float_IfResult6 = Constant194;
	}
	else
	{
	float_IfResult6 = Result199;
	}
	float Constant196 = 0;
	NiagaraSpawnInfo Output15;
	Output15.Count = float_IfResult6;
	Output15.InterpStartDt = Result192;
	Output15.IntervalDt = Constant196;
	Output15.SpawnGroup = Context.Map.Constants.Grande.SpawnBurst_Instantaneous.SpawnGroup;
	int Constant197 = 0;
	float Constant198 = 0;
	float Constant199 = 0;
	NiagaraSpawnInfo Output16;
	Output16.Count = Constant197;
	Output16.InterpStartDt = Constant198;
	Output16.SpawnGroup = Context.Map.Constants.Grande.SpawnBurst_Instantaneous.SpawnGroup;
	Output16.IntervalDt = Constant199;
	NiagaraSpawnInfo SpawnInfo_IfResult1;
	if(Result196)
	{
	SpawnInfo_IfResult1 = Output15;
	}
	else
	{
	SpawnInfo_IfResult1 = Output16;
	}
	Context.Map.Grande.SpawnBurst_Instantaneous.SpawnBurst = SpawnInfo_IfResult1;
	bool Result200 = NiagaraAll(Context.Map.Grande.LoopedAge <= Context.Map.Constants.Grande.SpawnBurst_Instantaneous.SpawnTime);
	bool Result201 = Context.Map.Transient.SpawningbCanEverSpawn || Result200;
	Context.Map.Transient.SpawningbCanEverSpawn = Result201;
}

void UniformRangedFloat001_Grande_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context)
{
	bool Constant200 = false;
	Context.Map.UniformRangedFloat001.OverrideRandomness = Constant200;
	int Constant201 = 0;
	Context.Map.UniformRangedFloat001.RandomnessMode = Constant201;
	bool Constant202 = false;
	Context.Map.UniformRangedFloat001.OverrideSeed = Constant202;
	bool Constant203 = false;
	Context.Map.UniformRangedFloat001.FixedRandomSeed = Constant203;
	int Constant204 = 0;
	bool Constant205 = false;
	int Mode_IfResult8;
	bool Override_IfResult8;
	if(Context.Map.UniformRangedFloat001.OverrideRandomness)
	{
	Mode_IfResult8 = Context.Map.UniformRangedFloat001.RandomnessMode;
	Override_IfResult8 = Context.Map.UniformRangedFloat001.OverrideSeed;
	}
	else
	{
	Mode_IfResult8 = Constant204;
	Override_IfResult8 = Constant205;
	}
	float RandomRangeFloat_Func_Output_Result6;
	RandomRangeFloat_Func_(Context.Map.Constants.Grande.UniformRangedFloat001.Minimum, Context.Map.Constants.Grande.UniformRangedFloat001.Maximum, Context.Map.Constants.Grande.UniformRangedFloat001.RandomSeed, Mode_IfResult8, Override_IfResult8, Context.Map.UniformRangedFloat001.FixedRandomSeed, RandomRangeFloat_Func_Output_Result6, Context);
	Out_UniformRangedFloat = RandomRangeFloat_Func_Output_Result6;
}

void UniformRangedFloat002_Grande_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context)
{
	bool Constant206 = false;
	Context.Map.UniformRangedFloat002.OverrideRandomness = Constant206;
	int Constant207 = 0;
	Context.Map.UniformRangedFloat002.RandomnessMode = Constant207;
	bool Constant208 = false;
	Context.Map.UniformRangedFloat002.OverrideSeed = Constant208;
	bool Constant209 = false;
	Context.Map.UniformRangedFloat002.FixedRandomSeed = Constant209;
	int Constant210 = 0;
	bool Constant211 = false;
	int Mode_IfResult9;
	bool Override_IfResult9;
	if(Context.Map.UniformRangedFloat002.OverrideRandomness)
	{
	Mode_IfResult9 = Context.Map.UniformRangedFloat002.RandomnessMode;
	Override_IfResult9 = Context.Map.UniformRangedFloat002.OverrideSeed;
	}
	else
	{
	Mode_IfResult9 = Constant210;
	Override_IfResult9 = Constant211;
	}
	float RandomRangeFloat_Func_Output_Result7;
	RandomRangeFloat_Func_(Context.Map.Constants.Grande.UniformRangedFloat002.Minimum, Context.Map.Constants.Grande.UniformRangedFloat002.Maximum, Context.Map.Constants.Grande.UniformRangedFloat002.RandomSeed, Mode_IfResult9, Override_IfResult9, Context.Map.UniformRangedFloat002.FixedRandomSeed, RandomRangeFloat_Func_Output_Result7, Context);
	Out_UniformRangedFloat = RandomRangeFloat_Func_Output_Result7;
}

void RandomVector_NF_TransformVector_Grande_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context)
{
	bool Constant218 = true;
	float4x4 Matrix_IfResult4;
	float4x4 Matrix001_IfResult3;
	if(In_ApplyScale)
	{
	Matrix_IfResult4 = Context.Map.Engine.Owner.SystemLocalToWorld;
	Matrix001_IfResult3 = Context.Map.Engine.Owner.SystemWorldToLocal;
	}
	else
	{
	Matrix_IfResult4 = Context.Map.Engine.Owner.SystemLocalToWorldNoScale;
	Matrix001_IfResult3 = Context.Map.Engine.Owner.SystemWorldToLocalNoScale;
	}
	bool TransformBase_Func_Output_bUseOriginal3;
	float4x4 TransformBase_Func_Output_OutTransform3;
	TransformBase_Func_(In_SourceSpace, In_DestinationSpace, Matrix_IfResult4, Matrix001_IfResult3, Constant218, TransformBase_Func_Output_bUseOriginal3, TransformBase_Func_Output_OutTransform3, Context);
	float3 Result202 = mul(float4(In_InVector,0.0),TransformBase_Func_Output_OutTransform3).xyz;
	float3 Vector_IfResult9;
	if(TransformBase_Func_Output_bUseOriginal3)
	{
	Vector_IfResult9 = In_InVector;
	}
	else
	{
	Vector_IfResult9 = Result202;
	}
	Out_OutVector = Vector_IfResult9;
}

void RandomVector_Grande_Func_(out float3 Out_RandomVector, inout FSimulationContext Context)
{
	bool Constant214 = false;
	Context.Map.RandomVector.ConstraintoAxis = Constant214;
	int Constant215 = 2;
	int Constant216 = 0;
	bool Constant217 = false;
	float3 RandomVector_NF_TransformVector_Grande_Func_Output_OutVector;
	RandomVector_NF_TransformVector_Grande_Func_(Context.Map.Constants.Grande.RandomVector.ConstraintVector, Constant215, Constant216, Constant217, RandomVector_NF_TransformVector_Grande_Func_Output_OutVector, Context);
	bool Constant219 = false;
	Context.Map.RandomVector.OverrideRandomness = Constant219;
	int Constant220 = 0;
	Context.Map.RandomVector.RandomnessMode = Constant220;
	bool Constant221 = false;
	Context.Map.RandomVector.OverrideSeed = Constant221;
	bool Constant222 = false;
	Context.Map.RandomVector.FixedRandomSeed = Constant222;
	int Constant223 = 0;
	bool Constant224 = false;
	int Mode_IfResult10;
	bool Override_IfResult10;
	if(Context.Map.RandomVector.OverrideRandomness)
	{
	Mode_IfResult10 = Context.Map.RandomVector.RandomnessMode;
	Override_IfResult10 = Context.Map.RandomVector.OverrideSeed;
	}
	else
	{
	Mode_IfResult10 = Constant223;
	Override_IfResult10 = Constant224;
	}
	float3 RandomUnitVector_Func_Output_UnitVector3D2;
	float2 RandomUnitVector_Func_Output_UnitVector2D2;
	RandomUnitVector_Func_(Context.Map.Constants.Grande.RandomVector.RandomSeed, Mode_IfResult10, Override_IfResult10, Context.Map.RandomVector.FixedRandomSeed, RandomUnitVector_Func_Output_UnitVector3D2, RandomUnitVector_Func_Output_UnitVector2D2, Context);
	float Result203 = dot(RandomVector_NF_TransformVector_Grande_Func_Output_OutVector,RandomUnitVector_Func_Output_UnitVector3D2);
	float Result204 = sign(Result203);
	float3 Result205 = Result204 * RandomUnitVector_Func_Output_UnitVector3D2;
	float3 Vector_IfResult10;
	if(Context.Map.RandomVector.ConstraintoAxis)
	{
	Vector_IfResult10 = Result205;
	}
	else
	{
	Vector_IfResult10 = RandomUnitVector_Func_Output_UnitVector3D2;
	}
	float3 Result206 = Context.Map.RandomVector.VectorScale * Vector_IfResult10;
	Out_RandomVector = Result206;
}

void RandomVector001_NF_TransformVector_Grande_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context)
{
	bool Constant229 = true;
	float4x4 Matrix_IfResult5;
	float4x4 Matrix001_IfResult4;
	if(In_ApplyScale)
	{
	Matrix_IfResult5 = Context.Map.Engine.Owner.SystemLocalToWorld;
	Matrix001_IfResult4 = Context.Map.Engine.Owner.SystemWorldToLocal;
	}
	else
	{
	Matrix_IfResult5 = Context.Map.Engine.Owner.SystemLocalToWorldNoScale;
	Matrix001_IfResult4 = Context.Map.Engine.Owner.SystemWorldToLocalNoScale;
	}
	bool TransformBase_Func_Output_bUseOriginal4;
	float4x4 TransformBase_Func_Output_OutTransform4;
	TransformBase_Func_(In_SourceSpace, In_DestinationSpace, Matrix_IfResult5, Matrix001_IfResult4, Constant229, TransformBase_Func_Output_bUseOriginal4, TransformBase_Func_Output_OutTransform4, Context);
	float3 Result207 = mul(float4(In_InVector,0.0),TransformBase_Func_Output_OutTransform4).xyz;
	float3 Vector_IfResult11;
	if(TransformBase_Func_Output_bUseOriginal4)
	{
	Vector_IfResult11 = In_InVector;
	}
	else
	{
	Vector_IfResult11 = Result207;
	}
	Out_OutVector = Vector_IfResult11;
}

void RandomVector001_Grande_Func_(out float3 Out_RandomVector, inout FSimulationContext Context)
{
	bool Constant225 = false;
	Context.Map.RandomVector001.ConstraintoAxis = Constant225;
	int Constant226 = 2;
	int Constant227 = 0;
	bool Constant228 = false;
	float3 RandomVector001_NF_TransformVector_Grande_Func_Output_OutVector;
	RandomVector001_NF_TransformVector_Grande_Func_(Context.Map.Constants.Grande.RandomVector001.ConstraintVector, Constant226, Constant227, Constant228, RandomVector001_NF_TransformVector_Grande_Func_Output_OutVector, Context);
	bool Constant230 = false;
	Context.Map.RandomVector001.OverrideRandomness = Constant230;
	int Constant231 = 0;
	Context.Map.RandomVector001.RandomnessMode = Constant231;
	bool Constant232 = false;
	Context.Map.RandomVector001.OverrideSeed = Constant232;
	bool Constant233 = false;
	Context.Map.RandomVector001.FixedRandomSeed = Constant233;
	int Constant234 = 0;
	bool Constant235 = false;
	int Mode_IfResult11;
	bool Override_IfResult11;
	if(Context.Map.RandomVector001.OverrideRandomness)
	{
	Mode_IfResult11 = Context.Map.RandomVector001.RandomnessMode;
	Override_IfResult11 = Context.Map.RandomVector001.OverrideSeed;
	}
	else
	{
	Mode_IfResult11 = Constant234;
	Override_IfResult11 = Constant235;
	}
	float3 RandomUnitVector_Func_Output_UnitVector3D3;
	float2 RandomUnitVector_Func_Output_UnitVector2D3;
	RandomUnitVector_Func_(Context.Map.Constants.Grande.RandomVector001.RandomSeed, Mode_IfResult11, Override_IfResult11, Context.Map.RandomVector001.FixedRandomSeed, RandomUnitVector_Func_Output_UnitVector3D3, RandomUnitVector_Func_Output_UnitVector2D3, Context);
	float Result208 = dot(RandomVector001_NF_TransformVector_Grande_Func_Output_OutVector,RandomUnitVector_Func_Output_UnitVector3D3);
	float Result209 = sign(Result208);
	float3 Result210 = Result209 * RandomUnitVector_Func_Output_UnitVector3D3;
	float3 Vector_IfResult12;
	if(Context.Map.RandomVector001.ConstraintoAxis)
	{
	Vector_IfResult12 = Result210;
	}
	else
	{
	Vector_IfResult12 = RandomUnitVector_Func_Output_UnitVector3D3;
	}
	float3 Result211 = Context.Map.RandomVector001.VectorScale * Vector_IfResult12;
	Out_RandomVector = Result211;
}

void UniformRangedVector_Grande_Func_(out float3 Out_UniformRangedVector, inout FSimulationContext Context)
{
	bool Constant236 = false;
	Context.Map.UniformRangedVector.OverrideRandomness = Constant236;
	int Constant237 = 0;
	Context.Map.UniformRangedVector.RandomnessMode = Constant237;
	bool Constant238 = false;
	Context.Map.UniformRangedVector.OverrideSeed = Constant238;
	bool Constant239 = false;
	Context.Map.UniformRangedVector.FixedRandomSeed = Constant239;
	int Constant240 = 0;
	bool Constant241 = false;
	int Mode_IfResult12;
	bool Override_IfResult12;
	if(Context.Map.UniformRangedVector.OverrideRandomness)
	{
	Mode_IfResult12 = Context.Map.UniformRangedVector.RandomnessMode;
	Override_IfResult12 = Context.Map.UniformRangedVector.OverrideSeed;
	}
	else
	{
	Mode_IfResult12 = Constant240;
	Override_IfResult12 = Constant241;
	}
	float3 RandomRangeFloat_Func_Output_Result8;
	RandomRangeFloat_Func_(Context.Map.Constants.Grande.UniformRangedVector.Minimum, Context.Map.Constants.Grande.UniformRangedVector.Maximum, Context.Map.Constants.Grande.UniformRangedVector.RandomSeed, Mode_IfResult12, Override_IfResult12, Context.Map.UniformRangedVector.FixedRandomSeed, RandomRangeFloat_Func_Output_Result8, Context);
	Out_UniformRangedVector = RandomRangeFloat_Func_Output_Result8;
}

void BeamEmitterSetup_NF_TransformVector_Grande_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context)
{
	bool Constant248 = true;
	float4x4 Matrix_IfResult6;
	float4x4 Matrix001_IfResult5;
	if(In_ApplyScale)
	{
	Matrix_IfResult6 = Context.Map.Engine.Owner.SystemLocalToWorld;
	Matrix001_IfResult5 = Context.Map.Engine.Owner.SystemWorldToLocal;
	}
	else
	{
	Matrix_IfResult6 = Context.Map.Engine.Owner.SystemLocalToWorldNoScale;
	Matrix001_IfResult5 = Context.Map.Engine.Owner.SystemWorldToLocalNoScale;
	}
	bool TransformBase_Func_Output_bUseOriginal5;
	float4x4 TransformBase_Func_Output_OutTransform5;
	TransformBase_Func_(In_SourceSpace, In_DestinationSpace, Matrix_IfResult6, Matrix001_IfResult5, Constant248, TransformBase_Func_Output_bUseOriginal5, TransformBase_Func_Output_OutTransform5, Context);
	float3 Result213 = mul(float4(In_InVector,0.0),TransformBase_Func_Output_OutTransform5).xyz;
	float3 Vector_IfResult13;
	if(TransformBase_Func_Output_bUseOriginal5)
	{
	Vector_IfResult13 = In_InVector;
	}
	else
	{
	Vector_IfResult13 = Result213;
	}
	Out_OutVector = Vector_IfResult13;
}

void BeamEmitterSetup_Grande_Func_(inout FSimulationContext Context)
{
	float3 Result212 = Context.Map.BeamEmitterSetup.BeamStart - Context.Map.BeamEmitterSetup.BeamEnd;
	float3 Constant242 = float3(0,0,1);
	float Constant243 = 1e-05;
	float Constant244 = 1;
	float3 DirectionAndLengthSafe_Func_Output_Direction2;
	float DirectionAndLengthSafe_Func_Output_Length2;
	bool DirectionAndLengthSafe_Func_Output_BelowThreshold2;
	DirectionAndLengthSafe_Func_(Result212, Constant242, Constant243, Constant244, DirectionAndLengthSafe_Func_Output_Direction2, DirectionAndLengthSafe_Func_Output_Length2, DirectionAndLengthSafe_Func_Output_BelowThreshold2, Context);
	int Constant245 = 2;
	int Constant246 = 0;
	bool Constant247 = false;
	float3 BeamEmitterSetup_NF_TransformVector_Grande_Func_Output_OutVector;
	BeamEmitterSetup_NF_TransformVector_Grande_Func_(Context.Map.BeamEmitterSetup.BeamEnd, Constant245, Constant246, Constant247, BeamEmitterSetup_NF_TransformVector_Grande_Func_Output_OutVector, Context);
	float3 Result214 = Context.Map.BeamEmitterSetup.BeamStart + BeamEmitterSetup_NF_TransformVector_Grande_Func_Output_OutVector;
	Context.Map.Local.BeamEmitterSetup.BeamStart = Context.Map.BeamEmitterSetup.BeamStart;
	Context.Map.Local.BeamEmitterSetup.BeamStartEndLength = DirectionAndLengthSafe_Func_Output_Length2;
	Context.Map.Local.BeamEmitterSetup.BeamEnd = Result214;
	bool Constant249 = false;
	Context.Map.BeamEmitterSetup.AbsoluteStartTangent = Constant249;
	float3 Result215 = Context.Map.BeamEmitterSetup.BeamStartTangent * Context.Map.Local.BeamEmitterSetup.BeamStartEndLength;
	float3 Result216 = Context.Map.Local.BeamEmitterSetup.BeamStart + Result215;
	float3 Vector_IfResult14;
	if(Context.Map.BeamEmitterSetup.AbsoluteStartTangent)
	{
	Vector_IfResult14 = Context.Map.BeamEmitterSetup.BeamStartTangent;
	}
	else
	{
	Vector_IfResult14 = Result216;
	}
	bool Constant250 = false;
	Context.Map.BeamEmitterSetup.AbsoluteEndTangent = Constant250;
	float3 Result217 = Context.Map.Local.BeamEmitterSetup.BeamStartEndLength * Context.Map.BeamEmitterSetup.BeamEndTangent;
	float3 Result218 = Result217 + Context.Map.Local.BeamEmitterSetup.BeamEnd;
	float3 Vector_IfResult15;
	if(Context.Map.BeamEmitterSetup.AbsoluteEndTangent)
	{
	Vector_IfResult15 = Context.Map.BeamEmitterSetup.BeamEndTangent;
	}
	else
	{
	Vector_IfResult15 = Result218;
	}
	Context.Map.Local.BeamEmitterSetup.BeamStartTangent = Vector_IfResult14;
	Context.Map.Local.BeamEmitterSetup.BeamEndTangent = Vector_IfResult15;
	float3 Result219 = Context.Map.Local.BeamEmitterSetup.BeamEnd - Context.Map.Local.BeamEmitterSetup.BeamStart;
	float3 Constant251 = float3(0,0,1);
	float Constant252 = 1e-05;
	float Constant253 = 1;
	float3 DirectionAndLengthSafe_Func_Output_Direction3;
	float DirectionAndLengthSafe_Func_Output_Length3;
	bool DirectionAndLengthSafe_Func_Output_BelowThreshold3;
	DirectionAndLengthSafe_Func_(Result219, Constant251, Constant252, Constant253, DirectionAndLengthSafe_Func_Output_Direction3, DirectionAndLengthSafe_Func_Output_Length3, DirectionAndLengthSafe_Func_Output_BelowThreshold3, Context);
	Context.Map.Grande.BeamStart = Context.Map.Local.BeamEmitterSetup.BeamStart;
	Context.Map.Grande.BeamStartTangent = Context.Map.Local.BeamEmitterSetup.BeamStartTangent;
	Context.Map.Grande.BeamEnd = Context.Map.Local.BeamEmitterSetup.BeamEnd;
	Context.Map.Grande.BeamEndTangent = Context.Map.Local.BeamEmitterSetup.BeamEndTangent;
	Context.Map.Grande.UseBeamTangents = Context.Map.BeamEmitterSetup.UseBeamTangents;
	Context.Map.Grande.BeamStartEndLength = Context.Map.Local.BeamEmitterSetup.BeamStartEndLength;
	Context.Map.Grande.BeamVector = Result219;
	Context.Map.Grande.BeamDirection = DirectionAndLengthSafe_Func_Output_Direction3;
	bool Result220 = NiagaraAll(Context.Map.Grande.LoopCount > Context.Map.Grande.BeamID);
	int Constant254 = -1;
	int int32_IfResult1;
	if(Result220)
	{
	int32_IfResult1 = Context.Map.Grande.LoopCount;
	}
	else
	{
	int32_IfResult1 = Constant254;
	}
	Context.Map.Grande.BeamID = int32_IfResult1;
}

void Grande_Func_(inout FSimulationContext Context)
{
	EnterStatScope(7 );
	EmitterState_Grande_Func_(Context);
	ExitStatScope( );
	int UniformRangedInt_Grande_Func_Output_UniformRangedInt;
	UniformRangedInt_Grande_Func_(UniformRangedInt_Grande_Func_Output_UniformRangedInt, Context);
	Context.Map.SpawnBurst_Instantaneous.SpawnCount = UniformRangedInt_Grande_Func_Output_UniformRangedInt;
	EnterStatScope(8 );
	SpawnBurst_Instantaneous_Grande_Func_(Context);
	ExitStatScope( );
	float UniformRangedFloat001_Grande_Func_Output_UniformRangedFloat;
	UniformRangedFloat001_Grande_Func_(UniformRangedFloat001_Grande_Func_Output_UniformRangedFloat, Context);
	float UniformRangedFloat002_Grande_Func_Output_UniformRangedFloat;
	UniformRangedFloat002_Grande_Func_(UniformRangedFloat002_Grande_Func_Output_UniformRangedFloat, Context);
	Context.Map.RandomVector.VectorScale = UniformRangedFloat001_Grande_Func_Output_UniformRangedFloat;
	Context.Map.RandomVector001.VectorScale = UniformRangedFloat002_Grande_Func_Output_UniformRangedFloat;
	float3 Constant212 = float3(0,0,0);
	bool Constant213 = true;
	float3 RandomVector_Grande_Func_Output_RandomVector;
	RandomVector_Grande_Func_(RandomVector_Grande_Func_Output_RandomVector, Context);
	float3 RandomVector001_Grande_Func_Output_RandomVector;
	RandomVector001_Grande_Func_(RandomVector001_Grande_Func_Output_RandomVector, Context);
	float3 UniformRangedVector_Grande_Func_Output_UniformRangedVector;
	UniformRangedVector_Grande_Func_(UniformRangedVector_Grande_Func_Output_UniformRangedVector, Context);
	Context.Map.BeamEmitterSetup.BeamStart = Constant212;
	Context.Map.BeamEmitterSetup.UseBeamTangents = Constant213;
	Context.Map.BeamEmitterSetup.BeamStartTangent = RandomVector_Grande_Func_Output_RandomVector;
	Context.Map.BeamEmitterSetup.BeamEndTangent = RandomVector001_Grande_Func_Output_RandomVector;
	Context.Map.BeamEmitterSetup.BeamEnd = UniformRangedVector_Grande_Func_Output_UniformRangedVector;
	EnterStatScope(9 );
	BeamEmitterSetup_Grande_Func_(Context);
	ExitStatScope( );
}

void EmitterState_EmitterChangeState002_Peque_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	int Constant266 = 3;
	bool Result235 = NiagaraAll(Context.Map.Peque.ExecutionState != Constant266);
	int Constant267 = 4;
	bool Result236 = NiagaraAll(Context.Map.Peque.ExecutionState != Constant267);
	bool Result237 = Result235 && Result236;
	bool Result238 = In_Condition && Result237;
	bool Result239 = NiagaraAll(Context.Map.Peque.ExecutionStateSource <= In_NewStateSource);
	bool Result240 = Result238 && Result239;
	int ENiagaraExecutionState_IfResult9;
	int ENiagaraExecutionStateSource_IfResult9;
	if(Result240)
	{
	ENiagaraExecutionState_IfResult9 = In_NewState;
	ENiagaraExecutionStateSource_IfResult9 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult9 = Context.Map.Peque.ExecutionState;
	ENiagaraExecutionStateSource_IfResult9 = Context.Map.Peque.ExecutionStateSource;
	}
	Context.Map.Peque.ExecutionState = ENiagaraExecutionState_IfResult9;
	Context.Map.Peque.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult9;
}

void EmitterState_EmitterChangeState005_Peque_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	int Constant272 = 3;
	bool Result244 = NiagaraAll(Context.Map.Peque.ExecutionState != Constant272);
	int Constant273 = 4;
	bool Result245 = NiagaraAll(Context.Map.Peque.ExecutionState != Constant273);
	bool Result246 = Result244 && Result245;
	bool Result247 = In_Condition && Result246;
	bool Result248 = NiagaraAll(Context.Map.Peque.ExecutionStateSource <= In_NewStateSource);
	bool Result249 = Result247 && Result248;
	int ENiagaraExecutionState_IfResult10;
	int ENiagaraExecutionStateSource_IfResult10;
	if(Result249)
	{
	ENiagaraExecutionState_IfResult10 = In_NewState;
	ENiagaraExecutionStateSource_IfResult10 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult10 = Context.Map.Peque.ExecutionState;
	ENiagaraExecutionStateSource_IfResult10 = Context.Map.Peque.ExecutionStateSource;
	}
	Context.Map.Peque.ExecutionState = ENiagaraExecutionState_IfResult10;
	Context.Map.Peque.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult10;
}

void EmitterState_EmitterChangeState003_Peque_Func_(int In_NewState, bool In_Condition, int In_NewStateSource, inout FSimulationContext Context)
{
	int Constant278 = 3;
	bool Result254 = NiagaraAll(Context.Map.Peque.ExecutionState != Constant278);
	int Constant279 = 4;
	bool Result255 = NiagaraAll(Context.Map.Peque.ExecutionState != Constant279);
	bool Result256 = Result254 && Result255;
	bool Result257 = In_Condition && Result256;
	bool Result258 = NiagaraAll(Context.Map.Peque.ExecutionStateSource <= In_NewStateSource);
	bool Result259 = Result257 && Result258;
	int ENiagaraExecutionState_IfResult11;
	int ENiagaraExecutionStateSource_IfResult11;
	if(Result259)
	{
	ENiagaraExecutionState_IfResult11 = In_NewState;
	ENiagaraExecutionStateSource_IfResult11 = In_NewStateSource;
	}
	else
	{
	ENiagaraExecutionState_IfResult11 = Context.Map.Peque.ExecutionState;
	ENiagaraExecutionStateSource_IfResult11 = Context.Map.Peque.ExecutionStateSource;
	}
	Context.Map.Peque.ExecutionState = ENiagaraExecutionState_IfResult11;
	Context.Map.Peque.ExecutionStateSource = ENiagaraExecutionStateSource_IfResult11;
}

void EmitterState_Peque_Func_(inout FSimulationContext Context)
{
	Context.Map.Local.EmitterState.PreviousEmitterState = Context.Map.Peque.ExecutionState;
	float Constant255 = 0.016667;
	float Result221 = max(Context.Map.Constants.Peque.EmitterState.LoopDuration, Constant255);
	Context.Map.Local.EmitterState.LoopDuration = Result221;
	float Constant256 = 0;
	bool Result222 = NiagaraAll(Context.Map.Peque.Age == Constant256);
	float Duration_IfResult3;
	if(Result222)
	{
	Duration_IfResult3 = Context.Map.Local.EmitterState.LoopDuration;
	}
	else
	{
	Duration_IfResult3 = Context.Map.Peque.CurrentLoopDuration;
	}
	float Constant257 = 0;
	Context.Map.Peque.CurrentLoopDuration = Duration_IfResult3;
	Context.Map.EmitterState.LoopDelay = Constant257;
	float Result223 = Context.Map.Peque.Age + Context.Map.Engine.DeltaTime;
	float Result224 = Context.Map.Engine.DeltaTime + Context.Map.Peque.LoopedAge;
	float Result225 = Result224 / Context.Map.Peque.CurrentLoopDuration;
	int Count3;
	Count3 = Result225;
	int Constant258 = 0;
	int Result226 = max(Count3, Constant258);
	float Result227 = Result226 * Context.Map.Peque.CurrentLoopDuration;
	float Result228 = Result224 - Result227;
	int Constant259 = 0;
	bool Result229 = NiagaraAll(Result226 > Constant259);
	int Result230 = Result226 + Context.Map.Peque.LoopCount;
	Context.Map.Peque.Age = Result223;
	Context.Map.Peque.LoopedAge = Result228;
	Context.Map.Local.EmitterState.LoopCountIncreased = Result229;
	Context.Map.Peque.LoopCount = Result230;
	bool Constant260 = false;
	Context.Map.EmitterState.RecalculateDurationEachLoop = Constant260;
	float float_IfResult7;
	if(Context.Map.EmitterState.RecalculateDurationEachLoop)
	{
	float_IfResult7 = Context.Map.Local.EmitterState.LoopDuration;
	}
	else
	{
	float_IfResult7 = Context.Map.Peque.CurrentLoopDuration;
	}
	float CurrentLoopDuration_IfResult3;
	float LoopedAge_IfResult3;
	if(Context.Map.Local.EmitterState.LoopCountIncreased)
	{
	CurrentLoopDuration_IfResult3 = float_IfResult7;
	LoopedAge_IfResult3 = Context.Map.Peque.LoopedAge;
	}
	else
	{
	CurrentLoopDuration_IfResult3 = Context.Map.Peque.CurrentLoopDuration;
	LoopedAge_IfResult3 = Context.Map.Peque.LoopedAge;
	}
	Context.Map.Peque.CurrentLoopDuration = CurrentLoopDuration_IfResult3;
	Context.Map.Peque.LoopedAge = LoopedAge_IfResult3;
	float Result231 = Context.Map.Peque.LoopedAge / Context.Map.Peque.CurrentLoopDuration;
	Context.Map.Peque.NormalizedLoopAge = Result231;
	float Constant261 = 0;
	float Constant262 = 1.0001;
	float Result232 = clamp(Context.Map.Engine.Owner.LODDistanceFraction,Constant261,Constant262);
	Context.Map.Peque.Scalability.DistanceFraction = Result232;
	int Constant263 = 0;
	Context.Map.Transient.ScalabilityEmitterExecutionState = Constant263;
	int Constant264 = 0;
	bool Result233 = NiagaraAll(Context.Map.Engine.Peque.NumParticles == Constant264);
	Context.Map.Local.EmitterState.NoActiveEmitterParticles = Result233;
	int Constant265 = 0;
	bool Result234 = NiagaraAll(Context.Map.System.ExecutionStateSource == Constant265);
	EmitterState_EmitterChangeState002_Peque_Func_(Context.Map.System.ExecutionState, Result234, Context.Map.System.ExecutionStateSource, Context);
	int Constant268 = 1;
	int Constant269 = 0;
	bool Result241 = NiagaraAll(Context.Map.System.ExecutionState != Constant269);
	int Constant270 = 2;
	bool Result242 = NiagaraAll(Context.Map.System.ExecutionStateSource == Constant270);
	bool Result243 = Result241 && Result242;
	int Constant271 = 1;
	EmitterState_EmitterChangeState005_Peque_Func_(Constant268, Result243, Constant271, Context);
	int Constant274 = 3;
	int Constant275 = 0;
	bool Result250 = NiagaraAll(Context.Map.Peque.ExecutionState != Constant275);
	int Constant276 = 0;
	bool Result251 = NiagaraAll(Context.Map.Peque.ExecutionStateSource != Constant276);
	bool Result252 = Result250 && Result251;
	bool Result253 = Context.Map.Local.EmitterState.NoActiveEmitterParticles && Result252;
	int Constant277 = 3;
	EmitterState_EmitterChangeState003_Peque_Func_(Constant274, Result253, Constant277, Context);
}

void UniformRangedInt_Peque_Func_(out int Out_UniformRangedInt, inout FSimulationContext Context)
{
	bool Constant280 = false;
	Context.Map.UniformRangedInt.OverrideRandomness = Constant280;
	int Constant281 = 0;
	Context.Map.UniformRangedInt.RandomnessMode = Constant281;
	bool Constant282 = false;
	Context.Map.UniformRangedInt.OverrideSeed = Constant282;
	bool Constant283 = false;
	Context.Map.UniformRangedInt.FixedRandomSeed = Constant283;
	int Constant284 = 0;
	bool Constant285 = false;
	int Mode_IfResult13;
	bool Override_IfResult13;
	if(Context.Map.UniformRangedInt.OverrideRandomness)
	{
	Mode_IfResult13 = Context.Map.UniformRangedInt.RandomnessMode;
	Override_IfResult13 = Context.Map.UniformRangedInt.OverrideSeed;
	}
	else
	{
	Mode_IfResult13 = Constant284;
	Override_IfResult13 = Constant285;
	}
	int RandomRangeInteger_Func_Output_Result2;
	RandomRangeInteger_Func_(Context.Map.Constants.Peque.UniformRangedInt.Minimum, Context.Map.Constants.Peque.UniformRangedInt.Maximum, Context.Map.Constants.Peque.UniformRangedInt.RandomSeed, Mode_IfResult13, Override_IfResult13, Context.Map.UniformRangedInt.FixedRandomSeed, RandomRangeInteger_Func_Output_Result2, Context);
	Out_UniformRangedInt = RandomRangeInteger_Func_Output_Result2;
}

void SpawnBurst_Instantaneous_Peque_Func_(inout FSimulationContext Context)
{
	Context.Map.SpawnBurst_Instantaneous.Age = Context.Map.Peque.LoopedAge;
	float Result260 = Context.Map.SpawnBurst_Instantaneous.Age - Context.Map.Engine.DeltaTime;
	float Result261 = Context.Map.Constants.Peque.SpawnBurst_Instantaneous.SpawnTime - Result260;
	float Constant286 = 0;
	float Output17;
	Output17 = Constant286;
	bool Result262 = NiagaraAll(Result261 >= Output17);
	float Result263 = Context.Map.Constants.Peque.SpawnBurst_Instantaneous.SpawnTime - Context.Map.SpawnBurst_Instantaneous.Age;
	bool Result264 = NiagaraAll(Result263 < Output17);
	bool Result265 = Result262 && Result264;
	int Constant287 = 0;
	bool Result266 = NiagaraAll(Context.Map.SpawnBurst_Instantaneous.SpawnCount == Constant287);
	float Constant288 = 0;
	float Result267 = Context.Map.SpawnBurst_Instantaneous.SpawnCount * Context.Map.Transient.ScalabilityEmitterSpawnCountScale * Context.Map.Engine.Peque.SpawnCountScale;
	float Constant289 = 1;
	float Result268 = max(Result267, Constant289);
	float float_IfResult8;
	if(Result266)
	{
	float_IfResult8 = Constant288;
	}
	else
	{
	float_IfResult8 = Result268;
	}
	float Constant290 = 0;
	NiagaraSpawnInfo Output18;
	Output18.Count = float_IfResult8;
	Output18.InterpStartDt = Result261;
	Output18.IntervalDt = Constant290;
	Output18.SpawnGroup = Context.Map.Constants.Peque.SpawnBurst_Instantaneous.SpawnGroup;
	int Constant291 = 0;
	float Constant292 = 0;
	float Constant293 = 0;
	NiagaraSpawnInfo Output19;
	Output19.Count = Constant291;
	Output19.InterpStartDt = Constant292;
	Output19.SpawnGroup = Context.Map.Constants.Peque.SpawnBurst_Instantaneous.SpawnGroup;
	Output19.IntervalDt = Constant293;
	NiagaraSpawnInfo SpawnInfo_IfResult2;
	if(Result265)
	{
	SpawnInfo_IfResult2 = Output18;
	}
	else
	{
	SpawnInfo_IfResult2 = Output19;
	}
	Context.Map.Peque.SpawnBurst_Instantaneous.SpawnBurst = SpawnInfo_IfResult2;
	bool Result269 = NiagaraAll(Context.Map.Peque.LoopedAge <= Context.Map.Constants.Peque.SpawnBurst_Instantaneous.SpawnTime);
	bool Result270 = Context.Map.Transient.SpawningbCanEverSpawn || Result269;
	Context.Map.Transient.SpawningbCanEverSpawn = Result270;
}

void UniformRangedFloat001_Peque_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context)
{
	bool Constant294 = false;
	Context.Map.UniformRangedFloat001.OverrideRandomness = Constant294;
	int Constant295 = 0;
	Context.Map.UniformRangedFloat001.RandomnessMode = Constant295;
	bool Constant296 = false;
	Context.Map.UniformRangedFloat001.OverrideSeed = Constant296;
	bool Constant297 = false;
	Context.Map.UniformRangedFloat001.FixedRandomSeed = Constant297;
	int Constant298 = 0;
	bool Constant299 = false;
	int Mode_IfResult14;
	bool Override_IfResult14;
	if(Context.Map.UniformRangedFloat001.OverrideRandomness)
	{
	Mode_IfResult14 = Context.Map.UniformRangedFloat001.RandomnessMode;
	Override_IfResult14 = Context.Map.UniformRangedFloat001.OverrideSeed;
	}
	else
	{
	Mode_IfResult14 = Constant298;
	Override_IfResult14 = Constant299;
	}
	float RandomRangeFloat_Func_Output_Result9;
	RandomRangeFloat_Func_(Context.Map.Constants.Peque.UniformRangedFloat001.Minimum, Context.Map.Constants.Peque.UniformRangedFloat001.Maximum, Context.Map.Constants.Peque.UniformRangedFloat001.RandomSeed, Mode_IfResult14, Override_IfResult14, Context.Map.UniformRangedFloat001.FixedRandomSeed, RandomRangeFloat_Func_Output_Result9, Context);
	Out_UniformRangedFloat = RandomRangeFloat_Func_Output_Result9;
}

void UniformRangedFloat002_Peque_Func_(out float Out_UniformRangedFloat, inout FSimulationContext Context)
{
	bool Constant300 = false;
	Context.Map.UniformRangedFloat002.OverrideRandomness = Constant300;
	int Constant301 = 0;
	Context.Map.UniformRangedFloat002.RandomnessMode = Constant301;
	bool Constant302 = false;
	Context.Map.UniformRangedFloat002.OverrideSeed = Constant302;
	bool Constant303 = false;
	Context.Map.UniformRangedFloat002.FixedRandomSeed = Constant303;
	int Constant304 = 0;
	bool Constant305 = false;
	int Mode_IfResult15;
	bool Override_IfResult15;
	if(Context.Map.UniformRangedFloat002.OverrideRandomness)
	{
	Mode_IfResult15 = Context.Map.UniformRangedFloat002.RandomnessMode;
	Override_IfResult15 = Context.Map.UniformRangedFloat002.OverrideSeed;
	}
	else
	{
	Mode_IfResult15 = Constant304;
	Override_IfResult15 = Constant305;
	}
	float RandomRangeFloat_Func_Output_Result10;
	RandomRangeFloat_Func_(Context.Map.Constants.Peque.UniformRangedFloat002.Minimum, Context.Map.Constants.Peque.UniformRangedFloat002.Maximum, Context.Map.Constants.Peque.UniformRangedFloat002.RandomSeed, Mode_IfResult15, Override_IfResult15, Context.Map.UniformRangedFloat002.FixedRandomSeed, RandomRangeFloat_Func_Output_Result10, Context);
	Out_UniformRangedFloat = RandomRangeFloat_Func_Output_Result10;
}

void RandomVector_NF_TransformVector_Peque_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context)
{
	bool Constant312 = true;
	float4x4 Matrix_IfResult7;
	float4x4 Matrix001_IfResult6;
	if(In_ApplyScale)
	{
	Matrix_IfResult7 = Context.Map.Engine.Owner.SystemLocalToWorld;
	Matrix001_IfResult6 = Context.Map.Engine.Owner.SystemWorldToLocal;
	}
	else
	{
	Matrix_IfResult7 = Context.Map.Engine.Owner.SystemLocalToWorldNoScale;
	Matrix001_IfResult6 = Context.Map.Engine.Owner.SystemWorldToLocalNoScale;
	}
	bool TransformBase_Func_Output_bUseOriginal6;
	float4x4 TransformBase_Func_Output_OutTransform6;
	TransformBase_Func_(In_SourceSpace, In_DestinationSpace, Matrix_IfResult7, Matrix001_IfResult6, Constant312, TransformBase_Func_Output_bUseOriginal6, TransformBase_Func_Output_OutTransform6, Context);
	float3 Result271 = mul(float4(In_InVector,0.0),TransformBase_Func_Output_OutTransform6).xyz;
	float3 Vector_IfResult16;
	if(TransformBase_Func_Output_bUseOriginal6)
	{
	Vector_IfResult16 = In_InVector;
	}
	else
	{
	Vector_IfResult16 = Result271;
	}
	Out_OutVector = Vector_IfResult16;
}

void RandomVector_Peque_Func_(out float3 Out_RandomVector, inout FSimulationContext Context)
{
	bool Constant308 = false;
	Context.Map.RandomVector.ConstraintoAxis = Constant308;
	int Constant309 = 2;
	int Constant310 = 0;
	bool Constant311 = false;
	float3 RandomVector_NF_TransformVector_Peque_Func_Output_OutVector;
	RandomVector_NF_TransformVector_Peque_Func_(Context.Map.Constants.Peque.RandomVector.ConstraintVector, Constant309, Constant310, Constant311, RandomVector_NF_TransformVector_Peque_Func_Output_OutVector, Context);
	bool Constant313 = false;
	Context.Map.RandomVector.OverrideRandomness = Constant313;
	int Constant314 = 0;
	Context.Map.RandomVector.RandomnessMode = Constant314;
	bool Constant315 = false;
	Context.Map.RandomVector.OverrideSeed = Constant315;
	bool Constant316 = false;
	Context.Map.RandomVector.FixedRandomSeed = Constant316;
	int Constant317 = 0;
	bool Constant318 = false;
	int Mode_IfResult16;
	bool Override_IfResult16;
	if(Context.Map.RandomVector.OverrideRandomness)
	{
	Mode_IfResult16 = Context.Map.RandomVector.RandomnessMode;
	Override_IfResult16 = Context.Map.RandomVector.OverrideSeed;
	}
	else
	{
	Mode_IfResult16 = Constant317;
	Override_IfResult16 = Constant318;
	}
	float3 RandomUnitVector_Func_Output_UnitVector3D4;
	float2 RandomUnitVector_Func_Output_UnitVector2D4;
	RandomUnitVector_Func_(Context.Map.Constants.Peque.RandomVector.RandomSeed, Mode_IfResult16, Override_IfResult16, Context.Map.RandomVector.FixedRandomSeed, RandomUnitVector_Func_Output_UnitVector3D4, RandomUnitVector_Func_Output_UnitVector2D4, Context);
	float Result272 = dot(RandomVector_NF_TransformVector_Peque_Func_Output_OutVector,RandomUnitVector_Func_Output_UnitVector3D4);
	float Result273 = sign(Result272);
	float3 Result274 = Result273 * RandomUnitVector_Func_Output_UnitVector3D4;
	float3 Vector_IfResult17;
	if(Context.Map.RandomVector.ConstraintoAxis)
	{
	Vector_IfResult17 = Result274;
	}
	else
	{
	Vector_IfResult17 = RandomUnitVector_Func_Output_UnitVector3D4;
	}
	float3 Result275 = Context.Map.RandomVector.VectorScale * Vector_IfResult17;
	Out_RandomVector = Result275;
}

void RandomVector001_NF_TransformVector_Peque_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context)
{
	bool Constant323 = true;
	float4x4 Matrix_IfResult8;
	float4x4 Matrix001_IfResult7;
	if(In_ApplyScale)
	{
	Matrix_IfResult8 = Context.Map.Engine.Owner.SystemLocalToWorld;
	Matrix001_IfResult7 = Context.Map.Engine.Owner.SystemWorldToLocal;
	}
	else
	{
	Matrix_IfResult8 = Context.Map.Engine.Owner.SystemLocalToWorldNoScale;
	Matrix001_IfResult7 = Context.Map.Engine.Owner.SystemWorldToLocalNoScale;
	}
	bool TransformBase_Func_Output_bUseOriginal7;
	float4x4 TransformBase_Func_Output_OutTransform7;
	TransformBase_Func_(In_SourceSpace, In_DestinationSpace, Matrix_IfResult8, Matrix001_IfResult7, Constant323, TransformBase_Func_Output_bUseOriginal7, TransformBase_Func_Output_OutTransform7, Context);
	float3 Result276 = mul(float4(In_InVector,0.0),TransformBase_Func_Output_OutTransform7).xyz;
	float3 Vector_IfResult18;
	if(TransformBase_Func_Output_bUseOriginal7)
	{
	Vector_IfResult18 = In_InVector;
	}
	else
	{
	Vector_IfResult18 = Result276;
	}
	Out_OutVector = Vector_IfResult18;
}

void RandomVector001_Peque_Func_(out float3 Out_RandomVector, inout FSimulationContext Context)
{
	bool Constant319 = false;
	Context.Map.RandomVector001.ConstraintoAxis = Constant319;
	int Constant320 = 2;
	int Constant321 = 0;
	bool Constant322 = false;
	float3 RandomVector001_NF_TransformVector_Peque_Func_Output_OutVector;
	RandomVector001_NF_TransformVector_Peque_Func_(Context.Map.Constants.Peque.RandomVector001.ConstraintVector, Constant320, Constant321, Constant322, RandomVector001_NF_TransformVector_Peque_Func_Output_OutVector, Context);
	bool Constant324 = false;
	Context.Map.RandomVector001.OverrideRandomness = Constant324;
	int Constant325 = 0;
	Context.Map.RandomVector001.RandomnessMode = Constant325;
	bool Constant326 = false;
	Context.Map.RandomVector001.OverrideSeed = Constant326;
	bool Constant327 = false;
	Context.Map.RandomVector001.FixedRandomSeed = Constant327;
	int Constant328 = 0;
	bool Constant329 = false;
	int Mode_IfResult17;
	bool Override_IfResult17;
	if(Context.Map.RandomVector001.OverrideRandomness)
	{
	Mode_IfResult17 = Context.Map.RandomVector001.RandomnessMode;
	Override_IfResult17 = Context.Map.RandomVector001.OverrideSeed;
	}
	else
	{
	Mode_IfResult17 = Constant328;
	Override_IfResult17 = Constant329;
	}
	float3 RandomUnitVector_Func_Output_UnitVector3D5;
	float2 RandomUnitVector_Func_Output_UnitVector2D5;
	RandomUnitVector_Func_(Context.Map.Constants.Peque.RandomVector001.RandomSeed, Mode_IfResult17, Override_IfResult17, Context.Map.RandomVector001.FixedRandomSeed, RandomUnitVector_Func_Output_UnitVector3D5, RandomUnitVector_Func_Output_UnitVector2D5, Context);
	float Result277 = dot(RandomVector001_NF_TransformVector_Peque_Func_Output_OutVector,RandomUnitVector_Func_Output_UnitVector3D5);
	float Result278 = sign(Result277);
	float3 Result279 = Result278 * RandomUnitVector_Func_Output_UnitVector3D5;
	float3 Vector_IfResult19;
	if(Context.Map.RandomVector001.ConstraintoAxis)
	{
	Vector_IfResult19 = Result279;
	}
	else
	{
	Vector_IfResult19 = RandomUnitVector_Func_Output_UnitVector3D5;
	}
	float3 Result280 = Context.Map.RandomVector001.VectorScale * Vector_IfResult19;
	Out_RandomVector = Result280;
}

void UniformRangedVector_Peque_Func_(out float3 Out_UniformRangedVector, inout FSimulationContext Context)
{
	bool Constant330 = false;
	Context.Map.UniformRangedVector.OverrideRandomness = Constant330;
	int Constant331 = 0;
	Context.Map.UniformRangedVector.RandomnessMode = Constant331;
	bool Constant332 = false;
	Context.Map.UniformRangedVector.OverrideSeed = Constant332;
	bool Constant333 = false;
	Context.Map.UniformRangedVector.FixedRandomSeed = Constant333;
	int Constant334 = 0;
	bool Constant335 = false;
	int Mode_IfResult18;
	bool Override_IfResult18;
	if(Context.Map.UniformRangedVector.OverrideRandomness)
	{
	Mode_IfResult18 = Context.Map.UniformRangedVector.RandomnessMode;
	Override_IfResult18 = Context.Map.UniformRangedVector.OverrideSeed;
	}
	else
	{
	Mode_IfResult18 = Constant334;
	Override_IfResult18 = Constant335;
	}
	float3 RandomRangeFloat_Func_Output_Result11;
	RandomRangeFloat_Func_(Context.Map.Constants.Peque.UniformRangedVector.Minimum, Context.Map.Constants.Peque.UniformRangedVector.Maximum, Context.Map.Constants.Peque.UniformRangedVector.RandomSeed, Mode_IfResult18, Override_IfResult18, Context.Map.UniformRangedVector.FixedRandomSeed, RandomRangeFloat_Func_Output_Result11, Context);
	Out_UniformRangedVector = RandomRangeFloat_Func_Output_Result11;
}

void BeamEmitterSetup_NF_TransformVector_Peque_Func_(float3 In_InVector, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, out float3 Out_OutVector, inout FSimulationContext Context)
{
	bool Constant342 = true;
	float4x4 Matrix_IfResult9;
	float4x4 Matrix001_IfResult8;
	if(In_ApplyScale)
	{
	Matrix_IfResult9 = Context.Map.Engine.Owner.SystemLocalToWorld;
	Matrix001_IfResult8 = Context.Map.Engine.Owner.SystemWorldToLocal;
	}
	else
	{
	Matrix_IfResult9 = Context.Map.Engine.Owner.SystemLocalToWorldNoScale;
	Matrix001_IfResult8 = Context.Map.Engine.Owner.SystemWorldToLocalNoScale;
	}
	bool TransformBase_Func_Output_bUseOriginal8;
	float4x4 TransformBase_Func_Output_OutTransform8;
	TransformBase_Func_(In_SourceSpace, In_DestinationSpace, Matrix_IfResult9, Matrix001_IfResult8, Constant342, TransformBase_Func_Output_bUseOriginal8, TransformBase_Func_Output_OutTransform8, Context);
	float3 Result282 = mul(float4(In_InVector,0.0),TransformBase_Func_Output_OutTransform8).xyz;
	float3 Vector_IfResult20;
	if(TransformBase_Func_Output_bUseOriginal8)
	{
	Vector_IfResult20 = In_InVector;
	}
	else
	{
	Vector_IfResult20 = Result282;
	}
	Out_OutVector = Vector_IfResult20;
}

void BeamEmitterSetup_Peque_Func_(inout FSimulationContext Context)
{
	float3 Result281 = Context.Map.BeamEmitterSetup.BeamStart - Context.Map.BeamEmitterSetup.BeamEnd;
	float3 Constant336 = float3(0,0,1);
	float Constant337 = 1e-05;
	float Constant338 = 1;
	float3 DirectionAndLengthSafe_Func_Output_Direction4;
	float DirectionAndLengthSafe_Func_Output_Length4;
	bool DirectionAndLengthSafe_Func_Output_BelowThreshold4;
	DirectionAndLengthSafe_Func_(Result281, Constant336, Constant337, Constant338, DirectionAndLengthSafe_Func_Output_Direction4, DirectionAndLengthSafe_Func_Output_Length4, DirectionAndLengthSafe_Func_Output_BelowThreshold4, Context);
	int Constant339 = 2;
	int Constant340 = 0;
	bool Constant341 = false;
	float3 BeamEmitterSetup_NF_TransformVector_Peque_Func_Output_OutVector;
	BeamEmitterSetup_NF_TransformVector_Peque_Func_(Context.Map.BeamEmitterSetup.BeamEnd, Constant339, Constant340, Constant341, BeamEmitterSetup_NF_TransformVector_Peque_Func_Output_OutVector, Context);
	float3 Result283 = Context.Map.BeamEmitterSetup.BeamStart + BeamEmitterSetup_NF_TransformVector_Peque_Func_Output_OutVector;
	Context.Map.Local.BeamEmitterSetup.BeamStart = Context.Map.BeamEmitterSetup.BeamStart;
	Context.Map.Local.BeamEmitterSetup.BeamStartEndLength = DirectionAndLengthSafe_Func_Output_Length4;
	Context.Map.Local.BeamEmitterSetup.BeamEnd = Result283;
	bool Constant343 = false;
	Context.Map.BeamEmitterSetup.AbsoluteStartTangent = Constant343;
	float3 Result284 = Context.Map.BeamEmitterSetup.BeamStartTangent * Context.Map.Local.BeamEmitterSetup.BeamStartEndLength;
	float3 Result285 = Context.Map.Local.BeamEmitterSetup.BeamStart + Result284;
	float3 Vector_IfResult21;
	if(Context.Map.BeamEmitterSetup.AbsoluteStartTangent)
	{
	Vector_IfResult21 = Context.Map.BeamEmitterSetup.BeamStartTangent;
	}
	else
	{
	Vector_IfResult21 = Result285;
	}
	bool Constant344 = false;
	Context.Map.BeamEmitterSetup.AbsoluteEndTangent = Constant344;
	float3 Result286 = Context.Map.Local.BeamEmitterSetup.BeamStartEndLength * Context.Map.BeamEmitterSetup.BeamEndTangent;
	float3 Result287 = Result286 + Context.Map.Local.BeamEmitterSetup.BeamEnd;
	float3 Vector_IfResult22;
	if(Context.Map.BeamEmitterSetup.AbsoluteEndTangent)
	{
	Vector_IfResult22 = Context.Map.BeamEmitterSetup.BeamEndTangent;
	}
	else
	{
	Vector_IfResult22 = Result287;
	}
	Context.Map.Local.BeamEmitterSetup.BeamStartTangent = Vector_IfResult21;
	Context.Map.Local.BeamEmitterSetup.BeamEndTangent = Vector_IfResult22;
	float3 Result288 = Context.Map.Local.BeamEmitterSetup.BeamEnd - Context.Map.Local.BeamEmitterSetup.BeamStart;
	float3 Constant345 = float3(0,0,1);
	float Constant346 = 1e-05;
	float Constant347 = 1;
	float3 DirectionAndLengthSafe_Func_Output_Direction5;
	float DirectionAndLengthSafe_Func_Output_Length5;
	bool DirectionAndLengthSafe_Func_Output_BelowThreshold5;
	DirectionAndLengthSafe_Func_(Result288, Constant345, Constant346, Constant347, DirectionAndLengthSafe_Func_Output_Direction5, DirectionAndLengthSafe_Func_Output_Length5, DirectionAndLengthSafe_Func_Output_BelowThreshold5, Context);
	Context.Map.Peque.BeamStart = Context.Map.Local.BeamEmitterSetup.BeamStart;
	Context.Map.Peque.BeamStartTangent = Context.Map.Local.BeamEmitterSetup.BeamStartTangent;
	Context.Map.Peque.BeamEnd = Context.Map.Local.BeamEmitterSetup.BeamEnd;
	Context.Map.Peque.BeamEndTangent = Context.Map.Local.BeamEmitterSetup.BeamEndTangent;
	Context.Map.Peque.UseBeamTangents = Context.Map.BeamEmitterSetup.UseBeamTangents;
	Context.Map.Peque.BeamStartEndLength = Context.Map.Local.BeamEmitterSetup.BeamStartEndLength;
	Context.Map.Peque.BeamVector = Result288;
	Context.Map.Peque.BeamDirection = DirectionAndLengthSafe_Func_Output_Direction5;
	bool Result289 = NiagaraAll(Context.Map.Peque.LoopCount > Context.Map.Peque.BeamID);
	int Constant348 = -1;
	int int32_IfResult2;
	if(Result289)
	{
	int32_IfResult2 = Context.Map.Peque.LoopCount;
	}
	else
	{
	int32_IfResult2 = Constant348;
	}
	Context.Map.Peque.BeamID = int32_IfResult2;
}

void Peque_Func_(inout FSimulationContext Context)
{
	EnterStatScope(11 );
	EmitterState_Peque_Func_(Context);
	ExitStatScope( );
	int UniformRangedInt_Peque_Func_Output_UniformRangedInt;
	UniformRangedInt_Peque_Func_(UniformRangedInt_Peque_Func_Output_UniformRangedInt, Context);
	Context.Map.SpawnBurst_Instantaneous.SpawnCount = UniformRangedInt_Peque_Func_Output_UniformRangedInt;
	EnterStatScope(12 );
	SpawnBurst_Instantaneous_Peque_Func_(Context);
	ExitStatScope( );
	float UniformRangedFloat001_Peque_Func_Output_UniformRangedFloat;
	UniformRangedFloat001_Peque_Func_(UniformRangedFloat001_Peque_Func_Output_UniformRangedFloat, Context);
	float UniformRangedFloat002_Peque_Func_Output_UniformRangedFloat;
	UniformRangedFloat002_Peque_Func_(UniformRangedFloat002_Peque_Func_Output_UniformRangedFloat, Context);
	Context.Map.RandomVector.VectorScale = UniformRangedFloat001_Peque_Func_Output_UniformRangedFloat;
	Context.Map.RandomVector001.VectorScale = UniformRangedFloat002_Peque_Func_Output_UniformRangedFloat;
	float3 Constant306 = float3(0,0,0);
	bool Constant307 = true;
	float3 RandomVector_Peque_Func_Output_RandomVector;
	RandomVector_Peque_Func_(RandomVector_Peque_Func_Output_RandomVector, Context);
	float3 RandomVector001_Peque_Func_Output_RandomVector;
	RandomVector001_Peque_Func_(RandomVector001_Peque_Func_Output_RandomVector, Context);
	float3 UniformRangedVector_Peque_Func_Output_UniformRangedVector;
	UniformRangedVector_Peque_Func_(UniformRangedVector_Peque_Func_Output_UniformRangedVector, Context);
	Context.Map.BeamEmitterSetup.BeamStart = Constant306;
	Context.Map.BeamEmitterSetup.UseBeamTangents = Constant307;
	Context.Map.BeamEmitterSetup.BeamStartTangent = RandomVector_Peque_Func_Output_RandomVector;
	Context.Map.BeamEmitterSetup.BeamEndTangent = RandomVector001_Peque_Func_Output_RandomVector;
	Context.Map.BeamEmitterSetup.BeamEnd = UniformRangedVector_Peque_Func_Output_UniformRangedVector;
	EnterStatScope(13 );
	BeamEmitterSetup_Peque_Func_(Context);
	ExitStatScope( );
}

float GetSpawnInterpolation()
{
	return 1.0f;}


void ReadDataSets(inout FSimulationContext Context)
{
}

void WriteDataSets(inout FSimulationContext Context)
{
}

void Simulate(inout FSimulationContext Context)
{
	EnterStatScope(0 );


	bool Constant = (false);
	Context.Map.Local.SystemState.LoopCountIncreased = Constant;
	bool Constant1 = false;
	Context.Map.SystemState.RecalculateDurationEachLoop = Constant1;
	int Constant2 = 0;
	Context.Map.Transient.ScalabilityExecutionState = Constant2;
	EnterStatScope(1 );
	SystemState_Func_(Context);
	ExitStatScope( );
	EnterStatScope(2 );
	Empty004_Func_(Context);
	ExitStatScope( );
	EnterStatScope(6 );
	Grande_Func_(Context);
	ExitStatScope( );
	EnterStatScope(10 );
	Peque_Func_(Context);
	ExitStatScope( );
	ExitStatScope( );
}
void SimulateMain()
{
EnterStatScope(14 );

	FSimulationContext Context = (FSimulationContext)0;
	Context.Map.Emitter.RandomSeed = InputDataInt(0, 0);
	Context.Map.Empty004.Age = InputDataFloat(0, 1);
	Context.Map.Empty004.BeamDirection.x = InputDataFloat(0, 2);
	Context.Map.Empty004.BeamDirection.y = InputDataFloat(0, 3);
	Context.Map.Empty004.BeamDirection.z = InputDataFloat(0, 4);
	Context.Map.Empty004.BeamEnd.x = InputDataFloat(0, 5);
	Context.Map.Empty004.BeamEnd.y = InputDataFloat(0, 6);
	Context.Map.Empty004.BeamEnd.z = InputDataFloat(0, 7);
	Context.Map.Empty004.BeamEndTangent.x = InputDataFloat(0, 8);
	Context.Map.Empty004.BeamEndTangent.y = InputDataFloat(0, 9);
	Context.Map.Empty004.BeamEndTangent.z = InputDataFloat(0, 10);
	Context.Map.Empty004.BeamID = InputDataInt(0, 11);
	Context.Map.Empty004.BeamStart.x = InputDataFloat(0, 12);
	Context.Map.Empty004.BeamStart.y = InputDataFloat(0, 13);
	Context.Map.Empty004.BeamStart.z = InputDataFloat(0, 14);
	Context.Map.Empty004.BeamStartEndLength = InputDataFloat(0, 15);
	Context.Map.Empty004.BeamStartTangent.x = InputDataFloat(0, 16);
	Context.Map.Empty004.BeamStartTangent.y = InputDataFloat(0, 17);
	Context.Map.Empty004.BeamStartTangent.z = InputDataFloat(0, 18);
	Context.Map.Empty004.BeamVector.x = InputDataFloat(0, 19);
	Context.Map.Empty004.BeamVector.y = InputDataFloat(0, 20);
	Context.Map.Empty004.BeamVector.z = InputDataFloat(0, 21);
	Context.Map.Empty004.CurrentLoopDuration = InputDataFloat(0, 22);
	Context.Map.Empty004.ExecutionState = InputDataInt(0, 23);
	Context.Map.Empty004.ExecutionStateSource = InputDataInt(0, 24);
	Context.Map.Empty004.LocalSpace = InputDataBool(0, 25);
	Context.Map.Empty004.LoopCount = InputDataInt(0, 26);
	Context.Map.Empty004.LoopedAge = InputDataFloat(0, 27);
	Context.Map.Empty004.NormalizedLoopAge = InputDataFloat(0, 28);
	Context.Map.Empty004.Scalability.DistanceFraction = InputDataFloat(0, 29);
	Context.Map.Empty004.SpawnBurst_Instantaneous.SpawnBurst.Count = 0;
	Context.Map.Empty004.SpawnBurst_Instantaneous.SpawnBurst.InterpStartDt = 0.0f;
	Context.Map.Empty004.SpawnBurst_Instantaneous.SpawnBurst.IntervalDt = 0.0f;
	Context.Map.Empty004.SpawnBurst_Instantaneous.SpawnBurst.SpawnGroup = 0;
	Context.Map.Empty004.UseBeamTangents = InputDataBool(0, 34);
	Context.Map.Grande.Age = InputDataFloat(0, 35);
	Context.Map.Grande.BeamDirection.x = InputDataFloat(0, 36);
	Context.Map.Grande.BeamDirection.y = InputDataFloat(0, 37);
	Context.Map.Grande.BeamDirection.z = InputDataFloat(0, 38);
	Context.Map.Grande.BeamEnd.x = InputDataFloat(0, 39);
	Context.Map.Grande.BeamEnd.y = InputDataFloat(0, 40);
	Context.Map.Grande.BeamEnd.z = InputDataFloat(0, 41);
	Context.Map.Grande.BeamEndTangent.x = InputDataFloat(0, 42);
	Context.Map.Grande.BeamEndTangent.y = InputDataFloat(0, 43);
	Context.Map.Grande.BeamEndTangent.z = InputDataFloat(0, 44);
	Context.Map.Grande.BeamID = InputDataInt(0, 45);
	Context.Map.Grande.BeamStart.x = InputDataFloat(0, 46);
	Context.Map.Grande.BeamStart.y = InputDataFloat(0, 47);
	Context.Map.Grande.BeamStart.z = InputDataFloat(0, 48);
	Context.Map.Grande.BeamStartEndLength = InputDataFloat(0, 49);
	Context.Map.Grande.BeamStartTangent.x = InputDataFloat(0, 50);
	Context.Map.Grande.BeamStartTangent.y = InputDataFloat(0, 51);
	Context.Map.Grande.BeamStartTangent.z = InputDataFloat(0, 52);
	Context.Map.Grande.BeamVector.x = InputDataFloat(0, 53);
	Context.Map.Grande.BeamVector.y = InputDataFloat(0, 54);
	Context.Map.Grande.BeamVector.z = InputDataFloat(0, 55);
	Context.Map.Grande.CurrentLoopDuration = InputDataFloat(0, 56);
	Context.Map.Grande.ExecutionState = InputDataInt(0, 57);
	Context.Map.Grande.ExecutionStateSource = InputDataInt(0, 58);
	Context.Map.Grande.LocalSpace = InputDataBool(0, 59);
	Context.Map.Grande.LoopCount = InputDataInt(0, 60);
	Context.Map.Grande.LoopedAge = InputDataFloat(0, 61);
	Context.Map.Grande.NormalizedLoopAge = InputDataFloat(0, 62);
	Context.Map.Grande.Scalability.DistanceFraction = InputDataFloat(0, 63);
	Context.Map.Grande.SpawnBurst_Instantaneous.SpawnBurst.Count = 0;
	Context.Map.Grande.SpawnBurst_Instantaneous.SpawnBurst.InterpStartDt = 0.0f;
	Context.Map.Grande.SpawnBurst_Instantaneous.SpawnBurst.IntervalDt = 0.0f;
	Context.Map.Grande.SpawnBurst_Instantaneous.SpawnBurst.SpawnGroup = 0;
	Context.Map.Grande.UseBeamTangents = InputDataBool(0, 68);
	Context.Map.Peque.Age = InputDataFloat(0, 69);
	Context.Map.Peque.BeamDirection.x = InputDataFloat(0, 70);
	Context.Map.Peque.BeamDirection.y = InputDataFloat(0, 71);
	Context.Map.Peque.BeamDirection.z = InputDataFloat(0, 72);
	Context.Map.Peque.BeamEnd.x = InputDataFloat(0, 73);
	Context.Map.Peque.BeamEnd.y = InputDataFloat(0, 74);
	Context.Map.Peque.BeamEnd.z = InputDataFloat(0, 75);
	Context.Map.Peque.BeamEndTangent.x = InputDataFloat(0, 76);
	Context.Map.Peque.BeamEndTangent.y = InputDataFloat(0, 77);
	Context.Map.Peque.BeamEndTangent.z = InputDataFloat(0, 78);
	Context.Map.Peque.BeamID = InputDataInt(0, 79);
	Context.Map.Peque.BeamStart.x = InputDataFloat(0, 80);
	Context.Map.Peque.BeamStart.y = InputDataFloat(0, 81);
	Context.Map.Peque.BeamStart.z = InputDataFloat(0, 82);
	Context.Map.Peque.BeamStartEndLength = InputDataFloat(0, 83);
	Context.Map.Peque.BeamStartTangent.x = InputDataFloat(0, 84);
	Context.Map.Peque.BeamStartTangent.y = InputDataFloat(0, 85);
	Context.Map.Peque.BeamStartTangent.z = InputDataFloat(0, 86);
	Context.Map.Peque.BeamVector.x = InputDataFloat(0, 87);
	Context.Map.Peque.BeamVector.y = InputDataFloat(0, 88);
	Context.Map.Peque.BeamVector.z = InputDataFloat(0, 89);
	Context.Map.Peque.CurrentLoopDuration = InputDataFloat(0, 90);
	Context.Map.Peque.ExecutionState = InputDataInt(0, 91);
	Context.Map.Peque.ExecutionStateSource = InputDataInt(0, 92);
	Context.Map.Peque.LocalSpace = InputDataBool(0, 93);
	Context.Map.Peque.LoopCount = InputDataInt(0, 94);
	Context.Map.Peque.LoopedAge = InputDataFloat(0, 95);
	Context.Map.Peque.NormalizedLoopAge = InputDataFloat(0, 96);
	Context.Map.Peque.Scalability.DistanceFraction = InputDataFloat(0, 97);
	Context.Map.Peque.SpawnBurst_Instantaneous.SpawnBurst.Count = 0;
	Context.Map.Peque.SpawnBurst_Instantaneous.SpawnBurst.InterpStartDt = 0.0f;
	Context.Map.Peque.SpawnBurst_Instantaneous.SpawnBurst.IntervalDt = 0.0f;
	Context.Map.Peque.SpawnBurst_Instantaneous.SpawnBurst.SpawnGroup = 0;
	Context.Map.Peque.UseBeamTangents = InputDataBool(0, 102);
	Context.Map.System.Age = InputDataFloat(0, 103);
	Context.Map.System.bCompleteOnInactive = InputDataBool(0, 104);
	Context.Map.System.CurrentLoopDuration = InputDataFloat(0, 105);
	Context.Map.System.ExecutionState = InputDataInt(0, 106);
	Context.Map.System.ExecutionStateSource = InputDataInt(0, 107);
	Context.Map.System.LoopCount = InputDataInt(0, 108);
	Context.Map.System.LoopedAge = InputDataFloat(0, 109);
	Context.Map.System.NormalizedLoopAge = InputDataFloat(0, 110);
	Context.Map.Engine.Emitter.TotalSpawnedParticles = InputDataInt(1, 0);
	Context.Map.Engine.Empty004.NumParticles = InputDataInt(1, 1);
	Context.Map.Engine.Empty004.SpawnCountScale = InputDataFloat(1, 2);
	Context.Map.Engine.Grande.NumParticles = InputDataInt(1, 3);
	Context.Map.Engine.Grande.SpawnCountScale = InputDataFloat(1, 4);
	Context.Map.Engine.Owner.ExecutionState = InputDataInt(1, 5);
	Context.Map.Engine.Owner.LODDistanceFraction = InputDataFloat(1, 6);
	Context.Map.Engine.Owner.SystemLocalToWorld[0][0] = InputDataFloat(1, 7);
	Context.Map.Engine.Owner.SystemLocalToWorld[0][1] = InputDataFloat(1, 8);
	Context.Map.Engine.Owner.SystemLocalToWorld[0][2] = InputDataFloat(1, 9);
	Context.Map.Engine.Owner.SystemLocalToWorld[0][3] = InputDataFloat(1, 10);
	Context.Map.Engine.Owner.SystemLocalToWorld[1][0] = InputDataFloat(1, 11);
	Context.Map.Engine.Owner.SystemLocalToWorld[1][1] = InputDataFloat(1, 12);
	Context.Map.Engine.Owner.SystemLocalToWorld[1][2] = InputDataFloat(1, 13);
	Context.Map.Engine.Owner.SystemLocalToWorld[1][3] = InputDataFloat(1, 14);
	Context.Map.Engine.Owner.SystemLocalToWorld[2][0] = InputDataFloat(1, 15);
	Context.Map.Engine.Owner.SystemLocalToWorld[2][1] = InputDataFloat(1, 16);
	Context.Map.Engine.Owner.SystemLocalToWorld[2][2] = InputDataFloat(1, 17);
	Context.Map.Engine.Owner.SystemLocalToWorld[2][3] = InputDataFloat(1, 18);
	Context.Map.Engine.Owner.SystemLocalToWorld[3][0] = InputDataFloat(1, 19);
	Context.Map.Engine.Owner.SystemLocalToWorld[3][1] = InputDataFloat(1, 20);
	Context.Map.Engine.Owner.SystemLocalToWorld[3][2] = InputDataFloat(1, 21);
	Context.Map.Engine.Owner.SystemLocalToWorld[3][3] = InputDataFloat(1, 22);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[0][0] = InputDataFloat(1, 23);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[0][1] = InputDataFloat(1, 24);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[0][2] = InputDataFloat(1, 25);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[0][3] = InputDataFloat(1, 26);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[1][0] = InputDataFloat(1, 27);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[1][1] = InputDataFloat(1, 28);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[1][2] = InputDataFloat(1, 29);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[1][3] = InputDataFloat(1, 30);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[2][0] = InputDataFloat(1, 31);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[2][1] = InputDataFloat(1, 32);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[2][2] = InputDataFloat(1, 33);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[2][3] = InputDataFloat(1, 34);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[3][0] = InputDataFloat(1, 35);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[3][1] = InputDataFloat(1, 36);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[3][2] = InputDataFloat(1, 37);
	Context.Map.Engine.Owner.SystemLocalToWorldNoScale[3][3] = InputDataFloat(1, 38);
	Context.Map.Engine.Owner.SystemWorldToLocal[0][0] = InputDataFloat(1, 39);
	Context.Map.Engine.Owner.SystemWorldToLocal[0][1] = InputDataFloat(1, 40);
	Context.Map.Engine.Owner.SystemWorldToLocal[0][2] = InputDataFloat(1, 41);
	Context.Map.Engine.Owner.SystemWorldToLocal[0][3] = InputDataFloat(1, 42);
	Context.Map.Engine.Owner.SystemWorldToLocal[1][0] = InputDataFloat(1, 43);
	Context.Map.Engine.Owner.SystemWorldToLocal[1][1] = InputDataFloat(1, 44);
	Context.Map.Engine.Owner.SystemWorldToLocal[1][2] = InputDataFloat(1, 45);
	Context.Map.Engine.Owner.SystemWorldToLocal[1][3] = InputDataFloat(1, 46);
	Context.Map.Engine.Owner.SystemWorldToLocal[2][0] = InputDataFloat(1, 47);
	Context.Map.Engine.Owner.SystemWorldToLocal[2][1] = InputDataFloat(1, 48);
	Context.Map.Engine.Owner.SystemWorldToLocal[2][2] = InputDataFloat(1, 49);
	Context.Map.Engine.Owner.SystemWorldToLocal[2][3] = InputDataFloat(1, 50);
	Context.Map.Engine.Owner.SystemWorldToLocal[3][0] = InputDataFloat(1, 51);
	Context.Map.Engine.Owner.SystemWorldToLocal[3][1] = InputDataFloat(1, 52);
	Context.Map.Engine.Owner.SystemWorldToLocal[3][2] = InputDataFloat(1, 53);
	Context.Map.Engine.Owner.SystemWorldToLocal[3][3] = InputDataFloat(1, 54);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[0][0] = InputDataFloat(1, 55);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[0][1] = InputDataFloat(1, 56);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[0][2] = InputDataFloat(1, 57);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[0][3] = InputDataFloat(1, 58);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[1][0] = InputDataFloat(1, 59);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[1][1] = InputDataFloat(1, 60);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[1][2] = InputDataFloat(1, 61);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[1][3] = InputDataFloat(1, 62);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[2][0] = InputDataFloat(1, 63);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[2][1] = InputDataFloat(1, 64);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[2][2] = InputDataFloat(1, 65);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[2][3] = InputDataFloat(1, 66);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[3][0] = InputDataFloat(1, 67);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[3][1] = InputDataFloat(1, 68);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[3][2] = InputDataFloat(1, 69);
	Context.Map.Engine.Owner.SystemWorldToLocalNoScale[3][3] = InputDataFloat(1, 70);
	Context.Map.Engine.Peque.NumParticles = InputDataInt(1, 71);
	Context.Map.Engine.Peque.SpawnCountScale = InputDataFloat(1, 72);
	Context.Map.Engine.System.TickCount = InputDataInt(1, 73);
	Context.Map.User.Empty004.RandomSeed = InputDataInt(1, 74);
	Context.Map.Constants.SystemState.LoopDelay = Constants_SystemState_LoopDelay;
	Context.Map.Constants.SystemState.LoopDuration = Constants_SystemState_LoopDuration;
	Context.Map.Engine.DeltaTime = Engine_DeltaTime;
	Context.Map.Constants.Empty004.EmitterState.LoopDuration = Constants_Empty004_EmitterState_LoopDuration;
	Context.Map.Constants.Empty004.EmitterState.LoopDelay = Constants_Empty004_EmitterState_LoopDelay;
	Context.Map.Constants.Empty004.UniformRangedInt.Minimum = Constants_Empty004_UniformRangedInt_Minimum;
	Context.Map.Constants.Empty004.UniformRangedInt.Maximum = Constants_Empty004_UniformRangedInt_Maximum;
	Context.Map.Constants.Empty004.UniformRangedInt.RandomSeed = Constants_Empty004_UniformRangedInt_RandomSeed;
	Context.Map.Constants.Empty004.SpawnBurst_Instantaneous.SpawnTime = Constants_Empty004_SpawnBurst_Instantaneous_SpawnTime;
	Context.Map.Constants.Empty004.SpawnBurst_Instantaneous.SpawnGroup = Constants_Empty004_SpawnBurst_Instantaneous_SpawnGroup;
	Context.Map.Constants.Empty004.SpawnBurst_Instantaneous.SpawnProbability = Constants_Empty004_SpawnBurst_Instantaneous_SpawnProbability;
	Context.Map.Constants.Empty004.UniformRangedFloat001.Minimum = Constants_Empty004_UniformRangedFloat001_Minimum;
	Context.Map.Constants.Empty004.UniformRangedFloat001.Maximum = Constants_Empty004_UniformRangedFloat001_Maximum;
	Context.Map.Constants.Empty004.UniformRangedFloat001.RandomSeed = Constants_Empty004_UniformRangedFloat001_RandomSeed;
	Context.Map.Constants.Empty004.UniformRangedFloat002.Minimum = Constants_Empty004_UniformRangedFloat002_Minimum;
	Context.Map.Constants.Empty004.UniformRangedFloat002.Maximum = Constants_Empty004_UniformRangedFloat002_Maximum;
	Context.Map.Constants.Empty004.UniformRangedFloat002.RandomSeed = Constants_Empty004_UniformRangedFloat002_RandomSeed;
	Context.Map.Constants.Empty004.UniformRangedVector001.Minimum = Constants_Empty004_UniformRangedVector001_Minimum;
	Context.Map.Constants.Empty004.UniformRangedVector001.Maximum = Constants_Empty004_UniformRangedVector001_Maximum;
	Context.Map.Constants.Empty004.UniformRangedVector001.RandomSeed = Constants_Empty004_UniformRangedVector001_RandomSeed;
	Context.Map.Constants.Empty004.RandomVector.ConstraintVector = Constants_Empty004_RandomVector_ConstraintVector;
	Context.Map.Constants.Empty004.RandomVector.RandomSeed = Constants_Empty004_RandomVector_RandomSeed;
	Context.Map.Constants.Empty004.RandomVector001.ConstraintVector = Constants_Empty004_RandomVector001_ConstraintVector;
	Context.Map.Constants.Empty004.RandomVector001.RandomSeed = Constants_Empty004_RandomVector001_RandomSeed;
	Context.Map.Constants.Empty004.UniformRangedVector.Minimum = Constants_Empty004_UniformRangedVector_Minimum;
	Context.Map.Constants.Empty004.UniformRangedVector.Maximum = Constants_Empty004_UniformRangedVector_Maximum;
	Context.Map.Constants.Empty004.UniformRangedVector.RandomSeed = Constants_Empty004_UniformRangedVector_RandomSeed;
	Context.Map.Constants.Grande.EmitterState.LoopDuration = Constants_Grande_EmitterState_LoopDuration;
	Context.Map.Constants.Grande.EmitterState.LoopDelay = Constants_Grande_EmitterState_LoopDelay;
	Context.Map.Constants.Grande.UniformRangedInt.Minimum = Constants_Grande_UniformRangedInt_Minimum;
	Context.Map.Constants.Grande.UniformRangedInt.Maximum = Constants_Grande_UniformRangedInt_Maximum;
	Context.Map.Constants.Grande.UniformRangedInt.RandomSeed = Constants_Grande_UniformRangedInt_RandomSeed;
	Context.Map.Constants.Grande.SpawnBurst_Instantaneous.SpawnTime = Constants_Grande_SpawnBurst_Instantaneous_SpawnTime;
	Context.Map.Constants.Grande.SpawnBurst_Instantaneous.SpawnGroup = Constants_Grande_SpawnBurst_Instantaneous_SpawnGroup;
	Context.Map.Constants.Grande.SpawnBurst_Instantaneous.SpawnProbability = Constants_Grande_SpawnBurst_Instantaneous_SpawnProbability;
	Context.Map.Constants.Grande.UniformRangedFloat001.Minimum = Constants_Grande_UniformRangedFloat001_Minimum;
	Context.Map.Constants.Grande.UniformRangedFloat001.Maximum = Constants_Grande_UniformRangedFloat001_Maximum;
	Context.Map.Constants.Grande.UniformRangedFloat001.RandomSeed = Constants_Grande_UniformRangedFloat001_RandomSeed;
	Context.Map.Constants.Grande.UniformRangedFloat002.Minimum = Constants_Grande_UniformRangedFloat002_Minimum;
	Context.Map.Constants.Grande.UniformRangedFloat002.Maximum = Constants_Grande_UniformRangedFloat002_Maximum;
	Context.Map.Constants.Grande.UniformRangedFloat002.RandomSeed = Constants_Grande_UniformRangedFloat002_RandomSeed;
	Context.Map.Constants.Grande.RandomVector.ConstraintVector = Constants_Grande_RandomVector_ConstraintVector;
	Context.Map.Constants.Grande.RandomVector.RandomSeed = Constants_Grande_RandomVector_RandomSeed;
	Context.Map.Constants.Grande.RandomVector001.ConstraintVector = Constants_Grande_RandomVector001_ConstraintVector;
	Context.Map.Constants.Grande.RandomVector001.RandomSeed = Constants_Grande_RandomVector001_RandomSeed;
	Context.Map.Constants.Grande.UniformRangedVector.Minimum = Constants_Grande_UniformRangedVector_Minimum;
	Context.Map.Constants.Grande.UniformRangedVector.Maximum = Constants_Grande_UniformRangedVector_Maximum;
	Context.Map.Constants.Grande.UniformRangedVector.RandomSeed = Constants_Grande_UniformRangedVector_RandomSeed;
	Context.Map.Constants.Peque.EmitterState.LoopDuration = Constants_Peque_EmitterState_LoopDuration;
	Context.Map.Constants.Peque.EmitterState.LoopDelay = Constants_Peque_EmitterState_LoopDelay;
	Context.Map.Constants.Peque.UniformRangedInt.Minimum = Constants_Peque_UniformRangedInt_Minimum;
	Context.Map.Constants.Peque.UniformRangedInt.Maximum = Constants_Peque_UniformRangedInt_Maximum;
	Context.Map.Constants.Peque.UniformRangedInt.RandomSeed = Constants_Peque_UniformRangedInt_RandomSeed;
	Context.Map.Constants.Peque.SpawnBurst_Instantaneous.SpawnTime = Constants_Peque_SpawnBurst_Instantaneous_SpawnTime;
	Context.Map.Constants.Peque.SpawnBurst_Instantaneous.SpawnGroup = Constants_Peque_SpawnBurst_Instantaneous_SpawnGroup;
	Context.Map.Constants.Peque.SpawnBurst_Instantaneous.SpawnProbability = Constants_Peque_SpawnBurst_Instantaneous_SpawnProbability;
	Context.Map.Constants.Peque.UniformRangedFloat001.Minimum = Constants_Peque_UniformRangedFloat001_Minimum;
	Context.Map.Constants.Peque.UniformRangedFloat001.Maximum = Constants_Peque_UniformRangedFloat001_Maximum;
	Context.Map.Constants.Peque.UniformRangedFloat001.RandomSeed = Constants_Peque_UniformRangedFloat001_RandomSeed;
	Context.Map.Constants.Peque.UniformRangedFloat002.Minimum = Constants_Peque_UniformRangedFloat002_Minimum;
	Context.Map.Constants.Peque.UniformRangedFloat002.Maximum = Constants_Peque_UniformRangedFloat002_Maximum;
	Context.Map.Constants.Peque.UniformRangedFloat002.RandomSeed = Constants_Peque_UniformRangedFloat002_RandomSeed;
	Context.Map.Constants.Peque.RandomVector.ConstraintVector = Constants_Peque_RandomVector_ConstraintVector;
	Context.Map.Constants.Peque.RandomVector.RandomSeed = Constants_Peque_RandomVector_RandomSeed;
	Context.Map.Constants.Peque.RandomVector001.ConstraintVector = Constants_Peque_RandomVector001_ConstraintVector;
	Context.Map.Constants.Peque.RandomVector001.RandomSeed = Constants_Peque_RandomVector001_RandomSeed;
	Context.Map.Constants.Peque.UniformRangedVector.Minimum = Constants_Peque_UniformRangedVector_Minimum;
	Context.Map.Constants.Peque.UniformRangedVector.Maximum = Constants_Peque_UniformRangedVector_Maximum;
	Context.Map.Constants.Peque.UniformRangedVector.RandomSeed = Constants_Peque_UniformRangedVector_RandomSeed;
	Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
	ReadDataSets(Context);
	Simulate(Context);
	WriteDataSets(Context);
	{
	int TmpWriteIndex = OutputIndex(0, false, true);
	OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Emitter.RandomSeed);
	OutputDataFloat(0, 1, TmpWriteIndex, Context.Map.Empty004.Age);
	OutputDataFloat(0, 2, TmpWriteIndex, Context.Map.Empty004.BeamDirection.x);
	OutputDataFloat(0, 3, TmpWriteIndex, Context.Map.Empty004.BeamDirection.y);
	OutputDataFloat(0, 4, TmpWriteIndex, Context.Map.Empty004.BeamDirection.z);
	OutputDataFloat(0, 5, TmpWriteIndex, Context.Map.Empty004.BeamEnd.x);
	OutputDataFloat(0, 6, TmpWriteIndex, Context.Map.Empty004.BeamEnd.y);
	OutputDataFloat(0, 7, TmpWriteIndex, Context.Map.Empty004.BeamEnd.z);
	OutputDataFloat(0, 8, TmpWriteIndex, Context.Map.Empty004.BeamEndTangent.x);
	OutputDataFloat(0, 9, TmpWriteIndex, Context.Map.Empty004.BeamEndTangent.y);
	OutputDataFloat(0, 10, TmpWriteIndex, Context.Map.Empty004.BeamEndTangent.z);
	OutputDataInt(0, 11, TmpWriteIndex, Context.Map.Empty004.BeamID);
	OutputDataFloat(0, 12, TmpWriteIndex, Context.Map.Empty004.BeamStart.x);
	OutputDataFloat(0, 13, TmpWriteIndex, Context.Map.Empty004.BeamStart.y);
	OutputDataFloat(0, 14, TmpWriteIndex, Context.Map.Empty004.BeamStart.z);
	OutputDataFloat(0, 15, TmpWriteIndex, Context.Map.Empty004.BeamStartEndLength);
	OutputDataFloat(0, 16, TmpWriteIndex, Context.Map.Empty004.BeamStartTangent.x);
	OutputDataFloat(0, 17, TmpWriteIndex, Context.Map.Empty004.BeamStartTangent.y);
	OutputDataFloat(0, 18, TmpWriteIndex, Context.Map.Empty004.BeamStartTangent.z);
	OutputDataFloat(0, 19, TmpWriteIndex, Context.Map.Empty004.BeamVector.x);
	OutputDataFloat(0, 20, TmpWriteIndex, Context.Map.Empty004.BeamVector.y);
	OutputDataFloat(0, 21, TmpWriteIndex, Context.Map.Empty004.BeamVector.z);
	OutputDataFloat(0, 22, TmpWriteIndex, Context.Map.Empty004.CurrentLoopDuration);
	OutputDataInt(0, 23, TmpWriteIndex, Context.Map.Empty004.ExecutionState);
	OutputDataInt(0, 24, TmpWriteIndex, Context.Map.Empty004.ExecutionStateSource);
	OutputDataBool(0, 25, TmpWriteIndex, Context.Map.Empty004.LocalSpace);
	OutputDataInt(0, 26, TmpWriteIndex, Context.Map.Empty004.LoopCount);
	OutputDataFloat(0, 27, TmpWriteIndex, Context.Map.Empty004.LoopedAge);
	OutputDataFloat(0, 28, TmpWriteIndex, Context.Map.Empty004.NormalizedLoopAge);
	OutputDataFloat(0, 29, TmpWriteIndex, Context.Map.Empty004.Scalability.DistanceFraction);
	OutputDataInt(0, 30, TmpWriteIndex, Context.Map.Empty004.SpawnBurst_Instantaneous.SpawnBurst.Count);
	OutputDataFloat(0, 31, TmpWriteIndex, Context.Map.Empty004.SpawnBurst_Instantaneous.SpawnBurst.InterpStartDt);
	OutputDataFloat(0, 32, TmpWriteIndex, Context.Map.Empty004.SpawnBurst_Instantaneous.SpawnBurst.IntervalDt);
	OutputDataInt(0, 33, TmpWriteIndex, Context.Map.Empty004.SpawnBurst_Instantaneous.SpawnBurst.SpawnGroup);
	OutputDataBool(0, 34, TmpWriteIndex, Context.Map.Empty004.UseBeamTangents);
	OutputDataFloat(0, 35, TmpWriteIndex, Context.Map.Grande.Age);
	OutputDataFloat(0, 36, TmpWriteIndex, Context.Map.Grande.BeamDirection.x);
	OutputDataFloat(0, 37, TmpWriteIndex, Context.Map.Grande.BeamDirection.y);
	OutputDataFloat(0, 38, TmpWriteIndex, Context.Map.Grande.BeamDirection.z);
	OutputDataFloat(0, 39, TmpWriteIndex, Context.Map.Grande.BeamEnd.x);
	OutputDataFloat(0, 40, TmpWriteIndex, Context.Map.Grande.BeamEnd.y);
	OutputDataFloat(0, 41, TmpWriteIndex, Context.Map.Grande.BeamEnd.z);
	OutputDataFloat(0, 42, TmpWriteIndex, Context.Map.Grande.BeamEndTangent.x);
	OutputDataFloat(0, 43, TmpWriteIndex, Context.Map.Grande.BeamEndTangent.y);
	OutputDataFloat(0, 44, TmpWriteIndex, Context.Map.Grande.BeamEndTangent.z);
	OutputDataInt(0, 45, TmpWriteIndex, Context.Map.Grande.BeamID);
	OutputDataFloat(0, 46, TmpWriteIndex, Context.Map.Grande.BeamStart.x);
	OutputDataFloat(0, 47, TmpWriteIndex, Context.Map.Grande.BeamStart.y);
	OutputDataFloat(0, 48, TmpWriteIndex, Context.Map.Grande.BeamStart.z);
	OutputDataFloat(0, 49, TmpWriteIndex, Context.Map.Grande.BeamStartEndLength);
	OutputDataFloat(0, 50, TmpWriteIndex, Context.Map.Grande.BeamStartTangent.x);
	OutputDataFloat(0, 51, TmpWriteIndex, Context.Map.Grande.BeamStartTangent.y);
	OutputDataFloat(0, 52, TmpWriteIndex, Context.Map.Grande.BeamStartTangent.z);
	OutputDataFloat(0, 53, TmpWriteIndex, Context.Map.Grande.BeamVector.x);
	OutputDataFloat(0, 54, TmpWriteIndex, Context.Map.Grande.BeamVector.y);
	OutputDataFloat(0, 55, TmpWriteIndex, Context.Map.Grande.BeamVector.z);
	OutputDataFloat(0, 56, TmpWriteIndex, Context.Map.Grande.CurrentLoopDuration);
	OutputDataInt(0, 57, TmpWriteIndex, Context.Map.Grande.ExecutionState);
	OutputDataInt(0, 58, TmpWriteIndex, Context.Map.Grande.ExecutionStateSource);
	OutputDataBool(0, 59, TmpWriteIndex, Context.Map.Grande.LocalSpace);
	OutputDataInt(0, 60, TmpWriteIndex, Context.Map.Grande.LoopCount);
	OutputDataFloat(0, 61, TmpWriteIndex, Context.Map.Grande.LoopedAge);
	OutputDataFloat(0, 62, TmpWriteIndex, Context.Map.Grande.NormalizedLoopAge);
	OutputDataFloat(0, 63, TmpWriteIndex, Context.Map.Grande.Scalability.DistanceFraction);
	OutputDataInt(0, 64, TmpWriteIndex, Context.Map.Grande.SpawnBurst_Instantaneous.SpawnBurst.Count);
	OutputDataFloat(0, 65, TmpWriteIndex, Context.Map.Grande.SpawnBurst_Instantaneous.SpawnBurst.InterpStartDt);
	OutputDataFloat(0, 66, TmpWriteIndex, Context.Map.Grande.SpawnBurst_Instantaneous.SpawnBurst.IntervalDt);
	OutputDataInt(0, 67, TmpWriteIndex, Context.Map.Grande.SpawnBurst_Instantaneous.SpawnBurst.SpawnGroup);
	OutputDataBool(0, 68, TmpWriteIndex, Context.Map.Grande.UseBeamTangents);
	OutputDataFloat(0, 69, TmpWriteIndex, Context.Map.Peque.Age);
	OutputDataFloat(0, 70, TmpWriteIndex, Context.Map.Peque.BeamDirection.x);
	OutputDataFloat(0, 71, TmpWriteIndex, Context.Map.Peque.BeamDirection.y);
	OutputDataFloat(0, 72, TmpWriteIndex, Context.Map.Peque.BeamDirection.z);
	OutputDataFloat(0, 73, TmpWriteIndex, Context.Map.Peque.BeamEnd.x);
	OutputDataFloat(0, 74, TmpWriteIndex, Context.Map.Peque.BeamEnd.y);
	OutputDataFloat(0, 75, TmpWriteIndex, Context.Map.Peque.BeamEnd.z);
	OutputDataFloat(0, 76, TmpWriteIndex, Context.Map.Peque.BeamEndTangent.x);
	OutputDataFloat(0, 77, TmpWriteIndex, Context.Map.Peque.BeamEndTangent.y);
	OutputDataFloat(0, 78, TmpWriteIndex, Context.Map.Peque.BeamEndTangent.z);
	OutputDataInt(0, 79, TmpWriteIndex, Context.Map.Peque.BeamID);
	OutputDataFloat(0, 80, TmpWriteIndex, Context.Map.Peque.BeamStart.x);
	OutputDataFloat(0, 81, TmpWriteIndex, Context.Map.Peque.BeamStart.y);
	OutputDataFloat(0, 82, TmpWriteIndex, Context.Map.Peque.BeamStart.z);
	OutputDataFloat(0, 83, TmpWriteIndex, Context.Map.Peque.BeamStartEndLength);
	OutputDataFloat(0, 84, TmpWriteIndex, Context.Map.Peque.BeamStartTangent.x);
	OutputDataFloat(0, 85, TmpWriteIndex, Context.Map.Peque.BeamStartTangent.y);
	OutputDataFloat(0, 86, TmpWriteIndex, Context.Map.Peque.BeamStartTangent.z);
	OutputDataFloat(0, 87, TmpWriteIndex, Context.Map.Peque.BeamVector.x);
	OutputDataFloat(0, 88, TmpWriteIndex, Context.Map.Peque.BeamVector.y);
	OutputDataFloat(0, 89, TmpWriteIndex, Context.Map.Peque.BeamVector.z);
	OutputDataFloat(0, 90, TmpWriteIndex, Context.Map.Peque.CurrentLoopDuration);
	OutputDataInt(0, 91, TmpWriteIndex, Context.Map.Peque.ExecutionState);
	OutputDataInt(0, 92, TmpWriteIndex, Context.Map.Peque.ExecutionStateSource);
	OutputDataBool(0, 93, TmpWriteIndex, Context.Map.Peque.LocalSpace);
	OutputDataInt(0, 94, TmpWriteIndex, Context.Map.Peque.LoopCount);
	OutputDataFloat(0, 95, TmpWriteIndex, Context.Map.Peque.LoopedAge);
	OutputDataFloat(0, 96, TmpWriteIndex, Context.Map.Peque.NormalizedLoopAge);
	OutputDataFloat(0, 97, TmpWriteIndex, Context.Map.Peque.Scalability.DistanceFraction);
	OutputDataInt(0, 98, TmpWriteIndex, Context.Map.Peque.SpawnBurst_Instantaneous.SpawnBurst.Count);
	OutputDataFloat(0, 99, TmpWriteIndex, Context.Map.Peque.SpawnBurst_Instantaneous.SpawnBurst.InterpStartDt);
	OutputDataFloat(0, 100, TmpWriteIndex, Context.Map.Peque.SpawnBurst_Instantaneous.SpawnBurst.IntervalDt);
	OutputDataInt(0, 101, TmpWriteIndex, Context.Map.Peque.SpawnBurst_Instantaneous.SpawnBurst.SpawnGroup);
	OutputDataBool(0, 102, TmpWriteIndex, Context.Map.Peque.UseBeamTangents);
	OutputDataFloat(0, 103, TmpWriteIndex, Context.Map.System.Age);
	OutputDataBool(0, 104, TmpWriteIndex, Context.Map.System.bCompleteOnInactive);
	OutputDataFloat(0, 105, TmpWriteIndex, Context.Map.System.CurrentLoopDuration);
	OutputDataInt(0, 106, TmpWriteIndex, Context.Map.System.ExecutionState);
	OutputDataInt(0, 107, TmpWriteIndex, Context.Map.System.ExecutionStateSource);
	OutputDataInt(0, 108, TmpWriteIndex, Context.Map.System.LoopCount);
	OutputDataFloat(0, 109, TmpWriteIndex, Context.Map.System.LoopedAge);
	OutputDataFloat(0, 110, TmpWriteIndex, Context.Map.System.NormalizedLoopAge);
	}
ExitStatScope( );
}
#line 703 "/Plugin/FX/Niagara/Private/NiagaraEmitterInstanceShader.usf"

#if 0 /*BEGIN_RESOURCE_TABLES*/
NULL, 0
NULL, NULL, 0, 0
#endif /*END_RESOURCE_TABLES*/
